package quality

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/devr-tools/codeguard/internal/codeguard/checks/support"
	"github.com/devr-tools/codeguard/internal/codeguard/core"
)

func TestParseCargoDeadCodeDiagnostics(t *testing.T) {
	output := `{"reason":"compiler-message","message":{"level":"error","message":"function ` + "`unused_helper`" + ` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"src/lib.rs","line_start":3,"column_start":4,"is_primary":true}]}}` + "\n" +
		`{"reason":"compiler-message","message":{"level":"warning","message":"unreachable statement","code":{"code":"unreachable_code"},"spans":[{"file_name":"src/lib.rs","line_start":8,"column_start":5,"is_primary":true}]}}` + "\n" +
		`{"reason":"compiler-message","message":{"level":"warning","message":"unused variable","code":{"code":"unused_variables"},"spans":[{"file_name":"src/lib.rs","line_start":9,"column_start":5,"is_primary":true}]}}`

	issues := parseCargoDeadCodeDiagnostics(output, t.TempDir())

	if len(issues) != 2 {
		t.Fatalf("issues len = %d, want 2: %+v", len(issues), issues)
	}
	if issues[0].code != "dead_code" || issues[0].path != "src/lib.rs" || issues[0].line != 3 || issues[0].column != 4 {
		t.Fatalf("first issue = %+v", issues[0])
	}
	if issues[1].code != "unreachable_code" || issues[1].line != 8 {
		t.Fatalf("second issue = %+v", issues[1])
	}
}

func TestParseCargoDeadCodeDiagnosticsSkipsExternalSpans(t *testing.T) {
	dir := t.TempDir()
	external := filepath.Join(filepath.Dir(dir), "external", "lib.rs")
	output := `{"reason":"compiler-message","message":{"level":"error","message":"function is never used","code":{"code":"dead_code"},"spans":[{"file_name":` + quoteJSON(external) + `,"line_start":3,"column_start":4,"is_primary":true}]}}`

	issues := parseCargoDeadCodeDiagnostics(output, dir)

	if len(issues) != 0 {
		t.Fatalf("issues = %+v, want none", issues)
	}
}

func TestRustToolchainIssueIgnoredAvoidsFalsePositiveSurfaces(t *testing.T) {
	target := core.TargetConfig{Name: "crate", Path: ".", Language: "rust"}
	tests := []struct {
		name   string
		source string
		line   int
	}{
		{
			name: "public api",
			source: `pub fn exported_api() {}
`,
			line: 1,
		},
		{
			name: "trait implementation",
			source: `trait Handler { fn handle(&self); }
struct Job;
impl Handler for Job {
    fn handle(&self) {}
}
`,
			line: 4,
		},
		{
			name: "cfg test",
			source: `#[cfg(test)]
fn helper_for_tests() {}
`,
			line: 2,
		},
		{
			name: "runtime export",
			source: `#[no_mangle]
pub extern "C" fn plugin_entrypoint() {}
`,
			line: 2,
		},
		{
			name: "generated file",
			source: `// Code generated by bindgen. DO NOT EDIT.
fn generated_helper() {}
`,
			line: 2,
		},
		{
			name: "proc macro",
			source: `extern crate proc_macro;
use proc_macro::TokenStream;

#[proc_macro]
pub fn make(_input: TokenStream) -> TokenStream { TokenStream::new() }
`,
			line: 5,
		},
		{
			name: "plugin registry",
			source: `inventory::submit! {
    Plugin::new()
}

fn registered_plugin() {}
`,
			line: 5,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			env := rustToolchainTestContext("src/lib.rs", []byte(tt.source))
			ignored := rustToolchainIssueIgnored(env, target, core.QualityDeadCodeConfig{}, rustToolchainIssue{
				path: "src/lib.rs",
				line: tt.line,
				code: "dead_code",
			})
			if !ignored {
				t.Fatal("issue was not ignored")
			}
		})
	}
}

func TestRustToolchainIssueIgnoredKeepsPrivateDeadCode(t *testing.T) {
	target := core.TargetConfig{Name: "crate", Path: ".", Language: "rust"}
	env := rustToolchainTestContext("src/lib.rs", []byte(`fn unused_helper() {}
`))

	ignored := rustToolchainIssueIgnored(env, target, core.QualityDeadCodeConfig{}, rustToolchainIssue{
		path: "src/lib.rs",
		line: 1,
		code: "dead_code",
	})

	if ignored {
		t.Fatal("private dead-code issue was ignored")
	}
}

func TestRustToolchainArtifactIssuesReportsAbsentPrivateFunction(t *testing.T) {
	dir := t.TempDir()
	writeRustToolchainTestFile(t, filepath.Join(dir, ".codeguard", "rust-symbols.txt"), `00000000 T rust_dead_code_test::used_private
`)
	env := rustToolchainMapTestContext(map[string][]byte{
		"Cargo.toml": []byte(`[package]
name = "rust-dead-code-test"
version = "0.1.0"
`),
		"src/lib.rs": []byte(`pub fn api() { used_private(); }

fn used_private() {}

fn unused_private() {}
`),
	})
	target := core.TargetConfig{Name: "crate", Path: dir, Language: "rust"}

	issues, err := rustToolchainArtifactIssues(env, target, core.QualityDeadCodeConfig{
		Rust: core.RustDeadCodeConfig{Reports: []string{".codeguard/rust-symbols.txt"}},
	})

	if err != nil {
		t.Fatalf("artifact issues: %v", err)
	}
	if len(issues) != 1 {
		t.Fatalf("issues len = %d, want 1: %+v", len(issues), issues)
	}
	if issues[0].code != rustToolchainArtifactCode || issues[0].path != "src/lib.rs" || issues[0].line != 5 {
		t.Fatalf("issue = %+v, want artifact issue for src/lib.rs:5", issues[0])
	}
}

func TestRustToolchainArtifactIssuesRecognizesLegacyMangledUsedSymbols(t *testing.T) {
	dir := t.TempDir()
	writeRustToolchainTestFile(t, filepath.Join(dir, ".codeguard", "rust-symbols.txt"), `_ZN19rust_dead_code_test12used_private17h1234567890abcdefE
`)
	env := rustToolchainMapTestContext(map[string][]byte{
		"Cargo.toml": []byte(`[package]
name = "rust-dead-code-test"
version = "0.1.0"
`),
		"src/lib.rs": []byte(`fn used_private() {}

fn unused_private() {}
`),
	})
	target := core.TargetConfig{Name: "crate", Path: dir, Language: "rust"}

	issues, err := rustToolchainArtifactIssues(env, target, core.QualityDeadCodeConfig{
		Rust: core.RustDeadCodeConfig{Reports: []string{".codeguard/rust-symbols.txt"}},
	})

	if err != nil {
		t.Fatalf("artifact issues: %v", err)
	}
	if len(issues) != 1 || issues[0].line != 3 {
		t.Fatalf("issues = %+v, want only unused_private", issues)
	}
}

func TestRustToolchainArtifactIssuesRequiresSameModuleEvidence(t *testing.T) {
	dir := t.TempDir()
	writeRustToolchainTestFile(t, filepath.Join(dir, ".codeguard", "rust-symbols.txt"), `00000000 T other_crate::used_private
`)
	env := rustToolchainMapTestContext(map[string][]byte{
		"Cargo.toml": []byte(`[package]
name = "rust-dead-code-test"
version = "0.1.0"
`),
		"src/lib.rs": []byte(`fn unused_private() {}
`),
	})
	target := core.TargetConfig{Name: "crate", Path: dir, Language: "rust"}

	issues, err := rustToolchainArtifactIssues(env, target, core.QualityDeadCodeConfig{
		Rust: core.RustDeadCodeConfig{Reports: []string{".codeguard/rust-symbols.txt"}},
	})

	if err != nil {
		t.Fatalf("artifact issues: %v", err)
	}
	if len(issues) != 0 {
		t.Fatalf("issues = %+v, want none without same-module evidence", issues)
	}
}

func TestRustToolchainArtifactCandidatesAvoidFalsePositiveSurfaces(t *testing.T) {
	source := []byte(`pub fn exported_api() {}

#[inline]
fn inline_helper() {}

fn generic_helper<T>(value: T) -> T { value }

#[no_mangle]
extern "C" fn plugin_entrypoint() {}

fn used_private() {}
`)
	env := rustToolchainMapTestContext(map[string][]byte{
		"Cargo.toml": []byte(`[package]
name = "rust-dead-code-test"
version = "0.1.0"
`),
		"src/lib.rs": source,
	})
	target := core.TargetConfig{Name: "crate", Path: ".", Language: "rust"}

	candidates := rustToolchainArtifactCandidates(env, target, core.QualityDeadCodeConfig{})

	if len(candidates) != 1 {
		t.Fatalf("candidates = %+v, want only used_private", candidates)
	}
	if candidates[0].name != "used_private" {
		t.Fatalf("candidate = %+v, want used_private", candidates[0])
	}
}

func rustToolchainTestContext(path string, data []byte) support.Context {
	return support.Context{
		ReadTargetFile: func(_ core.TargetConfig, rel string) ([]byte, error) {
			if filepath.ToSlash(rel) != filepath.ToSlash(path) {
				return nil, os.ErrNotExist
			}
			return data, nil
		},
		VisitTargetFiles: func(core.TargetConfig, func(string) bool, func(string, []byte)) {},
	}
}

func rustToolchainMapTestContext(files map[string][]byte) support.Context {
	return support.Context{
		ReadTargetFile: func(_ core.TargetConfig, rel string) ([]byte, error) {
			data, ok := files[filepath.ToSlash(rel)]
			if !ok {
				return nil, os.ErrNotExist
			}
			return data, nil
		},
		VisitTargetFiles: func(_ core.TargetConfig, include func(string) bool, visit func(string, []byte)) {
			for rel, data := range files {
				if include == nil || include(rel) {
					visit(rel, data)
				}
			}
		},
	}
}

func writeRustToolchainTestFile(t *testing.T, path string, data string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(data), 0o600); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func quoteJSON(value string) string {
	var out strings.Builder
	out.WriteByte('"')
	for _, r := range value {
		switch r {
		case '\\':
			out.WriteString(`\\`)
		case '"':
			out.WriteString(`\"`)
		default:
			out.WriteRune(r)
		}
	}
	out.WriteByte('"')
	return out.String()
}
