// Package codeguard exposes module-level assets that must live at the
// repository root. Currently it embeds CHANGELOG.md so the CLI can surface
// recent release highlights in its "What's New" banner without shipping a
// duplicate copy of the changelog.
package codeguard

import _ "embed"

// Changelog is the full contents of CHANGELOG.md, embedded at build time.
// It is generated by release-please in conventional-changelog format.
//
//go:embed CHANGELOG.md
var Changelog string
