package support

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/devr-tools/codeguard/internal/codeguard/core"
)

func TestTypeScriptRuntimeDiscoveryIgnoresTargetDependencies(t *testing.T) {
	t.Setenv(codeguardTypeScriptLibEnv, "")
	previousDefaults := defaultTypeScriptLibCandidates
	defaultTypeScriptLibCandidates = nil
	t.Cleanup(func() { defaultTypeScriptLibCandidates = previousDefaults })

	target := t.TempDir()
	repositoryRuntime := filepath.Join(target, "node_modules", "typescript", "lib", "typescript.js")
	if err := os.MkdirAll(filepath.Dir(repositoryRuntime), 0o755); err != nil {
		t.Fatalf("create repository runtime directory: %v", err)
	}
	if err := os.WriteFile(repositoryRuntime, []byte("malicious JavaScript"), 0o644); err != nil {
		t.Fatalf("write repository runtime: %v", err)
	}

	if got := discoverTypeScriptLibPath(target); got != "" {
		t.Fatalf("discovered repository-controlled TypeScript runtime %q", got)
	}
}

func TestTypeScriptRuntimeDiscoveryHonorsExplicitRuntime(t *testing.T) {
	configuredRuntime := filepath.Join(t.TempDir(), "typescript.js")
	if err := os.WriteFile(configuredRuntime, []byte("trusted JavaScript"), 0o644); err != nil {
		t.Fatalf("write configured runtime: %v", err)
	}
	t.Setenv(codeguardTypeScriptLibEnv, configuredRuntime)

	if got := discoverTypeScriptLibPath(t.TempDir()); got != configuredRuntime {
		t.Fatalf("discovered runtime = %q, want explicitly configured runtime %q", got, configuredRuntime)
	}
}

func TestTypeScriptTargetSourceFilesUsesFilteredCorpus(t *testing.T) {
	target := core.TargetConfig{Path: "/repo"}
	files := TypeScriptTargetSourceFiles(Context{
		ListTargetFiles: func(core.TargetConfig) ([]string, error) {
			// In production this list is generated by the runner's exclusion-aware
			// corpus. Dependency and generated paths never reach this callback.
			return []string{"src/app.ts", "README.md"}, nil
		},
	}, target)

	want := []string{"src/app.ts"}
	if !reflect.DeepEqual(files, want) {
		t.Fatalf("semantic source files = %q, want %q", files, want)
	}
}

func TestTypeScriptSemanticFlightDeduplicatesConcurrentRequests(t *testing.T) {
	cacheKey := "semantic-flight-test"
	first, leader := typeScriptSemanticFlightFor(cacheKey)
	if !leader {
		t.Fatal("first request was not selected as the semantic-run leader")
	}
	second, leader := typeScriptSemanticFlightFor(cacheKey)
	if leader {
		t.Fatal("second request started a duplicate semantic run")
	}
	if first != second {
		t.Fatal("concurrent requests did not share the same semantic flight")
	}

	first.results = TypeScriptSemanticResults{Debug: []string{"complete"}}
	typeScriptSemanticFinishFlight(cacheKey, first)
	<-second.done
	if !reflect.DeepEqual(second.results.Debug, []string{"complete"}) {
		t.Fatalf("shared semantic result = %q, want completion result", second.results.Debug)
	}
}

func TestSemanticSourcePathsAreRelativeToTarget(t *testing.T) {
	root := t.TempDir()
	got := semanticSourcePaths(root, []string{"src/app.ts"})
	want := []string{filepath.Join(root, "src", "app.ts")}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("semantic source paths = %q, want %q", got, want)
	}
}
