package support

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/devr-tools/codeguard/internal/codeguard/core"
)

func TestTypeScriptSemanticRunnerIntersectsCorpusWithConfiguredFiles(t *testing.T) {
	if _, err := exec.LookPath("node"); err != nil {
		t.Skip("node is required for the embedded semantic runner test")
	}

	root := t.TempDir()
	libPath := filepath.Join(root, "fake-typescript.js")
	fakeTypeScript := `
const path = require("path");
module.exports = {
  ScriptTarget: { Latest: 99 }, ModuleKind: { ESNext: 99 }, JsxEmit: { Preserve: 99 },
  sys: { readFile() {}, fileExists() { return true; }, readDirectory() { return []; } },
  findConfigFile(root) { return path.join(root, "tsconfig.json"); },
  readConfigFile() { return { config: {} }; },
  parseJsonConfigFileContent(config, sys, root) {
    return { fileNames: [path.join(root, "src/app.ts")], options: {} };
  },
  createProgram({ rootNames }) { throw new Error("ROOTS=" + JSON.stringify(rootNames)); },
  flattenDiagnosticMessageText(value) { return String(value); },
};`
	if err := os.WriteFile(libPath, []byte(fakeTypeScript), 0o600); err != nil {
		t.Fatal(err)
	}

	input := typeScriptSemanticInput{
		TypeScriptLibPath: libPath,
		TargetPath:        root,
		SourceFiles: []string{
			filepath.Join(root, "src/app.ts"),
			filepath.Join(root, "vendor/excluded.ts"),
			filepath.Join(root, "node_modules/pkg/index.ts"),
		},
	}
	_, err := runTypeScriptSemanticRunner(context.Background(), input)
	if err == nil {
		t.Fatal("semantic runner succeeded; want fake compiler root report")
	}
	message := err.Error()
	if !strings.Contains(message, filepath.Join(root, "src/app.ts")) {
		t.Fatalf("configured corpus root missing from compiler roots: %s", message)
	}
	for _, excluded := range []string{"vendor/excluded.ts", "node_modules/pkg/index.ts"} {
		if strings.Contains(message, excluded) {
			t.Fatalf("tsconfig-excluded corpus file %q reached compiler roots: %s", excluded, message)
		}
	}
}

func TestTypeScriptTargetSourceFilesUsesFilteredCorpus(t *testing.T) {
	target := core.TargetConfig{Path: "/repo"}
	files := TypeScriptTargetSourceFiles(Context{
		ListTargetFiles: func(core.TargetConfig) ([]string, error) {
			// In production this list is generated by the runner's exclusion-aware
			// corpus. Dependency and generated paths never reach this callback.
			return []string{"src/app.ts", "README.md"}, nil
		},
	}, target)

	want := []string{"src/app.ts"}
	if !reflect.DeepEqual(files, want) {
		t.Fatalf("semantic source files = %q, want %q", files, want)
	}
}

func TestTypeScriptSemanticFlightDeduplicatesConcurrentRequests(t *testing.T) {
	cacheKey := "semantic-flight-test"
	first, leader := typeScriptSemanticFlightFor(cacheKey)
	if !leader {
		t.Fatal("first request was not selected as the semantic-run leader")
	}
	second, leader := typeScriptSemanticFlightFor(cacheKey)
	if leader {
		t.Fatal("second request started a duplicate semantic run")
	}
	if first != second {
		t.Fatal("concurrent requests did not share the same semantic flight")
	}

	first.results = TypeScriptSemanticResults{Debug: []string{"complete"}}
	typeScriptSemanticFinishFlight(cacheKey, first)
	<-second.done
	if !reflect.DeepEqual(second.results.Debug, []string{"complete"}) {
		t.Fatalf("shared semantic result = %q, want completion result", second.results.Debug)
	}
}

func TestSemanticSourcePathsAreRelativeToTarget(t *testing.T) {
	root := t.TempDir()
	got := semanticSourcePaths(root, []string{"src/app.ts"})
	want := []string{filepath.Join(root, "src", "app.ts")}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("semantic source paths = %q, want %q", got, want)
	}
}
