package support

import (
	"path/filepath"
	"reflect"
	"testing"

	"github.com/devr-tools/codeguard/internal/codeguard/core"
)

func TestTypeScriptTargetSourceFilesUsesFilteredCorpus(t *testing.T) {
	target := core.TargetConfig{Path: "/repo"}
	files := TypeScriptTargetSourceFiles(Context{
		ListTargetFiles: func(core.TargetConfig) ([]string, error) {
			// In production this list is generated by the runner's exclusion-aware
			// corpus. Dependency and generated paths never reach this callback.
			return []string{"src/app.ts", "README.md"}, nil
		},
	}, target)

	want := []string{"src/app.ts"}
	if !reflect.DeepEqual(files, want) {
		t.Fatalf("semantic source files = %q, want %q", files, want)
	}
}

func TestTypeScriptSemanticFlightDeduplicatesConcurrentRequests(t *testing.T) {
	cacheKey := "semantic-flight-test"
	first, leader := typeScriptSemanticFlightFor(cacheKey)
	if !leader {
		t.Fatal("first request was not selected as the semantic-run leader")
	}
	second, leader := typeScriptSemanticFlightFor(cacheKey)
	if leader {
		t.Fatal("second request started a duplicate semantic run")
	}
	if first != second {
		t.Fatal("concurrent requests did not share the same semantic flight")
	}

	first.results = TypeScriptSemanticResults{Debug: []string{"complete"}}
	typeScriptSemanticFinishFlight(cacheKey, first)
	<-second.done
	if !reflect.DeepEqual(second.results.Debug, []string{"complete"}) {
		t.Fatalf("shared semantic result = %q, want completion result", second.results.Debug)
	}
}

func TestSemanticSourcePathsAreRelativeToTarget(t *testing.T) {
	root := t.TempDir()
	got := semanticSourcePaths(root, []string{"src/app.ts"})
	want := []string{filepath.Join(root, "src", "app.ts")}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("semantic source paths = %q, want %q", got, want)
	}
}
