package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

// qualityAIFixTemplates covers the AI-slop heuristics and the LLM-assisted
// semantic review rules. All are guided: the templates show the shape of the
// fix and the evidence to check, not a mechanical rewrite.
var qualityAIFixTemplates = map[string]core.FixTemplate{
	"quality.ai.swallowed-error":        {Kind: guided, Text: "Handle the error explicitly instead of discarding it.\n\nBefore:\nresult, _ := doWork()\n\nAfter:\nresult, err := doWork()\nif err != nil {\n\treturn fmt.Errorf(\"do work: %w\", err)\n}"},
	"quality.ai.narrative-comment":      {Kind: guided, Text: "Delete comments that narrate the adjacent code, or rewrite them to capture intent, constraints, or tradeoffs.\n\nBefore:\n// loop over the users and print each one\nfor _, user := range users {\n\tfmt.Println(user)\n}\n\nAfter:\n// emit one line per user so the audit job can diff snapshots\nfor _, user := range users {\n\tfmt.Println(user)\n}"},
	"quality.ai.hallucinated-import":    {Kind: guided, Text: "Replace the unresolved import with a dependency that exists in the repository, or add the dependency to the module manifest intentionally.\n\nBefore:\nimport { fetchJson } from \"super-fetch-utils\"; // not in package.json\n\nAfter:\n// either: npm install super-fetch-utils\n// or import the local equivalent that already exists:\nimport { fetchJson } from \"./lib/fetch-json\";"},
	"quality.ai.dead-code":              {Kind: guided, Text: "Delete the unreachable constant-condition branch or replace the placeholder with a real runtime check.\n\nBefore:\nif (false) {\n  runLegacyMigration();\n}\n\nAfter:\nif (config.legacyMigrationEnabled) {\n  runLegacyMigration();\n}\n// or delete the branch and its dead callee entirely"},
	"quality.ai.error-style-drift":      {Kind: guided, Text: "Match the repository's dominant error-handling convention instead of introducing a divergent style in one file.\n\nBefore:\nif err != nil {\n\treturn err // repo convention wraps errors with %w context\n}\n\nAfter:\nif err != nil {\n\treturn fmt.Errorf(\"load config: %w\", err)\n}"},
	"quality.ai.naming-drift":           {Kind: guided, Text: "Rename the divergent identifiers to the repository's dominant naming convention.\n\nBefore:\nconst user_display_name = getUser().name; // camelCase codebase\n\nAfter:\nconst userDisplayName = getUser().name;"},
	"quality.ai.over-mocked-test":       {Kind: guided, Text: "Exercise the real unit boundary and assert on observable behavior instead of mock wiring.\n\nBefore:\nmockRepo.On(\"Save\", mock.Anything).Return(nil)\nsvc.Create(user)\nmockRepo.AssertExpectations(t)\n\nAfter:\nrepo := newInMemoryRepo()\nsvc := NewService(repo)\nsvc.Create(user)\nif got := len(repo.All()); got != 1 {\n\tt.Fatalf(\"saved users = %d, want 1\", got)\n}"},
	"quality.ai.local-idiom-drift":      {Kind: guided, Text: "Rewrite the new tests in the repository's established testing idiom.\n\nBefore:\n// repo uses standard-library table tests; the new file introduces an assertion library\nassert.Equal(t, want, got)\n\nAfter:\nif got != want {\n\tt.Fatalf(\"Process() = %v, want %v\", got, want)\n}"},
	"quality.ai.change-risk":            {Kind: guided, Text: "Reduce the risky surface of the change before merge: check the diff size, new dependencies, test coverage, and unresolved quality.ai findings driving the score.\n\nBefore:\n// one patch: 800 changed lines, a new dependency, no new tests, swallowed errors\n\nAfter:\n// split the patch into reviewable steps\n// add tests that cover the changed behavior\n// resolve the individual quality.ai findings so the risk score drops"},
	"quality.ai.provenance-policy":      {Kind: guided, Text: "Resolve the AI-quality findings that trip the stricter AI-assisted thresholds, or correct the provenance tag if it was set by mistake.\n\nBefore:\n// commit trailer marks the change AI-assisted and quality.ai warnings remain\n\nAfter:\n// keep the trailer and resolve the quality.ai findings before merge\n// or remove the provenance tag if the change was not AI-assisted"},
	"quality.ai.semantic-doc-mismatch":  {Kind: guided, Text: "Align the function name, adjacent documentation, and implementation so all three describe the same behavior; check which of the three the change actually intended.\n\nBefore:\n// fetchActiveUsers returns the active users.\nfunc fetchActiveUsers() []User {\n\treturn allUsers() // returns inactive users too\n}\n\nAfter:\n// fetchAllUsers returns every user regardless of status.\nfunc fetchAllUsers() []User {\n\treturn allUsers()\n}\n// or keep the name and filter to active users, updating callers and tests"},
	"quality.ai.contract-drift":         {Kind: guided, Text: "Make the behavior change explicit and keep docs, errors, and tests aligned with the new contract.\n\nBefore:\n// BuildUser creates a user record.\nfunc BuildUser() error {\n\treturn errors.New(\"user deleted\")\n}\n\nAfter:\n// DeleteUser removes an existing user record.\nfunc DeleteUser() error {\n\treturn errors.New(\"user deleted\")\n}\n// or keep BuildUser semantics and restore create behavior with matching tests"},
	"quality.ai.semantic-error-message": {Kind: guided, Text: "Rewrite the error message so it names the actual failing operation, resource, and condition; verify it against the code path that produces it.\n\nBefore:\nreturn fmt.Errorf(\"failed to save user\") // raised while reading the config file\n\nAfter:\nreturn fmt.Errorf(\"read config %s: %w\", path, err)"},
	"quality.ai.semantic-test-coverage": {Kind: guided, Text: "Add a test that exercises the changed branch, return value, or failure mode; confirm the new behavior is what the assertion observes.\n\nBefore:\n// the change adds a retry branch to Fetch(); no test triggers a retry\n\nAfter:\nfunc TestFetchRetriesOnTimeout(t *testing.T) {\n\tsrv := flakyServer(1) // fails once, then succeeds\n\tif _, err := Fetch(srv.URL); err != nil {\n\t\tt.Fatalf(\"expected retry to recover, got %v\", err)\n\t}\n}"},
	"quality.ai.semantic-test-adequacy": {Kind: guided, Text: "Strengthen the nearby tests so they prove the changed behavior with meaningful assertions, negative paths, and boundary coverage.\n\nBefore:\nfunc TestBuildUser(t *testing.T) {\n\tBuildUser()\n}\n\nAfter:\nfunc TestBuildUserReturnsErrorOnConflict(t *testing.T) {\n\terr := BuildUser(conflictingInput)\n\tif err == nil {\n\t\tt.Fatal(\"expected conflict error\")\n\t}\n\tif !strings.Contains(err.Error(), \"conflict\") {\n\t\tt.Fatalf(\"error = %v, want conflict details\", err)\n\t}\n}"},
	"quality.ai.semantic-runtime":       {Kind: guided, Text: "Point the semantic review provider at an installed command that returns valid JSON, or disable semantic review explicitly.\n\nBefore:\n{\n  \"ai\": {\n    \"semantic\": { \"enabled\": true },\n    \"provider\": { \"type\": \"command\", \"command\": \"missing-reviewer\" }\n  }\n}\n\nAfter:\n{\n  \"ai\": {\n    \"semantic\": { \"enabled\": true },\n    \"provider\": { \"type\": \"command\", \"command\": \"/usr/local/bin/semantic-reviewer\" }\n  }\n}\n// run the command by hand and fix any crash or malformed JSON it reports"},
}
