package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

// performanceFixTemplates covers the performance section heuristics.
var performanceFixTemplates = map[string]core.FixTemplate{
	"performance.sync-io-in-request-path":          {Kind: guided, Text: "Load the data once at startup or cache it instead of reading the filesystem per request.\n\nBefore:\nfunc handler(w http.ResponseWriter, r *http.Request) {\n\tdata, _ := os.ReadFile(\"config.json\")\n\tw.Write(data)\n}\n\nAfter:\nvar config = mustLoadConfig(\"config.json\") // loaded once at startup\n\nfunc handler(w http.ResponseWriter, r *http.Request) {\n\tw.Write(config)\n}"},
	"performance.unbounded-goroutines-in-loop":     {Kind: guided, Text: "Bound loop-driven concurrency with a worker pool, semaphore, or errgroup limit.\n\nBefore:\nfor _, job := range jobs {\n\tgo process(job)\n}\n\nAfter:\ngroup, ctx := errgroup.WithContext(ctx)\ngroup.SetLimit(8)\nfor _, job := range jobs {\n\tgroup.Go(func() error { return process(ctx, job) })\n}\nif err := group.Wait(); err != nil {\n\treturn err\n}"},
	"performance.n-plus-one-query":                 {Kind: guided, Text: "Batch the per-item lookups into one query issued before the loop.\n\nBefore:\nfor _, id := range ids {\n\tuser, _ := db.GetUser(ctx, id)\n\tusers = append(users, user)\n}\n\nAfter:\nusers, err := db.GetUsersByIDs(ctx, ids) // single batched query"},
	"performance.go.alloc-in-loop":                 {Kind: guided, Text: "Use strings.Builder for string accumulation and preallocate slice capacity before the loop.\n\nBefore:\nvar out string\nfor _, line := range lines {\n\tout += line + \"\\n\"\n}\n\nAfter:\nvar b strings.Builder\nfor _, line := range lines {\n\tb.WriteString(line)\n\tb.WriteByte('\\n')\n}\nout := b.String()"},
	"performance.rust.alloc-in-loop":               {Kind: guided, Text: "Preallocate the String or collect parts and join once.\n\nBefore:\nlet mut out = String::new();\nfor row in rows {\n    out.push_str(render(row).as_str());\n}\n\nAfter:\nlet mut out = String::with_capacity(rows.len() * 32);\nfor row in rows {\n    out.push_str(render(row).as_str());\n}\n// or: let out = rows.iter().map(render).collect::<Vec<_>>().join(\"\")"},
	"performance.cpp.alloc-in-loop":                {Kind: guided, Text: "Reserve string capacity before the loop, or collect fragments and concatenate once after it.\n\nBefore:\nstd::string out;\nfor (const auto& row : rows) {\n  out += render(row);\n}\n\nAfter:\nstd::string out;\nout.reserve(rows.size() * 32);\nfor (const auto& row : rows) {\n  out += render(row);\n}\n// or collect into std::vector<std::string> and join once"},
	"performance.typescript.sync-io-in-handler":    {Kind: guided, Text: "Switch to the promise-based API inside request handlers so the event loop is not blocked.\n\nBefore:\napp.get(\"/report\", (req, res) => {\n  const data = fs.readFileSync(\"report.json\", \"utf8\");\n  res.send(data);\n});\n\nAfter:\napp.get(\"/report\", async (req, res) => {\n  const data = await fs.promises.readFile(\"report.json\", \"utf8\");\n  res.send(data);\n});"},
	"performance.javascript.sync-io-in-handler":    {Kind: guided, Text: "Switch to the promise-based API inside request handlers so the event loop is not blocked.\n\nBefore:\napp.get(\"/report\", (req, res) => {\n  res.send(fs.readFileSync(\"report.json\"));\n});\n\nAfter:\nconst fsp = require(\"fs/promises\");\napp.get(\"/report\", async (req, res) => {\n  res.send(await fsp.readFile(\"report.json\"));\n});"},
	"performance.typescript.unbounded-concurrency": {Kind: guided, Text: "Process the work in bounded chunks or wrap calls with a concurrency limiter.\n\nBefore:\nfor (const url of urls) {\n  promises.push(fetch(url));\n}\nawait Promise.all(promises);\n\nAfter:\nimport pLimit from \"p-limit\";\nconst limit = pLimit(8);\nawait Promise.all(urls.map((url) => limit(() => fetch(url))));"},
	"performance.javascript.unbounded-concurrency": {Kind: guided, Text: "Process the work in bounded chunks or wrap calls with a concurrency limiter.\n\nBefore:\nfor (const url of urls) {\n  promises.push(fetch(url));\n}\nawait Promise.all(promises);\n\nAfter:\nfor (let i = 0; i < urls.length; i += 8) {\n  await Promise.all(urls.slice(i, i + 8).map((url) => fetch(url)));\n}"},
	"performance.python.sync-io-in-async":          {Kind: guided, Text: "Use async clients and asyncio.sleep inside async functions so the event loop is not blocked.\n\nBefore:\nasync def refresh():\n    data = requests.get(url).json()\n    time.sleep(1)\n\nAfter:\nasync def refresh():\n    async with httpx.AsyncClient() as client:\n        data = (await client.get(url)).json()\n    await asyncio.sleep(1)"},
	"performance.regex-compile-in-loop":            {Kind: deterministic, Text: "Compile the pattern once outside the loop and reuse it.\n\nBefore:\nfor _, line := range lines {\n\tre := regexp.MustCompile(`\\d+`)\n\tif re.MatchString(line) { ... }\n}\n\nAfter:\nvar digits = regexp.MustCompile(`\\d+`) // compiled once\n\nfor _, line := range lines {\n\tif digits.MatchString(line) { ... }\n}"},
	"performance.go.defer-in-loop":                 {Kind: guided, Text: "Release per-iteration resources explicitly, or extract the loop body into a function so the defer runs each iteration.\n\nBefore:\nfor _, path := range paths {\n\tf, _ := os.Open(path)\n\tdefer f.Close() // all files stay open until the function returns\n}\n\nAfter:\nfor _, path := range paths {\n\tif err := processFile(path); err != nil { ... }\n}\n\nfunc processFile(path string) error {\n\tf, err := os.Open(path)\n\tif err != nil {\n\t\treturn err\n\t}\n\tdefer f.Close() // closes at the end of each iteration\n\t...\n}"},
	"performance.go.sleep-in-loop":                 {Kind: guided, Text: "Replace the polling sleep with a ticker, a channel signal, or backoff.\n\nBefore:\nfor {\n\tif ready() {\n\t\tbreak\n\t}\n\ttime.Sleep(100 * time.Millisecond)\n}\n\nAfter:\nticker := time.NewTicker(100 * time.Millisecond)\ndefer ticker.Stop()\nfor range ticker.C {\n\tif ready() {\n\t\tbreak\n\t}\n}\n// or better: have the producer signal readiness on a channel"},
	"performance.rust.sleep-in-loop":               {Kind: guided, Text: "Replace the polling sleep with a proper synchronization primitive or bounded backoff.\n\nBefore:\nloop {\n    if ready() { break; }\n    std::thread::sleep(Duration::from_millis(100));\n}\n\nAfter:\nwhile !ready() {\n    receiver.recv_timeout(Duration::from_millis(100)).ok();\n}\n// or use a Condvar / watch channel so readiness is signaled instead of polled"},
	"performance.cpp.sleep-in-loop":                {Kind: guided, Text: "Replace the polling sleep with a condition variable, timer primitive, or bounded backoff helper.\n\nBefore:\nwhile (!ready()) {\n  std::this_thread::sleep_for(std::chrono::milliseconds(100));\n}\n\nAfter:\nstd::unique_lock<std::mutex> lock(mu);\ncv.wait_for(lock, std::chrono::milliseconds(100), [&] { return ready(); });\n// or use an event/timer abstraction instead of polling"},
	"performance.cpp.unbounded-concurrency":        {Kind: guided, Text: "Bound loop-driven thread/task creation with a fixed worker pool, semaphore, or bounded executor.\n\nBefore:\nfor (const auto& job : jobs) {\n  threads.emplace_back(run, job);\n}\n\nAfter:\nThreadPool pool(8);\nfor (const auto& job : jobs) {\n  pool.submit(run, job);\n}\npool.wait();"},
	"performance.go.timer-leak-in-loop":            {Kind: deterministic, Text: "Reuse one timer instead of allocating a new one per iteration with time.After.\n\nBefore:\nfor {\n\tselect {\n\tcase msg := <-inbox:\n\t\thandle(msg)\n\tcase <-time.After(time.Second): // leaks a timer per iteration\n\t\treturn\n\t}\n}\n\nAfter:\ntimer := time.NewTimer(time.Second)\ndefer timer.Stop()\nfor {\n\tselect {\n\tcase msg := <-inbox:\n\t\thandle(msg)\n\t\ttimer.Reset(time.Second)\n\tcase <-timer.C:\n\t\treturn\n\t}\n}"},
	"performance.unbounded-read":                   {Kind: guided, Text: "Bound the read or process the input as a stream.\n\nBefore:\nfunc handler(w http.ResponseWriter, r *http.Request) {\n\tbody, _ := io.ReadAll(r.Body) // one oversized request = whole payload in memory\n}\n\nAfter:\nfunc handler(w http.ResponseWriter, r *http.Request) {\n\tbody, err := io.ReadAll(io.LimitReader(r.Body, 1<<20)) // 1 MiB cap\n}\n// Python: read(65536) in a loop, or iterate the file object line by line"},
	"performance.go.hot-package":                   {Kind: guided, Text: "Reduce direct fan-in to the package so ordinary edits do not force broad recompiles.\n\nBefore:\ninternal/platform/config    // imported directly by many packages\n\nAfter:\ninternal/platform/config/schema   // stable leaf types\ninternal/platform/config/load     // volatile implementation\n// move frequently changing code behind smaller leaf packages or interfaces"},
	"performance.go.rebuild-amplifier":             {Kind: guided, Text: "Break the package apart so changes stop cascading through the transitive import graph.\n\nBefore:\ninternal/core // depends on many details and is imported nearly everywhere\n\nAfter:\ninternal/core/contracts  // stable shared interfaces\ninternal/core/runtime    // volatile implementation details\n// pull fast-changing code into narrower leaves and keep shared contracts small"},
	"performance.cpp.hot-header":                   {Kind: guided, Text: "Reduce direct include fan-in so ordinary header edits do not force broad recompilation.\n\nBefore:\n// common.hpp includes unrelated declarations and is included everywhere\n\nAfter:\n// split focused declarations into narrow headers and use forward declarations where possible"},
	"performance.cpp.rebuild-amplifier":            {Kind: guided, Text: "Break the transitive include cascade around the header/module.\n\nBefore:\n// core.hpp includes volatile implementation headers and is imported broadly\n\nAfter:\n// keep stable declarations in core.hpp; move implementation dependencies into .cpp files or private modules"},
	"performance.string-concat-in-loop":            {Kind: deterministic, Text: "Collect the parts and join once after the loop.\n\nBefore:\nout = \"\"\nfor row in rows:\n    out += render(row)\n\nAfter:\nparts = [render(row) for row in rows]\nout = \"\".join(parts)\n// TS/JS: const parts: string[] = []; parts.push(render(row)); const out = parts.join(\"\")"},
	"performance.python.unbounded-concurrency":     {Kind: guided, Text: "Bound loop-driven task creation with a semaphore or task group.\n\nBefore:\nfor url in urls:\n    asyncio.create_task(fetch(url))\n\nAfter:\nsem = asyncio.Semaphore(8)\n\nasync def bounded_fetch(url):\n    async with sem:\n        return await fetch(url)\n\nasync with asyncio.TaskGroup() as group:\n    for url in urls:\n        group.create_task(bounded_fetch(url))"},
	"performance.typescript.await-in-loop":         {Kind: guided, Text: "Run independent iterations concurrently with Promise.all.\n\nBefore:\nfor (const id of ids) {\n  const user = await fetchUser(id); // serial round-trips\n  users.push(user);\n}\n\nAfter:\nconst users = await Promise.all(ids.map((id) => fetchUser(id)));\n// keep the loop only when each iteration depends on the previous one"},
	"performance.javascript.await-in-loop":         {Kind: guided, Text: "Run independent iterations concurrently with Promise.all.\n\nBefore:\nfor (const id of ids) {\n  const user = await fetchUser(id); // serial round-trips\n  users.push(user);\n}\n\nAfter:\nconst users = await Promise.all(ids.map((id) => fetchUser(id)));\n// keep the loop only when each iteration depends on the previous one"},
	"performance.typescript.timer-listener-leak":   {Kind: guided, Text: "Store timer handles and clean up listeners on teardown.\n\nBefore:\nsetInterval(poll, 1000); // no clearInterval anywhere\nfor (const el of items) {\n  el.addEventListener(\"click\", onClick);\n}\n\nAfter:\nconst handle = setInterval(poll, 1000);\nconst controller = new AbortController();\nfor (const el of items) {\n  el.addEventListener(\"click\", onClick, { signal: controller.signal });\n}\n// on teardown:\nclearInterval(handle);\ncontroller.abort();"},
	"performance.javascript.timer-listener-leak":   {Kind: guided, Text: "Store timer handles and clean up listeners on teardown.\n\nBefore:\nsetInterval(poll, 1000); // no clearInterval anywhere\nfor (const el of items) {\n  el.addEventListener(\"click\", onClick);\n}\n\nAfter:\nconst handle = setInterval(poll, 1000);\nconst controller = new AbortController();\nfor (const el of items) {\n  el.addEventListener(\"click\", onClick, { signal: controller.signal });\n}\n// on teardown:\nclearInterval(handle);\ncontroller.abort();"},
}
