package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var catalog = map[string]core.RuleMetadata{
	"quality.gofmt": {
		ID:             "quality.gofmt",
		Section:        "Code Quality",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Go formatting",
		Description:    "Fails when a Go source file is not gofmt-clean.",
		HowToFix:       "Run gofmt on the file and commit the formatted result.",
	},
	"quality.parse-error": {
		ID:             "quality.parse-error",
		Section:        "Code Quality",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Go parseability",
		Description:    "Fails when a Go source file cannot be parsed.",
		HowToFix:       "Fix the syntax error so the file parses cleanly.",
	},
	"quality.max-file-lines": {
		ID:             "quality.max-file-lines",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "File length",
		Description:    "Warns when a file exceeds the configured maximum line count.",
		HowToFix:       "Split the file into smaller units or raise the configured threshold intentionally.",
	},
	"quality.max-function-lines": {
		ID:             "quality.max-function-lines",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Function length",
		Description:    "Warns when a function exceeds the configured maximum line count.",
		HowToFix:       "Break the function into smaller helpers or raise the threshold intentionally.",
	},
	"quality.max-parameters": {
		ID:             "quality.max-parameters",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Function parameters",
		Description:    "Warns when a function exceeds the configured parameter count.",
		HowToFix:       "Group related inputs into a struct or simplify the function signature.",
	},
	"quality.cyclomatic-complexity": {
		ID:             "quality.cyclomatic-complexity",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Cyclomatic complexity",
		Description:    "Warns when a function exceeds the configured cyclomatic complexity threshold.",
		HowToFix:       "Reduce branching in the function or refactor logic into smaller units.",
	},
	"quality.dependency-direction": {
		ID:             "quality.dependency-direction",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Dependency direction",
		Description:    "Warns when non-CLI packages import CLI-only implementation details.",
		HowToFix:       "Move shared logic into reusable packages and keep internal or CLI details out of library code.",
	},
	"quality.command-check": {
		ID:             "quality.command-check",
		Section:        "Code Quality",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		Title:          "Language quality command",
		Description:    "Fails when a configured language-specific quality command exits non-zero.",
		HowToFix:       "Fix the reported issue from the command output or adjust the configured command if it does not fit the target.",
	},
	"quality.typescript.ts-ignore": {
		ID:             "quality.typescript.ts-ignore",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript suppression comment",
		Description:    "Warns when TypeScript code uses @ts-ignore to suppress type checking.",
		HowToFix:       "Remove the suppression by correcting the underlying type issue or replacing it with a narrower escape hatch.",
	},
	"quality.typescript.explicit-any": {
		ID:             "quality.typescript.explicit-any",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript explicit any",
		Description:    "Warns when TypeScript code opts out of type safety with explicit any.",
		HowToFix:       "Use a narrower type, a generic constraint, or a targeted unknown-based refinement instead of any.",
	},
	"quality.typescript.ts-nocheck": {
		ID:             "quality.typescript.ts-nocheck",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript file-level suppression",
		Description:    "Warns when a TypeScript file disables type checking with @ts-nocheck.",
		HowToFix:       "Remove the file-level suppression and address the underlying type errors directly.",
	},
	"quality.typescript.double-assertion": {
		ID:             "quality.typescript.double-assertion",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript double assertion",
		Description:    "Warns when TypeScript code uses chained assertions such as as unknown as T to bypass type safety.",
		HowToFix:       "Replace the double assertion with a narrower source type, runtime validation, or a safer refinement step.",
	},
	"quality.typescript.non-null-assertion": {
		ID:             "quality.typescript.non-null-assertion",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript non-null assertion",
		Description:    "Warns when TypeScript code forces nullability away with the non-null assertion operator.",
		HowToFix:       "Prove nullability through control flow, validation, or safer API design instead of using ! assertions.",
	},
	"design.cmd-through-internal-cli": {
		ID:             "design.cmd-through-internal-cli",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Command layer routing",
		Description:    "Fails when cmd entrypoints import reusable service packages directly instead of going through internal/cli.",
		HowToFix:       "Route command execution through internal/cli and keep cmd thin.",
	},
	"design.service-import-internal": {
		ID:             "design.service-import-internal",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Service to internal import",
		Description:    "Fails when reusable public packages, other than the SDK facade, import internal packages.",
		HowToFix:       "Move the dependency behind a public boundary or relocate the service code.",
	},
	"design.service-import-cmd": {
		ID:             "design.service-import-cmd",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Service to cmd import",
		Description:    "Fails when reusable service code imports cmd packages.",
		HowToFix:       "Move shared behavior into a reusable package and keep cmd packages as entrypoints only.",
	},
	"design.generic-package-name": {
		ID:             "design.generic-package-name",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Generic package name",
		Description:    "Warns when a package name is too generic to communicate ownership or responsibility.",
		HowToFix:       "Rename the package to something specific to its responsibility.",
	},
	"design.max-methods-per-type": {
		ID:             "design.max-methods-per-type",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Methods per type",
		Description:    "Warns when a type accumulates too many methods.",
		HowToFix:       "Split responsibilities across smaller types or interfaces.",
	},
	"design.max-interface-methods": {
		ID:             "design.max-interface-methods",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Interface size",
		Description:    "Warns when an interface is too large.",
		HowToFix:       "Break the interface into smaller focused contracts.",
	},
	"design.max-decls-per-file": {
		ID:             "design.max-decls-per-file",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Declarations per file",
		Description:    "Warns when a file accumulates too many top-level declarations.",
		HowToFix:       "Move related declarations into smaller files with clearer ownership.",
	},
	"design.typescript.generic-module-name": {
		ID:             "design.typescript.generic-module-name",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript generic module name",
		Description:    "Warns when a TypeScript or JavaScript module name is too generic to communicate ownership or responsibility.",
		HowToFix:       "Rename the module to something specific to its responsibility.",
	},
	"design.typescript.max-methods-per-type": {
		ID:             "design.typescript.max-methods-per-type",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript methods per type",
		Description:    "Warns when a TypeScript class accumulates too many methods.",
		HowToFix:       "Split responsibilities across smaller classes or extracted collaborators.",
	},
	"design.typescript.max-interface-members": {
		ID:             "design.typescript.max-interface-members",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript interface size",
		Description:    "Warns when a TypeScript interface or object type accumulates too many members.",
		HowToFix:       "Break the interface or type into smaller focused contracts.",
	},
	"design.python.public-imports-private": {
		ID:             "design.python.public-imports-private",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python public-to-private import",
		Description:    "Fails when a public Python module imports a private module or private symbol.",
		HowToFix:       "Keep private helpers behind the public module boundary or move shared logic into a public module.",
	},
	"design.python.public-imports-cli": {
		ID:             "design.python.public-imports-cli",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python public-to-entrypoint import",
		Description:    "Fails when a public Python module imports a CLI or entrypoint module.",
		HowToFix:       "Move shared behavior into a reusable module and keep entrypoints thin.",
	},
	"design.python.generic-module-name": {
		ID:             "design.python.generic-module-name",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python generic module name",
		Description:    "Warns when a Python module name is too generic to communicate ownership or responsibility.",
		HowToFix:       "Rename the module to something specific to its responsibility.",
	},
	"security.hardcoded-secret": {
		ID:             "security.hardcoded-secret",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Hardcoded secret",
		Description:    "Fails when a likely hardcoded secret is detected in source text.",
		HowToFix:       "Remove the secret from the repository and load it from a secret manager or environment at runtime.",
	},
	"security.private-key": {
		ID:             "security.private-key",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Private key material",
		Description:    "Fails when PEM private key material is detected.",
		HowToFix:       "Delete the committed key, rotate the credential, and load key material from secure storage.",
	},
	"security.insecure-tls": {
		ID:             "security.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Insecure TLS",
		Description:    "Fails when insecure TLS verification is explicitly disabled.",
		HowToFix:       "Enable certificate verification and use trusted certificates in non-local environments.",
	},
	"security.shell-execution": {
		ID:             "security.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Shell execution review",
		Description:    "Warns when shell execution primitives are used and should receive manual review.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain command execution.",
	},
	"security.govulncheck": {
		ID:             "security.govulncheck",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		Title:          "Govulncheck finding",
		Description:    "Surfaces vulnerabilities or integration failures from govulncheck.",
		HowToFix:       "Install govulncheck, then upgrade or replace the affected dependency and re-run the scan.",
	},
	"security.command-check": {
		ID:             "security.command-check",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		Title:          "Language security command",
		Description:    "Fails when a configured language-specific security command exits non-zero.",
		HowToFix:       "Fix the reported issue from the command output or adjust the configured command if it does not fit the target.",
	},
	"prompts.secret-interpolation": {
		ID:             "prompts.secret-interpolation",
		Section:        "AI Prompts",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Prompt secret interpolation",
		Description:    "Fails when prompt assets interpolate likely secret values.",
		HowToFix:       "Remove secret placeholders from prompt assets and inject secrets outside the prompt text.",
	},
	"prompts.unsafe-instructions": {
		ID:             "prompts.unsafe-instructions",
		Section:        "AI Prompts",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Unsafe prompt instructions",
		Description:    "Warns when prompt assets contain instruction-injection or system prompt exfiltration patterns.",
		HowToFix:       "Rewrite the prompt to remove instruction override or prompt exfiltration language.",
	},
	"ci.required-workflow-dir": {
		ID:             "ci.required-workflow-dir",
		Section:        "CI/CD",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Workflow directory",
		Description:    "Fails when the configured workflow directory is required but missing.",
		HowToFix:       "Add the required workflow directory or disable the policy explicitly.",
	},
	"ci.required-file": {
		ID:             "ci.required-file",
		Section:        "CI/CD",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Required CI file",
		Description:    "Fails when required workflow, release, or automation files are missing.",
		HowToFix:       "Add the required file or remove the policy requirement if it does not apply.",
	},
	"ci.workflow-content": {
		ID:             "ci.workflow-content",
		Section:        "CI/CD",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Workflow content",
		Description:    "Fails when required workflow file markers are absent.",
		HowToFix:       "Update the workflow file so the required steps or markers are present.",
	},
	"ci.test-file-location": {
		ID:             "ci.test-file-location",
		Section:        "CI/CD",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Test file location",
		Description:    "Fails when language-specific test files live outside the configured test directories.",
		HowToFix:       "Move the test file under the configured test path or update the CI policy if the layout is intentional.",
	},
	"security.typescript.insecure-tls": {
		ID:             "security.typescript.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript insecure TLS",
		Description:    "Fails when TypeScript or JavaScript code disables TLS verification.",
		HowToFix:       "Enable certificate verification and use trusted certificates in non-local environments.",
	},
	"security.typescript.shell-execution": {
		ID:             "security.typescript.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript shell execution review",
		Description:    "Warns when TypeScript or JavaScript code invokes shell execution primitives.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain command execution.",
	},
	"security.typescript.dynamic-code": {
		ID:             "security.typescript.dynamic-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript dynamic code execution",
		Description:    "Warns when TypeScript or JavaScript code evaluates dynamic source text.",
		HowToFix:       "Remove eval-style execution or strictly constrain and validate the executed content.",
	},
	"security.typescript.vm-dynamic-code": {
		ID:             "security.typescript.vm-dynamic-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript Node vm execution",
		Description:    "Warns when TypeScript or JavaScript code uses Node vm APIs to compile or execute dynamic code.",
		HowToFix:       "Avoid dynamic vm execution, or strictly constrain and validate the executed content and context.",
	},
	"security.typescript.unsafe-html-sink": {
		ID:             "security.typescript.unsafe-html-sink",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript unsafe HTML sink",
		Description:    "Warns when TypeScript or JavaScript code writes untrusted content into unsafe HTML injection sinks.",
		HowToFix:       "Prefer safe DOM APIs or sanitize content before writing to HTML sinks.",
	},
	"security.python.insecure-tls": {
		ID:             "security.python.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python insecure TLS",
		Description:    "Fails when Python code disables TLS verification.",
		HowToFix:       "Enable certificate verification and use trusted certificates in non-local environments.",
	},
	"security.python.shell-execution": {
		ID:             "security.python.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python shell execution review",
		Description:    "Warns when Python code invokes shell execution primitives.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain command execution.",
	},
	"security.python.dynamic-code": {
		ID:             "security.python.dynamic-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python dynamic code execution",
		Description:    "Warns when Python code evaluates or executes dynamic source text.",
		HowToFix:       "Remove eval or exec usage, or strictly constrain and validate the executed content.",
	},
}

func Catalog() map[string]core.RuleMetadata {
	out := make(map[string]core.RuleMetadata, len(catalog))
	for id, meta := range catalog {
		out[id] = core.NormalizeRuleMetadata(meta)
	}
	return out
}
