package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

// qualityAICatalog covers the AI-failure-mode rule pack (quality.ai.*): the
// deterministic heuristics plus the semantic-runtime verdict rules. Split
// from qualityCatalog so each catalog file stays within the repo's own
// file-size budget.
var qualityAICatalog = map[string]core.RuleMetadata{
	"quality.ai.swallowed-error": {
		ID:             "quality.ai.swallowed-error",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "AI-style swallowed error",
		Description: "Warns when code drops errors through blank assignments, empty catch blocks, or pass-only exception handlers that are common in AI-generated patches.",
		HowToFix:    "Handle the error explicitly, add logging or propagation, or document the intentional suppression with a narrow justification.",
	},
	"quality.ai.narrative-comment": {
		ID:             "quality.ai.narrative-comment",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "Narrative comment",
		Description: "Warns when comments merely narrate nearby code instead of explaining intent, constraints, or non-obvious tradeoffs, a common LLM failure mode.",
		HowToFix:    "Delete the narration or rewrite the comment so it captures why the code exists, what constraint it protects, or what tradeoff it makes.",
	},
	"quality.ai.hallucinated-import": {
		ID:             "quality.ai.hallucinated-import",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "Hallucinated import",
		Description: "Warns when an import cannot be resolved against local module manifests, declared dependencies, standard libraries, or local files, which is a common AI-generated code failure mode.",
		HowToFix:    "Replace the import with a dependency that exists in the repo, add the missing dependency intentionally, or fix the path or package name.",
	},
	"quality.ai.dead-code": {
		ID:             "quality.ai.dead-code",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "Plausible but dead code",
		Description: "Warns when code contains unreachable constant-condition branches, statements after unconditional returns or raises, or private functions that are never referenced, all common leftovers in AI-generated patches.",
		HowToFix:    "Delete the unreachable or unused code, replace the placeholder with a real condition, or wire the function into the code path that was supposed to call it.",
	},
	"quality.ai.error-style-drift": {
		ID:             "quality.ai.error-style-drift",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "Error-handling style drift",
		Description: "Warns when a file's error-handling style diverges from the repository's dominant convention, such as unwrapped errors in a %w-wrapping Go codebase, bare except clauses in a typed-except Python codebase, or raw Error throws in a custom-error-class TypeScript codebase.",
		HowToFix:    "Match the repository's established error-handling convention, or migrate the convention deliberately across the codebase rather than in a single file.",
	},
	"quality.ai.naming-drift": {
		ID:             "quality.ai.naming-drift",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "Identifier naming drift",
		Description: "Warns when a file's identifier naming convention (snake_case vs camelCase) diverges from the repository's dominant convention, a common smell in AI-generated contributions.",
		HowToFix:    "Rename the divergent identifiers to match the repository's dominant naming convention.",
	},
	"quality.ai.over-mocked-test": {
		ID:             "quality.ai.over-mocked-test",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "Over-mocked test",
		Description: "Warns when a test leans heavily on mocks and stubs with little direct assertion signal, a common sign that AI-generated tests are only verifying the mock setup.",
		HowToFix:    "Prefer exercising the real unit boundary, reduce mock setup, and add assertions about behavior or outputs instead of only expectations on doubles.",
	},
	"quality.ai.local-idiom-drift": {
		ID:             "quality.ai.local-idiom-drift",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "Codebase idiom drift",
		Description: "Warns when new tests diverge from the repository's dominant local testing idiom, which is a common smell in AI-generated contributions that are technically valid but inconsistent.",
		HowToFix:    "Match the established local framework and style unless there is a deliberate migration plan with repository-wide buy-in.",
	},
	"quality.ai.change-risk": {
		ID:               "quality.ai.change-risk",
		Section:          "Code Quality",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.RepositoryWideRuleLanguageCoverage(),
		Title:            "AI change risk",
		Description:      "Warns when an AI-assisted or AI-shaped change accumulates enough risky signals that it should receive stricter review before merge.",
		HowToFix:         "Reduce the risky surface area of the change, add or strengthen tests, split the patch into smaller steps, or resolve the AI-quality findings driving the score.",
	},
	"quality.ai.provenance-policy": {
		ID:               "quality.ai.provenance-policy",
		Section:          "Code Quality",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.RepositoryWideRuleLanguageCoverage(),
		Title:            "AI provenance policy",
		Description:      "Applies stricter review thresholds when the current change is tagged as AI-assisted through configured environment hints or commit trailers.",
		HowToFix:         "Reduce the AI-slop signals in the change, lower the risk surface, or remove the AI-assisted provenance tag if it was set incorrectly.",
	},
	"quality.ai.semantic-doc-mismatch": {
		ID:             "quality.ai.semantic-doc-mismatch",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "Semantic function and docs mismatch",
		Description: "Warns when optional LLM-assisted semantic review finds that a changed function name or adjacent documentation no longer matches the implementation.",
		HowToFix:    "Rename the function, update the surrounding documentation, or change the implementation so all three describe the same behavior.",
	},
	"quality.ai.contract-drift": {
		ID:             "quality.ai.contract-drift",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "Semantic contract drift",
		Description: "Warns when optional LLM-assisted semantic review finds that a changed function appears to drift from its prior behavior or surrounding contract without a clear caller-facing update.",
		HowToFix:    "Align the implementation, nearby docs, error semantics, and tests around the intended contract, or make the caller-visible behavior change explicit and fully covered.",
	},
	"quality.ai.semantic-error-message": {
		ID:             "quality.ai.semantic-error-message",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "Semantic error-message mismatch",
		Description: "Warns when optional LLM-assisted semantic review finds that a changed error message misstates the actual failing condition, resource, or recovery path.",
		HowToFix:    "Rewrite the error message so it names the actual failing operation or condition and gives operators an accurate debugging breadcrumb.",
	},
	"quality.ai.semantic-test-coverage": {
		ID:             "quality.ai.semantic-test-coverage",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "Semantic changed-behavior test gap",
		Description: "Warns when optional LLM-assisted semantic review finds that changed behavior does not appear to be exercised by nearby repository tests.",
		HowToFix:    "Add or update tests that cover the new branch, return value, failure mode, or externally visible behavior introduced by the change.",
	},
	"quality.ai.semantic-test-adequacy": {
		ID:             "quality.ai.semantic-test-adequacy",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "Semantic test adequacy gap",
		Description: "Warns when optional LLM-assisted semantic review finds that nearby tests for a changed behavior look weak, overly happy-path, or otherwise inadequate for the risk introduced by the change.",
		HowToFix:    "Strengthen the nearby tests so they exercise the changed behavior with meaningful assertions, negative paths, and relevant edge cases instead of only shallow or mock-heavy checks.",
	},
	"quality.ai.semantic-runtime": {
		ID:             "quality.ai.semantic-runtime",
		Section:        "Code Quality",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "Semantic review runtime failure",
		Description: "Fails when semantic review was enabled but the configured command was missing, crashed, or returned invalid output, so the scan would otherwise lose semantic coverage silently.",
		HowToFix:    "Configure a valid semantic command, then fix any runtime or JSON response errors so semantic review can run deterministically.",
	},
}
