package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var qualitySmellCatalog = map[string]core.RuleMetadata{
	"smell.god-object": {
		ID:             "smell.god-object",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageCPP,
			core.RuleLanguageGo,
			core.RuleLanguageJavaScript,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
		),
		Title:       "God object",
		Description: "Warns when a local type/class accumulates many methods, fields, and responsibility clusters.",
		HowToFix:    "Split cohesive responsibilities into smaller collaborators or value objects and keep the original type focused on orchestration only when necessary.",
	},
	"smell.feature-envy": {
		ID:             "smell.feature-envy",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageCPP,
			core.RuleLanguageGo,
			core.RuleLanguageJavaScript,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
		),
		Title:       "Feature envy",
		Description: "Warns when a function or method mostly interrogates one external collaborator instead of its own receiver/context.",
		HowToFix:    "Move the behavior closer to the data owner, add a named operation on the collaborator, or pass a richer domain object.",
	},
	"smell.middle-man": {
		ID:             "smell.middle-man",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageCPP,
			core.RuleLanguageGo,
			core.RuleLanguageJavaScript,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
		),
		Title:       "Middle man",
		Description: "Warns when a type/class mostly forwards calls to one collaborator without policy, translation, or ownership.",
		HowToFix:    "Inline the pass-through layer, or add meaningful policy/translation so the abstraction earns its place.",
	},
	"smell.message-chain": {
		ID:             "smell.message-chain",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageCPP,
			core.RuleLanguageGo,
			core.RuleLanguageJavaScript,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
		),
		Title:       "Message chain",
		Description: "Warns when code reaches through a long chain of collaborators, increasing coupling to object structure.",
		HowToFix:    "Introduce a named query/helper at the boundary or move the traversal behind the object that owns the structure.",
	},
	"smell.data-clump": {
		ID:             "smell.data-clump",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageCPP,
			core.RuleLanguageGo,
			core.RuleLanguageJavaScript,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
		),
		Title:       "Data clump",
		Description: "Warns when the same group of primitive/domain parameters appears repeatedly across functions.",
		HowToFix:    "Extract the repeated group into a value object, options type, or request DTO that can hold invariants and names.",
	},
	"smell.switch-on-type": {
		ID:             "smell.switch-on-type",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageCPP,
			core.RuleLanguageGo,
			core.RuleLanguageJavaScript,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
		),
		Title:       "Switch on type",
		Description: "Warns when behavior repeatedly branches on type/kind/discriminator checks that should move behind polymorphism or dispatch.",
		HowToFix:    "Replace repeated type/kind branches with polymorphic methods, strategy objects, or a centralized dispatch table.",
	},
}
