package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var supplyChainCatalog = map[string]core.RuleMetadata{
	"supply_chain.vulnerable-dependency": {
		ID:               "supply_chain.vulnerable-dependency",
		Section:          "Supply Chain",
		DefaultLevel:     "fail",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.RepositoryWideRuleLanguageCoverage(),
		Title:            "Vulnerable dependency",
		Description:      "Fails when a normalized dependency matches an affected version range in the configured local advisory cache.",
		HowToFix:         "Upgrade to a version outside the advisory's affected range, then refresh the lockfile and advisory cache through the approved update process.",
	},
	"supply_chain.unpinned-dependency": {
		ID:               "supply_chain.unpinned-dependency",
		Section:          "Supply Chain",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.RepositoryWideRuleLanguageCoverage(),
		Title:            "Unpinned dependency",
		Description:      "Warns when a dependency declaration does not pin to a concrete version or digest.",
		HowToFix:         "Pin the dependency to a reviewed version or digest and commit the corresponding lockfile update.",
	},
	"supply_chain.missing-lockfile": {
		ID:               "supply_chain.missing-lockfile",
		Section:          "Supply Chain",
		DefaultLevel:     "fail",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.RepositoryWideRuleLanguageCoverage(),
		Title:            "Missing lockfile",
		Description:      "Fails when a supported package manifest is committed without its expected lockfile.",
		HowToFix:         "Generate and commit the lockfile that matches the manifest before merging the change.",
	},
	"supply_chain.lockfile-drift": {
		ID:               "supply_chain.lockfile-drift",
		Section:          "Supply Chain",
		DefaultLevel:     "fail",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.RepositoryWideRuleLanguageCoverage(),
		Title:            "Lockfile drift",
		Description:      "Fails when a manifest change is not reflected in the associated lockfile.",
		HowToFix:         "Regenerate the lockfile from the updated manifest and commit both files together.",
	},
	"supply_chain.denied-license": {
		ID:               "supply_chain.denied-license",
		Section:          "Supply Chain",
		DefaultLevel:     "fail",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.RepositoryWideRuleLanguageCoverage(),
		Title:            "Denied dependency license",
		Description:      "Fails when a dependency resolves to a license that violates configured policy.",
		HowToFix:         "Replace or upgrade the dependency, or adjust the license policy if the exception is intentional and approved.",
	},
	"supply_chain.cargo.missing-package-license": {
		ID:               "supply_chain.cargo.missing-package-license",
		Section:          "Supply Chain",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(core.RuleLanguageRust),
		Title:            "Cargo package license missing",
		Description:      "Warns when a Cargo.toml package omits the package.license field, making license policy and artifact metadata harder to audit.",
		HowToFix:         "Add a reviewed SPDX license expression to package.license in Cargo.toml.",
	},
	"supply_chain.cargo.non-hermetic-source": {
		ID:               "supply_chain.cargo.non-hermetic-source",
		Section:          "Supply Chain",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(core.RuleLanguageRust),
		Title:            "Cargo dependency source is non-hermetic",
		Description:      "Warns when a Cargo dependency uses a local path source, a floating git branch, or a git source without a pinned rev.",
		HowToFix:         "Replace the source with a registry release, or pin the git dependency to an exact rev and avoid path-based sources in committed manifests.",
	},
}
