package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

// qualityFixTemplates covers the non-AI quality rules, including the
// TypeScript/JavaScript suppression mirrors and the performance heuristics.
var qualityFixTemplates = map[string]core.FixTemplate{
	"quality.gofmt":                            {Kind: deterministic, Text: "Run gofmt -w on the file and commit the formatted result.\n\nBefore:\nfunc main(){fmt.Println(\"hi\")}\n\nAfter:\nfunc main() {\n\tfmt.Println(\"hi\")\n}"},
	"quality.parse-error":                      {Kind: guided, Text: "Fix the syntax error the parser reports so the file parses cleanly.\n\nBefore:\nfunc main() {\n\tfmt.Println(\"hi\")\n// missing closing brace\n\nAfter:\nfunc main() {\n\tfmt.Println(\"hi\")\n}"},
	"quality.max-file-lines":                   {Kind: guided, Text: "Split the file into smaller files with one responsibility each.\n\nBefore:\n// handlers.go: routing, validation, persistence, and rendering in one 900-line file\n\nAfter:\n// handlers.go: HTTP routing only\n// validate.go: input validation\n// store.go: persistence\n// render.go: response rendering"},
	"quality.max-function-lines":               {Kind: guided, Text: "Extract cohesive steps into named helpers until the function fits the configured limit.\n\nBefore:\nfunc handle(req Request) (Response, error) {\n\t// dozens of lines: validate, transform, persist, render\n}\n\nAfter:\nfunc handle(req Request) (Response, error) {\n\tinput, err := validate(req)\n\tif err != nil {\n\t\treturn Response{}, err\n\t}\n\trecord := transform(input)\n\tif err := persist(record); err != nil {\n\t\treturn Response{}, err\n\t}\n\treturn render(record), nil\n}"},
	"quality.max-parameters":                   {Kind: guided, Text: "Group related parameters into an options struct.\n\nBefore:\nfunc render(w io.Writer, title string, body string, width int, height int, theme string) error\n\nAfter:\ntype RenderOptions struct {\n\tTitle, Body   string\n\tWidth, Height int\n\tTheme         string\n}\n\nfunc render(w io.Writer, opts RenderOptions) error"},
	"quality.cyclomatic-complexity":            {Kind: guided, Text: "Flatten branching with early returns, or replace branch ladders with table-driven dispatch.\n\nBefore:\nif ok {\n\tif valid {\n\t\tif ready {\n\t\t\tprocess()\n\t\t}\n\t}\n}\n\nAfter:\nif !ok || !valid || !ready {\n\treturn\n}\nprocess()"},
	"quality.duplicate-code":                   {Kind: guided, Text: "Extract the duplicated block into one shared helper and call it from every copy site.\n\nBefore:\n// the same parse-validate-normalize sequence repeated in create.go and update.go\n\nAfter:\nfunc normalizeInput(raw Input) (Input, error) {\n\t// shared implementation\n}\n// create.go and update.go both call normalizeInput"},
	"quality.dependency-direction":             {Kind: guided, Text: "Move the shared logic into a reusable package so library code stops importing CLI internals.\n\nBefore:\n// internal/report/report.go\nimport \"example.com/app/internal/cli\" // library imports CLI details\n\nAfter:\n// move the shared helper from internal/cli into a reusable package\nimport \"example.com/app/internal/render\""},
	"quality.command-check":                    {Kind: guided, Text: "Run the configured quality command locally and fix each reported finding at its source.\n\nBefore:\n$ golangci-lint run\nstore.go:42:2: ineffectual assignment to err\n\nAfter:\n// handle or return err at store.go:42, then re-run until the command exits 0\n// adjust the configured command only if it does not fit the target"},
	"quality.sync-io-in-request-path":          {Kind: guided, Text: "Load the data once at startup or cache it instead of reading the filesystem per request.\n\nBefore:\nfunc handler(w http.ResponseWriter, r *http.Request) {\n\tdata, _ := os.ReadFile(\"config.json\")\n\tw.Write(data)\n}\n\nAfter:\nvar config = mustLoadConfig(\"config.json\") // loaded once at startup\n\nfunc handler(w http.ResponseWriter, r *http.Request) {\n\tw.Write(config)\n}"},
	"quality.unbounded-goroutines-in-loop":     {Kind: guided, Text: "Bound loop-driven concurrency with a worker pool, semaphore, or errgroup limit.\n\nBefore:\nfor _, job := range jobs {\n\tgo process(job)\n}\n\nAfter:\ngroup, ctx := errgroup.WithContext(ctx)\ngroup.SetLimit(8)\nfor _, job := range jobs {\n\tgroup.Go(func() error { return process(ctx, job) })\n}\nif err := group.Wait(); err != nil {\n\treturn err\n}"},
	"quality.coverage-delta":                   {Kind: guided, Text: "Add or extend tests so the changed lines are exercised.\n\nBefore:\n// the diff adds a new error branch in Process() that no test reaches\n\nAfter:\nfunc TestProcessRejectsEmptyInput(t *testing.T) {\n\tif _, err := Process(\"\"); err == nil {\n\t\tt.Fatal(\"expected error for empty input\")\n\t}\n}"},
	"quality.n-plus-one-query":                 {Kind: guided, Text: "Batch the per-item lookups into one query issued before the loop.\n\nBefore:\nfor _, id := range ids {\n\tuser, _ := db.GetUser(ctx, id)\n\tusers = append(users, user)\n}\n\nAfter:\nusers, err := db.GetUsersByIDs(ctx, ids) // single batched query"},
	"quality.go.alloc-in-loop":                 {Kind: guided, Text: "Use strings.Builder for string accumulation and preallocate slice capacity before the loop.\n\nBefore:\nvar out string\nfor _, line := range lines {\n\tout += line + \"\\n\"\n}\n\nAfter:\nvar b strings.Builder\nfor _, line := range lines {\n\tb.WriteString(line)\n\tb.WriteByte('\\n')\n}\nout := b.String()"},
	"quality.typescript.sync-io-in-handler":    {Kind: guided, Text: "Switch to the promise-based API inside request handlers so the event loop is not blocked.\n\nBefore:\napp.get(\"/report\", (req, res) => {\n  const data = fs.readFileSync(\"report.json\", \"utf8\");\n  res.send(data);\n});\n\nAfter:\napp.get(\"/report\", async (req, res) => {\n  const data = await fs.promises.readFile(\"report.json\", \"utf8\");\n  res.send(data);\n});"},
	"quality.javascript.sync-io-in-handler":    {Kind: guided, Text: "Switch to the promise-based API inside request handlers so the event loop is not blocked.\n\nBefore:\napp.get(\"/report\", (req, res) => {\n  res.send(fs.readFileSync(\"report.json\"));\n});\n\nAfter:\nconst fsp = require(\"fs/promises\");\napp.get(\"/report\", async (req, res) => {\n  res.send(await fsp.readFile(\"report.json\"));\n});"},
	"quality.typescript.unbounded-concurrency": {Kind: guided, Text: "Process the work in bounded chunks or wrap calls with a concurrency limiter.\n\nBefore:\nfor (const url of urls) {\n  promises.push(fetch(url));\n}\nawait Promise.all(promises);\n\nAfter:\nimport pLimit from \"p-limit\";\nconst limit = pLimit(8);\nawait Promise.all(urls.map((url) => limit(() => fetch(url))));"},
	"quality.javascript.unbounded-concurrency": {Kind: guided, Text: "Process the work in bounded chunks or wrap calls with a concurrency limiter.\n\nBefore:\nfor (const url of urls) {\n  promises.push(fetch(url));\n}\nawait Promise.all(promises);\n\nAfter:\nfor (let i = 0; i < urls.length; i += 8) {\n  await Promise.all(urls.slice(i, i + 8).map((url) => fetch(url)));\n}"},
	"quality.python.sync-io-in-async":          {Kind: guided, Text: "Use async clients and asyncio.sleep inside async functions so the event loop is not blocked.\n\nBefore:\nasync def refresh():\n    data = requests.get(url).json()\n    time.sleep(1)\n\nAfter:\nasync def refresh():\n    async with httpx.AsyncClient() as client:\n        data = (await client.get(url)).json()\n    await asyncio.sleep(1)"},
	"quality.typescript.ts-ignore":             {Kind: guided, Text: "Fix the underlying type error and delete the @ts-ignore suppression.\n\nBefore:\n// @ts-ignore\nconst id = user.id;\n\nAfter:\nif (user === undefined) {\n  throw new Error(\"user is required\");\n}\nconst id = user.id;"},
	"quality.typescript.explicit-any":          {Kind: guided, Text: "Replace any with a precise type, a generic constraint, or unknown plus narrowing.\n\nBefore:\nfunction parse(input: any): any {\n  return JSON.parse(input);\n}\n\nAfter:\nfunction parse<T>(input: string): T {\n  return JSON.parse(input) as T;\n}"},
	"quality.typescript.ts-nocheck":            {Kind: guided, Text: "Delete the file-level @ts-nocheck and fix the type errors it hides.\n\nBefore:\n// @ts-nocheck\nexport function total(items) {\n  return items.reduce((sum, item) => sum + item.price, 0);\n}\n\nAfter:\nexport function total(items: LineItem[]): number {\n  return items.reduce((sum, item) => sum + item.price, 0);\n}"},
	"quality.typescript.double-assertion":      {Kind: guided, Text: "Replace the as unknown as chain with runtime validation or a narrower source type.\n\nBefore:\nconst user = payload as unknown as User;\n\nAfter:\nconst user = parseUser(payload); // validates the shape and returns User\nfunction parseUser(value: unknown): User {\n  if (!isUser(value)) {\n    throw new Error(\"invalid user payload\");\n  }\n  return value;\n}"},
	"quality.typescript.non-null-assertion":    {Kind: guided, Text: "Prove nullability with a guard instead of asserting it away with !.\n\nBefore:\nconst name = user!.name;\n\nAfter:\nif (user === null) {\n  throw new Error(\"user is required\");\n}\nconst name = user.name;"},
	"quality.typescript.ts-expect-error":       {Kind: guided, Text: "Fix the underlying type error and delete the @ts-expect-error suppression.\n\nBefore:\n// @ts-expect-error\nconst id = user.id;\n\nAfter:\nif (user === undefined) {\n  throw new Error(\"user is required\");\n}\nconst id = user.id;"},
	"quality.typescript.debugger-statement":    {Kind: deterministic, Text: "Remove the committed debugger statement; use tests or structured logging instead.\n\nBefore:\nfunction onSubmit(data: FormData) {\n  debugger;\n  send(data);\n}\n\nAfter:\nfunction onSubmit(data: FormData) {\n  send(data);\n}"},
	"quality.javascript.ts-ignore":             {Kind: guided, Text: "Fix the underlying type error and delete the @ts-ignore suppression.\n\nBefore:\n// @ts-ignore\nconst id = user.id;\n\nAfter:\nif (user === undefined) {\n  throw new Error(\"user is required\");\n}\nconst id = user.id;"},
	"quality.javascript.explicit-any":          {Kind: guided, Text: "Replace any with a precise type, a generic constraint, or unknown plus narrowing.\n\nBefore:\n/** @param {any} input */\nfunction parse(input) {\n  return JSON.parse(input);\n}\n\nAfter:\n/** @param {string} input @returns {Config} */\nfunction parse(input) {\n  return JSON.parse(input);\n}"},
	"quality.javascript.ts-nocheck":            {Kind: guided, Text: "Delete the file-level @ts-nocheck and fix the type errors it hides.\n\nBefore:\n// @ts-nocheck\n/** @param {Array<{price: number}>} items */\nfunction total(items) {\n  return items.reduce((sum, item) => sum + item.price, 0);\n}\n\nAfter:\n/** @param {Array<{price: number}>} items @returns {number} */\nfunction total(items) {\n  return items.reduce((sum, item) => sum + item.price, 0);\n}"},
	"quality.javascript.double-assertion":      {Kind: guided, Text: "Replace the JSDoc cast chain with runtime validation of the value's shape.\n\nBefore:\nconst user = /** @type {User} */ (/** @type {unknown} */ (payload));\n\nAfter:\nconst user = parseUser(payload); // validates the shape and returns User\nfunction parseUser(value) {\n  if (!isUser(value)) {\n    throw new Error(\"invalid user payload\");\n  }\n  return value;\n}"},
	"quality.javascript.non-null-assertion":    {Kind: guided, Text: "Prove nullability with a guard instead of asserting it away with !.\n\nBefore:\nconst name = user!.name;\n\nAfter:\nif (user === null) {\n  throw new Error(\"user is required\");\n}\nconst name = user.name;"},
	"quality.javascript.ts-expect-error":       {Kind: guided, Text: "Fix the underlying type error and delete the @ts-expect-error suppression.\n\nBefore:\n// @ts-expect-error\nconst id = user.id;\n\nAfter:\nif (user === undefined) {\n  throw new Error(\"user is required\");\n}\nconst id = user.id;"},
	"quality.javascript.debugger-statement":    {Kind: deterministic, Text: "Remove the committed debugger statement; use tests or structured logging instead.\n\nBefore:\nfunction onSubmit(data) {\n  debugger;\n  send(data);\n}\n\nAfter:\nfunction onSubmit(data) {\n  send(data);\n}"},
}
