package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var dataFixTemplates = map[string]core.FixTemplate{
	"data.read-modify-write-race":             {Kind: guided, Text: "Make the read and write atomic.\n\nBefore:\nrow := repo.Get(id)\nrow.Count++\nrepo.Update(row)\n\nAfter:\nrepo.InTx(ctx, func(tx Tx) error {\n\trow := tx.GetForUpdate(id)\n\trow.Count++\n\treturn tx.Update(row)\n})\n// or use a single conditional update"},
	"data.missing-transaction-boundary":       {Kind: guided, Text: "Group related writes in one transaction.\n\nBefore:\nrepo.CreateOrder(order)\nrepo.CreateLineItems(items)\n\nAfter:\nrepo.InTx(ctx, func(tx Tx) error {\n\tif err := tx.CreateOrder(order); err != nil { return err }\n\treturn tx.CreateLineItems(items)\n})"},
	"data.side-effect-in-transaction":         {Kind: guided, Text: "Move external side effects out of rollback-capable transaction bodies.\n\nBefore:\ntx.Do(func() error { save(); return email.Send() })\n\nAfter:\ntx.Do(func() error { save(); return outbox.Insert(emailEvent) })\n// send asynchronously after commit"},
	"data.non-idempotent-consumer":            {Kind: guided, Text: "Guard message handlers with a stable idempotency or deduplication key.\n\nBefore:\nfunc Handle(msg Message) error { return charge(msg.Payment) }\n\nAfter:\nfunc Handle(msg Message) error {\n\tif seen(msg.ID) { return nil }\n\treturn recordAndCharge(msg.ID, msg.Payment)\n}"},
	"data.missing-deduplication":              {Kind: guided, Text: "Record processed message/event IDs before side effects.\n\nBefore:\nprocess(event)\n\nAfter:\nif dedupe.AlreadyProcessed(event.ID) { return nil }\nreturn dedupe.ProcessOnce(event.ID, func() error { return process(event) })"},
	"data.unsafe-dual-write":                  {Kind: guided, Text: "Replace independent writes to multiple systems with an explicit consistency strategy.\n\nBefore:\ndb.Save(order)\npublisher.Publish(orderCreated)\n\nAfter:\ntx.Save(order)\ntx.InsertOutbox(orderCreated)\n// relay publishes from the outbox with retry/reconciliation"},
	"data.missing-outbox-strategy":            {Kind: guided, Text: "Persist events in an outbox inside the same transaction as the state change.\n\nBefore:\nrepo.Save(entity)\nevents.Publish(EntitySaved{ID: entity.ID})\n\nAfter:\nrepo.InTx(ctx, func(tx Tx) error {\n\ttx.Save(entity)\n\treturn tx.OutboxInsert(EntitySaved{ID: entity.ID})\n})"},
	"data.unstable-pagination":                {Kind: deterministic, Text: "Make paginated reads deterministic.\n\nBefore:\nSELECT * FROM orders LIMIT 50 OFFSET 100\n\nAfter:\nSELECT * FROM orders WHERE id > $cursor ORDER BY id ASC LIMIT 50"},
	"data.unbounded-read":                     {Kind: deterministic, Text: "Bound database reads with a limit, cursor, stream, or selective predicate.\n\nBefore:\nSELECT * FROM events\n\nAfter:\nSELECT * FROM events WHERE created_at >= $since ORDER BY created_at LIMIT 1000"},
	"data.exactly-once-assumption":            {Kind: guided, Text: "Design consumers for at-least-once delivery.\n\nBefore:\n// broker delivers exactly once, so no dedupe needed\n\nAfter:\n// delivery is treated as at-least-once; event_id is recorded before side effects"},
	"data.cache-without-policy":               {Kind: guided, Text: "Give caches explicit freshness and ownership rules.\n\nBefore:\ncache.Set(key, value)\n\nAfter:\ncache.Set(key, value, cache.WithTTL(5*time.Minute))\n// document who invalidates the key and what stale reads mean"},
	"contracts.non-expand-contract-migration": {Kind: guided, Text: "Split rolling schema changes into expand, migrate, and contract phases.\n\nBefore:\nALTER TABLE users DROP COLUMN legacy_email;\n\nAfter:\n-- release 1: add new_email and dual-write\n-- release 2: backfill and switch reads\n-- release 3: drop legacy_email after verification"},
}
