package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

// performanceCatalog covers the performance section. These rules previously
// lived in the quality section under quality.* ids (see
// retiredPerformanceRuleIDs for the mapping).
var performanceCatalog = map[string]core.RuleMetadata{
	"performance.n-plus-one-query": {
		ID:             "performance.n-plus-one-query",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "N+1 query in loop",
		Description: "Warns when a database query or remote fetch call runs inside a loop body, suggesting an N+1 access pattern.",
		HowToFix:    "Batch the lookups into one query, prefetch the data before the loop, or use a bulk API.",
	},
	"performance.go.alloc-in-loop": {
		ID:             "performance.go.alloc-in-loop",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Allocation-heavy loop",
		Description:    "Warns when a loop grows a string by concatenation or accumulates fmt.Sprintf output (performance_rules.detect_alloc_in_loop, on by default). When performance_rules.detect_prealloc_in_loop is enabled (off by default), also warns when a loop appends to a slice without preallocated capacity despite a knowable bound.",
		HowToFix:       "Use strings.Builder for string accumulation and preallocate slice capacity with make(len 0, cap n) before the loop.",
	},
	"performance.rust.alloc-in-loop": {
		ID:               "performance.rust.alloc-in-loop",
		Section:          "Performance",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(core.RuleLanguageRust),
		Title:            "Rust string growth in loop",
		Description:      "Warns when a Rust loop repeatedly grows a String initialized without visible preallocation via +=, x = x + ..., or push_str (performance_rules.detect_alloc_in_loop).",
		HowToFix:         "Collect the parts and join once, or initialize the String with String::with_capacity before the loop.",
	},
	"performance.sync-io-in-request-path": {
		ID:             "performance.sync-io-in-request-path",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Synchronous I/O in request path",
		Description:    "Warns when a likely Go HTTP handler performs synchronous file I/O directly in the request path.",
		HowToFix:       "Move the I/O out of the request path, preload or cache the data, or switch to an architecture that avoids per-request filesystem access.",
	},
	"performance.unbounded-goroutines-in-loop": {
		ID:             "performance.unbounded-goroutines-in-loop",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Goroutines launched from loops",
		Description:    "Warns when Go code launches goroutines from inside loops without any visible bounding mechanism.",
		HowToFix:       "Use a worker pool, semaphore, errgroup limit, or explicit queue so loop-driven concurrency stays bounded.",
	},
	"performance.typescript.sync-io-in-handler": {
		ID:             "performance.typescript.sync-io-in-handler",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript sync I/O in handler",
		Description:    "Warns when a synchronous *Sync call runs inside an HTTP request handler, blocking the event loop.",
		HowToFix:       "Switch to the promise-based API (fs.promises, async exec) inside request handlers.",
	},
	"performance.javascript.sync-io-in-handler": {
		ID:             "performance.javascript.sync-io-in-handler",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "JavaScript sync I/O in handler",
		Description:    "Warns when a synchronous *Sync call runs inside an HTTP request handler, blocking the event loop.",
		HowToFix:       "Switch to the promise-based API (fs.promises, async exec) inside request handlers.",
	},
	"performance.typescript.unbounded-concurrency": {
		ID:             "performance.typescript.unbounded-concurrency",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript unbounded concurrency",
		Description:    "Warns when promises are created inside a loop without batching or a concurrency limiter.",
		HowToFix:       "Process the work in chunks with Promise.all or wrap calls with a limiter such as p-limit.",
	},
	"performance.javascript.unbounded-concurrency": {
		ID:             "performance.javascript.unbounded-concurrency",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "JavaScript unbounded concurrency",
		Description:    "Warns when promises are created inside a loop without batching or a concurrency limiter.",
		HowToFix:       "Process the work in chunks with Promise.all or wrap calls with a limiter such as p-limit.",
	},
	"performance.python.sync-io-in-async": {
		ID:             "performance.python.sync-io-in-async",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python blocking call in async function",
		Description:    "Warns when requests, urllib, or time.sleep calls run inside an async def body, blocking the event loop.",
		HowToFix:       "Use an async HTTP client (httpx.AsyncClient, aiohttp) and asyncio.sleep inside async functions.",
	},
	"performance.regex-compile-in-loop": {
		ID:             "performance.regex-compile-in-loop",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
			core.RuleLanguageRust,
		),
		Title:       "Regex compiled in loop",
		Description: "Warns when a regular expression is compiled inside a loop body (regexp.Compile/MustCompile, re.compile, new RegExp), repeating the compilation cost every iteration (performance_rules.detect_regex_compile_in_loop).",
		HowToFix:    "Compile the pattern once before the loop or at package/module level and reuse it.",
	},
	"performance.go.defer-in-loop": {
		ID:             "performance.go.defer-in-loop",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Defer inside loop",
		Description:    "Warns when a defer statement sits inside a loop body: deferred calls run only at function exit, so resources accumulate for every iteration (performance_rules.detect_defer_in_loop).",
		HowToFix:       "Release the resource explicitly at the end of the iteration, or extract the loop body into a function so the defer runs per iteration.",
	},
	"performance.go.sleep-in-loop": {
		ID:             "performance.go.sleep-in-loop",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Sleep inside loop",
		Description:    "Warns when time.Sleep runs inside a loop body, which usually marks a poll that burns latency (performance_rules.detect_sleep_in_loop).",
		HowToFix:       "Replace the poll with a time.Ticker, a channel or sync.Cond signal, or an exponential-backoff helper.",
	},
	"performance.rust.sleep-in-loop": {
		ID:               "performance.rust.sleep-in-loop",
		Section:          "Performance",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(core.RuleLanguageRust),
		Title:            "Rust sleep inside loop",
		Description:      "Warns when std::thread::sleep or thread::sleep runs inside a Rust loop body, which usually marks a poll that wants a signal, timer primitive, or bounded backoff helper (performance_rules.detect_sleep_in_loop).",
		HowToFix:         "Replace the polling sleep with a channel/Condvar signal, a timer primitive, or a bounded backoff helper.",
	},
	"performance.go.timer-leak-in-loop": {
		ID:             "performance.go.timer-leak-in-loop",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Timer leaked in loop",
		Description:    "Warns when time.After is called inside a loop: each call allocates a timer that is not garbage-collected until it fires, so tight loops leak timers (performance_rules.detect_timer_leaks).",
		HowToFix:       "Create one time.NewTimer or time.NewTicker before the loop and reuse it (Reset per iteration), stopping it when done.",
	},
	"performance.unbounded-read": {
		ID:             "performance.unbounded-read",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
		),
		Title:       "Unbounded read into memory",
		Description: "Warns when an entire input is read into memory without a size bound: io.ReadAll in Go HTTP handlers or loops, and .read()/.readlines() with no size argument in Python loops. One oversized input then costs the whole payload in memory (performance_rules.detect_unbounded_reads).",
		HowToFix:    "Bound the read (io.LimitReader, read(n)) or process the input as a stream instead of materializing it.",
	},
	"performance.string-concat-in-loop": {
		ID:             "performance.string-concat-in-loop",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
		),
		Title:       "String concatenation in loop",
		Description: "Warns when a string grows by += inside a loop in Python or TypeScript/JavaScript, copying the accumulated value every iteration (performance_rules.detect_alloc_in_loop; the Go equivalent is performance.go.alloc-in-loop).",
		HowToFix:    "Collect the parts in a list/array and join them once after the loop.",
	},
	"performance.python.unbounded-concurrency": {
		ID:             "performance.python.unbounded-concurrency",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python unbounded concurrency",
		Description:    "Warns when asyncio.create_task or asyncio.ensure_future runs inside a loop with no visible concurrency limit (Semaphore, TaskGroup, or a limiter library) in the file (performance_rules.detect_unbounded_concurrency).",
		HowToFix:       "Bound the fan-out with an asyncio.Semaphore, an asyncio.TaskGroup, or a limiter such as aiolimiter.",
	},
	"performance.typescript.await-in-loop": {
		ID:             "performance.typescript.await-in-loop",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript await in loop",
		Description:    "Warns when await runs inside a loop body, serializing work that could run concurrently; for await streams are exempt (performance_rules.detect_await_in_loop).",
		HowToFix:       "Collect the promises and await Promise.all (chunked or via a limiter) when the iterations are independent.",
	},
	"performance.javascript.await-in-loop": {
		ID:             "performance.javascript.await-in-loop",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "JavaScript await in loop",
		Description:    "Warns when await runs inside a loop body, serializing work that could run concurrently; for await streams are exempt (performance_rules.detect_await_in_loop).",
		HowToFix:       "Collect the promises and await Promise.all (chunked or via a limiter) when the iterations are independent.",
	},
	"performance.typescript.timer-listener-leak": {
		ID:             "performance.typescript.timer-listener-leak",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript leaked timer or listener",
		Description:    "Warns when setInterval has no matching clearInterval anywhere in the file, or addEventListener runs inside a loop with no removeEventListener/AbortSignal in the file — both keep callbacks and their captures alive indefinitely (performance_rules.detect_timer_leaks).",
		HowToFix:       "Store the interval handle and clearInterval it on teardown; deregister listeners with removeEventListener or pass an AbortSignal.",
	},
	"performance.javascript.timer-listener-leak": {
		ID:             "performance.javascript.timer-listener-leak",
		Section:        "Performance",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "JavaScript leaked timer or listener",
		Description:    "Warns when setInterval has no matching clearInterval anywhere in the file, or addEventListener runs inside a loop with no removeEventListener/AbortSignal in the file — both keep callbacks and their captures alive indefinitely (performance_rules.detect_timer_leaks).",
		HowToFix:       "Store the interval handle and clearInterval it on teardown; deregister listeners with removeEventListener or pass an AbortSignal.",
	},
}

// RetiredPerformanceRuleIDs maps the retired quality.* ids of the performance
// rules to their performance.* replacements. The scan never consults this —
// there is deliberately no runtime aliasing — but `codeguard doctor` uses it
// to flag stale waivers and configs after the migration.
func RetiredPerformanceRuleIDs() map[string]string {
	return map[string]string{
		"quality.n-plus-one-query":                 "performance.n-plus-one-query",
		"quality.go.alloc-in-loop":                 "performance.go.alloc-in-loop",
		"quality.sync-io-in-request-path":          "performance.sync-io-in-request-path",
		"quality.unbounded-goroutines-in-loop":     "performance.unbounded-goroutines-in-loop",
		"quality.typescript.sync-io-in-handler":    "performance.typescript.sync-io-in-handler",
		"quality.javascript.sync-io-in-handler":    "performance.javascript.sync-io-in-handler",
		"quality.typescript.unbounded-concurrency": "performance.typescript.unbounded-concurrency",
		"quality.javascript.unbounded-concurrency": "performance.javascript.unbounded-concurrency",
		"quality.python.sync-io-in-async":          "performance.python.sync-io-in-async",
	}
}
