package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var designGraphCatalog = map[string]core.RuleMetadata{
	"design.layer-boundary": {
		ID: "design.layer-boundary", Section: "Design Patterns", DefaultLevel: "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic, LanguageCoverage: designGraphLanguageCoverage(),
		Title: "Layer dependency boundary", Description: "Fails when a module imports a denied architectural layer or an external dependency denied to its layer.",
		HowToFix: "Invert the dependency, move the implementation to an allowed layer, or route access through an allowed contract.",
	},
	"design.unassigned-module": {
		ID: "design.unassigned-module", Section: "Design Patterns", DefaultLevel: "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic, LanguageCoverage: designGraphLanguageCoverage(),
		Title: "Unassigned architecture module", Description: "Fails when boundary assignment is required and a module is outside every configured layer or domain.",
		HowToFix: "Add the module path to the appropriate configured layer and domain.",
	},
	"design.domain-boundary": {
		ID: "design.domain-boundary", Section: "Design Patterns", DefaultLevel: "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic, LanguageCoverage: designGraphLanguageCoverage(),
		Title: "Domain dependency boundary", Description: "Fails when a cross-domain import is not permitted or bypasses the target domain's public paths.",
		HowToFix: "Use a public contract exposed by an allowed domain, or remove the cross-domain dependency.",
	},
	"design.data-ownership": {
		ID: "design.data-ownership", Section: "Design Patterns", DefaultLevel: "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic, LanguageCoverage: designGraphLanguageCoverage(),
		Title: "Domain data ownership", Description: "Fails when one domain directly imports another domain's data or persistence modules.",
		HowToFix: "Access the data through the owning domain's public API, contract, or event.",
	},
	"design.capability-boundary": {
		ID: "design.capability-boundary", Section: "Design Patterns", DefaultLevel: "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic, LanguageCoverage: designGraphLanguageCoverage(),
		Title: "Technical capability boundary", Description: "Fails when a source module imports a sensitive technical capability outside its approved paths.",
		HowToFix: "Move the import and its implementation into an allowed adapter and expose a narrow contract to callers.",
	},
	"design.private-module-import": {
		ID:               "design.private-module-import",
		Section:          "Design Patterns",
		DefaultLevel:     "fail",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: designGraphLanguageCoverage(),
		Title:            "Private module import",
		Description:      "Fails when code outside a configured public surface imports one of its implementation modules instead of an approved entrypoint.",
		HowToFix:         "Import the component's public entrypoint, or deliberately add the target module to the surface's configured entrypoints.",
	},
	"design.production-imports-test": {
		ID:               "design.production-imports-test",
		Section:          "Design Patterns",
		DefaultLevel:     "fail",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: designGraphLanguageCoverage(),
		Title:            "Production imports test code",
		Description:      "Fails when a configured production module imports a test, mock, fixture, or other test-only module.",
		HowToFix:         "Move the shared behavior into a production module, then make both production and test code import that module.",
	},
	"design.typescript.import-cycle": {
		ID:             "design.typescript.import-cycle",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript import cycle",
		Description:    "Fails when TypeScript modules form an internal import cycle.",
		HowToFix:       "Break the cycle by extracting shared behavior into a lower-level module or by inverting the dependency direction.",
	},
	"design.javascript.import-cycle": {
		ID:             "design.javascript.import-cycle",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "JavaScript import cycle",
		Description:    "Fails when JavaScript modules form an internal import cycle.",
		HowToFix:       "Break the cycle by extracting shared behavior into a lower-level module or by inverting the dependency direction.",
	},
	"design.rust.import-cycle": {
		ID:             "design.rust.import-cycle",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Rust module cycle",
		Description:    "Fails when Rust modules form an internal use/mod dependency cycle.",
		HowToFix:       "Break the cycle by moving shared items into a lower-level module or by inverting the dependency direction.",
	},
	"design.java.import-cycle": {
		ID:             "design.java.import-cycle",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Java import cycle",
		Description:    "Fails when Java classes form an internal import cycle.",
		HowToFix:       "Break the cycle by introducing an interface or moving shared types into a lower-level package.",
	},
	"design.cpp.import-cycle": {
		ID:               "design.cpp.import-cycle",
		Section:          "Design Patterns",
		DefaultLevel:     "fail",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(core.RuleLanguageCPP),
		Title:            "C++ include or module cycle",
		Description:      "Fails when target-local C++ headers, source files, or named modules form a dependency cycle.",
		HowToFix:         "Break the cycle by moving shared declarations into a lower-level header/module or depending on an abstract interface.",
	},
	"design.god-module": {
		ID:             "design.god-module",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
			core.RuleLanguageRust,
			core.RuleLanguageJava,
			core.RuleLanguageCPP,
		),
		Title:       "God module",
		Description: "Warns when a module's combined fan-in and fan-out exceeds the configured threshold, indicating it concentrates too much of the dependency graph.",
		HowToFix:    "Split the module into smaller focused modules and route consumers through narrower interfaces.",
	},
	"design.high-impact-change": {
		ID:             "design.high-impact-change",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(
			core.RuleLanguageGo,
			core.RuleLanguagePython,
			core.RuleLanguageTypeScript,
			core.RuleLanguageJavaScript,
			core.RuleLanguageRust,
			core.RuleLanguageJava,
			core.RuleLanguageCPP,
		),
		Title:       "High impact change",
		Description: "Warns in diff mode when a changed module has more transitive dependents than the configured threshold.",
		HowToFix:    "Split the change into smaller steps, add coverage for dependent modules, or stage the rollout carefully.",
	},
}
