package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var catalog = map[string]core.RuleMetadata{
	"quality.gofmt": {
		ID:           "quality.gofmt",
		Section:      "Code Quality",
		DefaultLevel: "fail",
		Title:        "Go formatting",
		Description:  "Fails when a Go source file is not gofmt-clean.",
		HowToFix:     "Run gofmt on the file and commit the formatted result.",
	},
	"quality.parse-error": {
		ID:           "quality.parse-error",
		Section:      "Code Quality",
		DefaultLevel: "fail",
		Title:        "Go parseability",
		Description:  "Fails when a Go source file cannot be parsed.",
		HowToFix:     "Fix the syntax error so the file parses cleanly.",
	},
	"quality.max-file-lines": {
		ID:           "quality.max-file-lines",
		Section:      "Code Quality",
		DefaultLevel: "warn",
		Title:        "File length",
		Description:  "Warns when a file exceeds the configured maximum line count.",
		HowToFix:     "Split the file into smaller units or raise the configured threshold intentionally.",
	},
	"quality.max-function-lines": {
		ID:           "quality.max-function-lines",
		Section:      "Code Quality",
		DefaultLevel: "warn",
		Title:        "Function length",
		Description:  "Warns when a function exceeds the configured maximum line count.",
		HowToFix:     "Break the function into smaller helpers or raise the threshold intentionally.",
	},
	"quality.max-parameters": {
		ID:           "quality.max-parameters",
		Section:      "Code Quality",
		DefaultLevel: "warn",
		Title:        "Function parameters",
		Description:  "Warns when a function exceeds the configured parameter count.",
		HowToFix:     "Group related inputs into a struct or simplify the function signature.",
	},
	"quality.cyclomatic-complexity": {
		ID:           "quality.cyclomatic-complexity",
		Section:      "Code Quality",
		DefaultLevel: "warn",
		Title:        "Cyclomatic complexity",
		Description:  "Warns when a function exceeds the configured cyclomatic complexity threshold.",
		HowToFix:     "Reduce branching in the function or refactor logic into smaller units.",
	},
	"quality.dependency-direction": {
		ID:           "quality.dependency-direction",
		Section:      "Code Quality",
		DefaultLevel: "warn",
		Title:        "Dependency direction",
		Description:  "Warns when non-CLI packages import CLI-only implementation details.",
		HowToFix:     "Move shared logic into reusable packages and keep internal or CLI details out of library code.",
	},
	"design.cmd-through-internal-cli": {
		ID:           "design.cmd-through-internal-cli",
		Section:      "Design Patterns",
		DefaultLevel: "fail",
		Title:        "Command layer routing",
		Description:  "Fails when cmd entrypoints import reusable service packages directly instead of going through internal/cli.",
		HowToFix:     "Route command execution through internal/cli and keep cmd thin.",
	},
	"design.service-import-internal": {
		ID:           "design.service-import-internal",
		Section:      "Design Patterns",
		DefaultLevel: "fail",
		Title:        "Service to internal import",
		Description:  "Fails when reusable service code imports internal packages.",
		HowToFix:     "Move the dependency behind a public boundary or relocate the service code.",
	},
	"design.service-import-cmd": {
		ID:           "design.service-import-cmd",
		Section:      "Design Patterns",
		DefaultLevel: "fail",
		Title:        "Service to cmd import",
		Description:  "Fails when reusable service code imports cmd packages.",
		HowToFix:     "Move shared behavior into a reusable package and keep cmd packages as entrypoints only.",
	},
	"design.generic-package-name": {
		ID:           "design.generic-package-name",
		Section:      "Design Patterns",
		DefaultLevel: "warn",
		Title:        "Generic package name",
		Description:  "Warns when a package name is too generic to communicate ownership or responsibility.",
		HowToFix:     "Rename the package to something specific to its responsibility.",
	},
	"design.max-methods-per-type": {
		ID:           "design.max-methods-per-type",
		Section:      "Design Patterns",
		DefaultLevel: "warn",
		Title:        "Methods per type",
		Description:  "Warns when a type accumulates too many methods.",
		HowToFix:     "Split responsibilities across smaller types or interfaces.",
	},
	"design.max-interface-methods": {
		ID:           "design.max-interface-methods",
		Section:      "Design Patterns",
		DefaultLevel: "warn",
		Title:        "Interface size",
		Description:  "Warns when an interface is too large.",
		HowToFix:     "Break the interface into smaller focused contracts.",
	},
	"design.max-decls-per-file": {
		ID:           "design.max-decls-per-file",
		Section:      "Design Patterns",
		DefaultLevel: "warn",
		Title:        "Declarations per file",
		Description:  "Warns when a file accumulates too many top-level declarations.",
		HowToFix:     "Move related declarations into smaller files with clearer ownership.",
	},
	"security.hardcoded-secret": {
		ID:           "security.hardcoded-secret",
		Section:      "Security",
		DefaultLevel: "fail",
		Title:        "Hardcoded secret",
		Description:  "Fails when a likely hardcoded secret is detected in source text.",
		HowToFix:     "Remove the secret from the repository and load it from a secret manager or environment at runtime.",
	},
	"security.private-key": {
		ID:           "security.private-key",
		Section:      "Security",
		DefaultLevel: "fail",
		Title:        "Private key material",
		Description:  "Fails when PEM private key material is detected.",
		HowToFix:     "Delete the committed key, rotate the credential, and load key material from secure storage.",
	},
	"security.insecure-tls": {
		ID:           "security.insecure-tls",
		Section:      "Security",
		DefaultLevel: "fail",
		Title:        "Insecure TLS",
		Description:  "Fails when insecure TLS verification is explicitly disabled.",
		HowToFix:     "Enable certificate verification and use trusted certificates in non-local environments.",
	},
	"security.shell-execution": {
		ID:           "security.shell-execution",
		Section:      "Security",
		DefaultLevel: "warn",
		Title:        "Shell execution review",
		Description:  "Warns when shell execution primitives are used and should receive manual review.",
		HowToFix:     "Prefer direct library calls, or tightly validate and constrain command execution.",
	},
	"security.govulncheck": {
		ID:           "security.govulncheck",
		Section:      "Security",
		DefaultLevel: "fail",
		Title:        "Govulncheck finding",
		Description:  "Surfaces vulnerabilities or integration failures from govulncheck.",
		HowToFix:     "Install govulncheck, then upgrade or replace the affected dependency and re-run the scan.",
	},
	"prompts.secret-interpolation": {
		ID:           "prompts.secret-interpolation",
		Section:      "AI Prompts",
		DefaultLevel: "fail",
		Title:        "Prompt secret interpolation",
		Description:  "Fails when prompt assets interpolate likely secret values.",
		HowToFix:     "Remove secret placeholders from prompt assets and inject secrets outside the prompt text.",
	},
	"prompts.unsafe-instructions": {
		ID:           "prompts.unsafe-instructions",
		Section:      "AI Prompts",
		DefaultLevel: "warn",
		Title:        "Unsafe prompt instructions",
		Description:  "Warns when prompt assets contain instruction-injection or system prompt exfiltration patterns.",
		HowToFix:     "Rewrite the prompt to remove instruction override or prompt exfiltration language.",
	},
	"ci.required-workflow-dir": {
		ID:           "ci.required-workflow-dir",
		Section:      "CI/CD",
		DefaultLevel: "fail",
		Title:        "Workflow directory",
		Description:  "Fails when the configured workflow directory is required but missing.",
		HowToFix:     "Add the required workflow directory or disable the policy explicitly.",
	},
	"ci.required-file": {
		ID:           "ci.required-file",
		Section:      "CI/CD",
		DefaultLevel: "fail",
		Title:        "Required CI file",
		Description:  "Fails when required workflow, release, or automation files are missing.",
		HowToFix:     "Add the required file or remove the policy requirement if it does not apply.",
	},
	"ci.workflow-content": {
		ID:           "ci.workflow-content",
		Section:      "CI/CD",
		DefaultLevel: "fail",
		Title:        "Workflow content",
		Description:  "Fails when required workflow file markers are absent.",
		HowToFix:     "Update the workflow file so the required steps or markers are present.",
	},
}

func Catalog() map[string]core.RuleMetadata {
	return catalog
}
