package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var changeSafetyFixTemplates = map[string]core.FixTemplate{
	"naming.generic-identifier":             {Kind: guided, Text: "Replace placeholder names with domain vocabulary.\n\nBefore:\nfunc process(foo User) { tmp := foo.Email }\n\nAfter:\nfunc process(account User) { normalizedEmail := account.Email }"},
	"function.excessive-parameters":         {Kind: guided, Text: "Group related parameters or split the function.\n\nBefore:\nfunc CreateUser(name, email, country, plan, source string, admin bool) error\n\nAfter:\ntype CreateUserRequest struct { Name, Email, Country, Plan, Source string; Admin bool }\nfunc CreateUser(req CreateUserRequest) error"},
	"function.mixed-abstraction-level":      {Kind: guided, Text: "Keep each function at one abstraction level.\n\nBefore:\nfunc Checkout(order Order) { validate(order); db.Query(...); http.Post(...) }\n\nAfter:\nfunc Checkout(order Order) { validate(order); persistOrder(order); publishCheckout(order) }"},
	"function.command-query-mix":            {Kind: guided, Text: "Separate value queries from state-changing commands.\n\nBefore:\nfunc GetUser(id string) (User, error) { repo.SaveAudit(id); return repo.Find(id) }\n\nAfter:\nfunc GetUser(id string) (User, error) { return repo.Find(id) }\nfunc RecordUserLookup(id string) error { return repo.SaveAudit(id) }"},
	"error.logged-and-ignored":              {Kind: guided, Text: "Do not only log an error and continue as success.\n\nBefore:\nif err != nil { log.Printf(\"load: %v\", err); return nil }\n\nAfter:\nif err != nil { return fmt.Errorf(\"load profile: %w\", err) }"},
	"error.context-lost":                    {Kind: guided, Text: "Preserve the original error while adding operation context.\n\nBefore:\nif err != nil { return err }\n\nAfter:\nif err != nil { return fmt.Errorf(\"load profile: %w\", err) }"},
	"defensive.unchecked-type-assertion":    {Kind: guided, Text: "Use checked assertions or validation before consuming dynamic values.\n\nBefore:\nuser := value.(User)\n\nAfter:\nuser, ok := value.(User)\nif !ok { return fmt.Errorf(\"expected User\") }"},
	"defensive.unsafe-numeric-conversion":   {Kind: guided, Text: "Validate numeric bounds before narrowing or changing sign.\n\nBefore:\ncount32 := int32(count)\n\nAfter:\nif count > math.MaxInt32 { return fmt.Errorf(\"count too large\") }\ncount32 := int32(count)"},
	"maintainability.public-surface-growth": {Kind: guided, Text: "Keep exported surface area intentional.\n\nBefore:\n// change exports helper only used internally\nexport function normalizeForInternalUse(...) { ... }\n\nAfter:\nfunction normalizeForInternalUse(...) { ... }\n// export only stable APIs with tests and docs"},
	"maintainability.dependency-growth":     {Kind: guided, Text: "Avoid unnecessary direct dependencies in changed files.\n\nBefore:\n// file imports a new SDK only for one small formatting branch\n\nAfter:\n// remove the dependency, pass the behavior in, or isolate the integration behind a small adapter"},

	"testing.behavior-change-without-test":  {Kind: guided, Text: "Add tests in the same diff for observable behavior changes.\n\nBefore:\n// production logic changed, no test files changed\n\nAfter:\n// production logic changed\n// matching unit, integration, or contract test asserts the new behavior"},
	"testing.failure-path-missing":          {Kind: guided, Text: "Exercise the new failure path explicitly.\n\nBefore:\nif err := client.Call(ctx); err != nil { return fallback }\n// only success-path tests exist\n\nAfter:\nif err := client.Call(ctx); err != nil { return fallback }\n// test injects client failure and asserts fallback/error behavior"},
	"testing.hardwired-dependency":          {Kind: guided, Text: "Inject dependencies that need deterministic tests.\n\nBefore:\nfunc Price(order Order) Money { return fetchRate(http.DefaultClient, order) }\n\nAfter:\ntype RateClient interface { Rate(context.Context, Order) (Money, error) }\nfunc Price(ctx context.Context, client RateClient, order Order) (Money, error) { return client.Rate(ctx, order) }"},
	"testing.nondeterministic-domain-logic": {Kind: guided, Text: "Move nondeterministic reads to a boundary and pass values into domain logic.\n\nBefore:\nfunc Expired(token Token) bool { return time.Now().After(token.ExpiresAt) }\n\nAfter:\nfunc Expired(now time.Time, token Token) bool { return now.After(token.ExpiresAt) }"},
	"testing.legacy-hotspot-uncovered":      {Kind: guided, Text: "Characterize existing hotspot behavior before changing it.\n\nBefore:\n// high-churn legacy parser changed directly\n\nAfter:\n// characterization tests pin current parser behavior, then production code changes"},

	"change.mixed-concerns":              {Kind: guided, Text: "Split unrelated work or make the coupling explicit.\n\nBefore:\n// PR changes billing, auth middleware, dependency upgrades, and CSS\n\nAfter:\n// PR 1: billing behavior + tests\n// PR 2: auth middleware + tests\n// PR 3: dependency upgrades"},
	"change.oversized-diff":              {Kind: guided, Text: "Reduce review risk by shrinking the diff or adding focused verification notes.\n\nBefore:\n// 60 files, 14 directories, public APIs changed, few tests\n\nAfter:\n// mechanical move PR first, behavior PR second, targeted tests and review map included"},
	"change.mixed-refactor-and-behavior": {Kind: guided, Text: "Separate behavior-preserving refactors from behavior changes.\n\nBefore:\n// rename service, move files, and change validation result in one PR\n\nAfter:\n// PR 1: rename/move only with unchanged tests\n// PR 2: validation behavior change with tests"},
	"change.too-many-concerns":           {Kind: guided, Text: "Split the PR around one reviewable concern.\n\nBefore:\n// storage migration, API behavior, UI copy, and cleanup together\n\nAfter:\n// one PR per storage/API/UI/cleanup concern or a documented atomic rollout plan"},
	"change.unnecessary-surface-area":    {Kind: guided, Text: "Limit edits to the smallest surface that implements the behavior.\n\nBefore:\n// feature changes interfaces across unrelated packages\n\nAfter:\n// feature changes one boundary and leaves unrelated packages untouched"},
	"change.one-use-abstraction":         {Kind: guided, Text: "Avoid abstractions that do not simplify or isolate policy.\n\nBefore:\ntype UserGetter interface { GetUser(id string) User }\n// one implementation, one caller, pass-through method\n\nAfter:\n// call concrete collaborator directly until another meaningful consumer appears"},
	"change.duplicate-helper":            {Kind: guided, Text: "Reuse the existing project helper or consolidate the duplicate.\n\nBefore:\nfunc normalizeEmailAddress(v string) string { ... }\n// existing canonicalizeEmail already exists\n\nAfter:\nfunc normalizeEmailAddress(v string) string { return canonicalizeEmail(v) }\n// or replace callers with the established helper"},
	"change.cleanup-regression":          {Kind: guided, Text: "Make cleanup diffs improve measured maintainability.\n\nBefore:\n// cleanup PR adds branches, wrappers, and duplicate paths\n\nAfter:\n// cleanup PR reduces complexity/duplication or documents why the temporary regression is needed"},
	"change.complexity-increased":        {Kind: guided, Text: "Reduce newly added complexity before merging.\n\nBefore:\nif a { if b { if c { ... } } }\n\nAfter:\nif !validRequest(req) { return err }\nreturn processValidRequest(req)"},
	"change.move-without-verification":   {Kind: guided, Text: "Preserve behavior evidence when moving code.\n\nBefore:\n// files moved, tests deleted or not run\n\nAfter:\n// tests moved with the code and narrow verification command is documented/run"},

	"refactor.behavior-change-detected":             {Kind: guided, Text: "Keep refactor-only diffs behavior-preserving.\n\nBefore:\n// PR labeled refactor removes an authorization branch\n\nAfter:\n// refactor PR preserves authorization; behavior change moves to a separate tested PR"},
	"refactor.public-contract-changed":              {Kind: guided, Text: "Avoid public contract changes in refactor-only work.\n\nBefore:\nfunc GetUser(id string) User\n// changed to return (*User, error) in refactor PR\n\nAfter:\n// refactor keeps signature stable or ships a separate compatibility-tested contract PR"},
	"refactor.test-coverage-reduced":                {Kind: guided, Text: "Move tests with refactored behavior instead of weakening coverage.\n\nBefore:\n// old package tests deleted after extraction\n\nAfter:\n// extracted package has equivalent tests and old integration coverage still passes"},
	"refactor.error-path-changed":                   {Kind: guided, Text: "Preserve error behavior during refactors.\n\nBefore:\nif err != nil { return nil }\n// refactor changed returned error to silent success\n\nAfter:\nif err != nil { return fmt.Errorf(\"load profile: %w\", err) }"},
	"refactor.side-effect-order-changed":            {Kind: guided, Text: "Keep side-effect order stable unless the PR is a tested behavior change.\n\nBefore:\nwriteDB(); publishEvent(); checkAuthorization()\n\nAfter:\ncheckAuthorization(); writeDB(); publishEvent()\n// with tests and rollout notes if ordering intentionally changed"},
	"refactor.visibility-expanded":                  {Kind: guided, Text: "Keep symbols private unless a real external consumer exists.\n\nBefore:\nfunc computePrice(...) Money\n// changed to exported ComputePrice during refactor\n\nAfter:\nfunc computePrice(...) Money\n// or export only with documented cross-package consumer"},
	"refactor.dependency-direction-worsened":        {Kind: guided, Text: "Preserve architectural dependency direction while refactoring.\n\nBefore:\n// domain package imports http/sql/framework package after extraction\n\nAfter:\n// domain owns an interface; infrastructure implements it outward"},
	"refactor.duplicate-implementation-left-behind": {Kind: guided, Text: "Remove or delegate old implementations after extraction.\n\nBefore:\nfunc calculateTotalV1(...) Money { ... }\nfunc calculateTotal(...) Money { ...same behavior... }\n\nAfter:\nfunc calculateTotal(...) Money { ... }\n// old callers migrated or old path delegates to the new implementation temporarily"},
	"refactor.dead-path-left-behind":                {Kind: guided, Text: "Delete obsolete paths or attach an owner and expiry.\n\nBefore:\nif oldFlowEnabled { oldFlow() } else { newFlow() }\n// oldFlow has no callers or rollout plan\n\nAfter:\nnewFlow()\n// or TODO(owner, date): remove oldFlow after migration metric reaches zero"},
}
