package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var designCatalog = map[string]core.RuleMetadata{
	"design.command-check": {
		ID:             "design.command-check",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		Title:          "Language design command",
		Description:    "Fails when a configured language-specific design command exits non-zero.",
		HowToFix:       "Fix the reported issue from the command output or adjust the configured command if it does not fit the target.",
	},
	"design.diff-command-check": {
		ID:             "design.diff-command-check",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		Title:          "Contract diff command",
		Description:    "Fails in diff mode when a configured language-specific contract check reports breaking drift between the base ref and the current target.",
		HowToFix:       "Restore compatibility or update the diff command and target contract if the change is intended.",
	},
	"design.cmd-through-internal-cli": {
		ID:             "design.cmd-through-internal-cli",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Command layer routing",
		Description:    "Fails when cmd entrypoints import reusable service packages directly instead of going through internal/cli.",
		HowToFix:       "Route command execution through internal/cli and keep cmd thin.",
	},
	"design.service-import-internal": {
		ID:             "design.service-import-internal",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Service to internal import",
		Description:    "Fails when reusable public packages, other than the SDK facade, import internal packages.",
		HowToFix:       "Move the dependency behind a public boundary or relocate the service code.",
	},
	"design.service-import-cmd": {
		ID:             "design.service-import-cmd",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Service to cmd import",
		Description:    "Fails when reusable service code imports cmd packages.",
		HowToFix:       "Move shared behavior into a reusable package and keep cmd packages as entrypoints only.",
	},
	"design.generic-package-name": {
		ID:             "design.generic-package-name",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Generic package name",
		Description:    "Warns when a package name is too generic to communicate ownership or responsibility.",
		HowToFix:       "Rename the package to something specific to its responsibility.",
	},
	"design.max-methods-per-type": {
		ID:             "design.max-methods-per-type",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Methods per type",
		Description:    "Warns when a type accumulates too many methods.",
		HowToFix:       "Split responsibilities across smaller types or interfaces.",
	},
	"design.max-interface-methods": {
		ID:             "design.max-interface-methods",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Interface size",
		Description:    "Warns when an interface is too large.",
		HowToFix:       "Break the interface into smaller focused contracts.",
	},
	"design.max-decls-per-file": {
		ID:             "design.max-decls-per-file",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Declarations per file",
		Description:    "Warns when a file accumulates too many top-level declarations.",
		HowToFix:       "Move related declarations into smaller files with clearer ownership.",
	},
	"design.typescript.generic-module-name": {
		ID:             "design.typescript.generic-module-name",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript generic module name",
		Description:    "Warns when a TypeScript or JavaScript module name is too generic to communicate ownership or responsibility.",
		HowToFix:       "Rename the module to something specific to its responsibility.",
	},
	"design.cpp.generic-module-name": {
		ID:               "design.cpp.generic-module-name",
		Section:          "Design Patterns",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(core.RuleLanguageCPP),
		Title:            "C++ generic file name",
		Description:      "Warns when a C++ source, header, or module file name is too generic to communicate responsibility.",
		HowToFix:         "Rename the file after the component or responsibility it owns.",
	},
	"design.cpp.max-methods-per-type": {
		ID:               "design.cpp.max-methods-per-type",
		Section:          "Design Patterns",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(core.RuleLanguageCPP),
		Title:            "C++ methods per type",
		Description:      "Warns when one C++ file defines too many qualified methods for the same type.",
		HowToFix:         "Split the type's responsibilities across smaller types or extracted collaborators.",
	},
	"design.cpp.max-decls-per-file": {
		ID:               "design.cpp.max-decls-per-file",
		Section:          "Design Patterns",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(core.RuleLanguageCPP),
		Title:            "C++ declarations per file",
		Description:      "Warns when a C++ file accumulates too many top-level declarations.",
		HowToFix:         "Split unrelated types and functions into smaller translation units or headers with clearer ownership.",
	},
	"design.cpp.max-interface-methods": {
		ID:               "design.cpp.max-interface-methods",
		Section:          "Design Patterns",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(core.RuleLanguageCPP),
		Title:            "C++ contract surface size",
		Description:      "Warns when a C++ contract file exposes too many public methods on one type.",
		HowToFix:         "Break the public surface into smaller focused contracts or move implementation details behind non-public helpers.",
	},
	"design.typescript.max-methods-per-type": {
		ID:             "design.typescript.max-methods-per-type",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript methods per type",
		Description:    "Warns when a TypeScript class accumulates too many methods.",
		HowToFix:       "Split responsibilities across smaller classes or extracted collaborators.",
	},
	"design.typescript.max-interface-members": {
		ID:             "design.typescript.max-interface-members",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript interface size",
		Description:    "Warns when a TypeScript interface or object type accumulates too many members.",
		HowToFix:       "Break the interface or type into smaller focused contracts.",
	},
	"design.python.public-imports-private": {
		ID:             "design.python.public-imports-private",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python public-to-private import",
		Description:    "Fails when a public Python module imports a private module or private symbol.",
		HowToFix:       "Keep private helpers behind the public module boundary or move shared logic into a public module.",
	},
	"design.python.public-imports-cli": {
		ID:             "design.python.public-imports-cli",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python public-to-entrypoint import",
		Description:    "Fails when a public Python module imports a CLI or entrypoint module.",
		HowToFix:       "Move shared behavior into a reusable module and keep entrypoints thin.",
	},
	"design.python.public-depends-on-cli": {
		ID:             "design.python.public-depends-on-cli",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python transitive entrypoint dependency",
		Description:    "Fails when a public Python module reaches a CLI or entrypoint module through the project import graph.",
		HowToFix:       "Remove the dependency path into the entrypoint layer and move shared behavior into reusable modules.",
	},
	"design.python.import-cycle": {
		ID:             "design.python.import-cycle",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python import cycle",
		Description:    "Fails when Python modules form an internal import cycle.",
		HowToFix:       "Break the cycle by extracting shared behavior behind a lower-level module or by inverting the dependency direction.",
	},
	"design.python.generic-module-name": {
		ID:             "design.python.generic-module-name",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python generic module name",
		Description:    "Warns when a Python module name is too generic to communicate ownership or responsibility.",
		HowToFix:       "Rename the module to something specific to its responsibility.",
	},
	"design.python.max-methods-per-type": {
		ID:             "design.python.max-methods-per-type",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python methods per type",
		Description:    "Warns when a Python class accumulates too many direct methods.",
		HowToFix:       "Split responsibilities across smaller classes or extract collaborators.",
	},
	"design.python.max-protocol-members": {
		ID:             "design.python.max-protocol-members",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python protocol surface size",
		Description:    "Warns when a Python Protocol accumulates too many direct members.",
		HowToFix:       "Break the protocol into smaller focused contracts.",
	},
	"design.rust.generic-module-name": {
		ID:               "design.rust.generic-module-name",
		Section:          "Design Patterns",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(core.RuleLanguageRust),
		Title:            "Rust generic module name",
		Description:      "Warns when a Rust module name is too generic to communicate ownership or responsibility.",
		HowToFix:         "Rename the module to something specific to its responsibility.",
	},
	"design.rust.max-methods-per-type": {
		ID:               "design.rust.max-methods-per-type",
		Section:          "Design Patterns",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(core.RuleLanguageRust),
		Title:            "Rust methods per type",
		Description:      "Warns when a Rust type accumulates too many impl methods within one file.",
		HowToFix:         "Split responsibilities across smaller types, traits, or modules.",
	},
	"design.rust.max-trait-members": {
		ID:               "design.rust.max-trait-members",
		Section:          "Design Patterns",
		DefaultLevel:     "warn",
		ExecutionModel:   core.RuleExecutionModelLanguageAgnostic,
		LanguageCoverage: core.FixedRuleLanguageCoverage(core.RuleLanguageRust),
		Title:            "Rust trait surface size",
		Description:      "Warns when a Rust trait accumulates too many members.",
		HowToFix:         "Break the trait into smaller focused contracts.",
	},
}
