package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var securityCatalog = map[string]core.RuleMetadata{
	"security.hardcoded-secret": {
		ID:             "security.hardcoded-secret",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Hardcoded secret",
		Description:    "Fails when a likely hardcoded secret is detected in source text.",
		HowToFix:       "Remove the secret from the repository and load it from a secret manager or environment at runtime.",
	},
	"security.private-key": {
		ID:             "security.private-key",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Private key material",
		Description:    "Fails when PEM private key material is detected.",
		HowToFix:       "Delete the committed key, rotate the credential, and load key material from secure storage.",
	},
	"security.insecure-tls": {
		ID:             "security.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Insecure TLS",
		Description:    "Fails when insecure TLS verification is explicitly disabled.",
		HowToFix:       "Enable certificate verification and use trusted certificates in non-local environments.",
	},
	"security.shell-execution": {
		ID:             "security.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Shell execution review",
		Description:    "Warns when shell execution primitives are used and should receive manual review.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain command execution.",
	},
	"security.govulncheck": {
		ID:             "security.govulncheck",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		Title:          "Govulncheck finding",
		Description:    "Surfaces vulnerabilities or integration failures from govulncheck.",
		HowToFix:       "Install govulncheck, then upgrade or replace the affected dependency and re-run the scan.",
	},
	"security.command-check": {
		ID:             "security.command-check",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		Title:          "Language security command",
		Description:    "Fails when a configured language-specific security command exits non-zero.",
		HowToFix:       "Fix the reported issue from the command output or adjust the configured command if it does not fit the target.",
	},
	"security.typescript.insecure-tls": {
		ID:             "security.typescript.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript insecure TLS",
		Description:    "Fails when TypeScript or JavaScript code disables TLS verification.",
		HowToFix:       "Enable certificate verification and use trusted certificates in non-local environments.",
	},
	"security.typescript.shell-execution": {
		ID:             "security.typescript.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript shell execution review",
		Description:    "Warns when TypeScript or JavaScript code invokes shell execution primitives.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain command execution.",
	},
	"security.typescript.dynamic-code": {
		ID:             "security.typescript.dynamic-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript dynamic code execution",
		Description:    "Warns when TypeScript or JavaScript code evaluates dynamic source text.",
		HowToFix:       "Remove eval-style execution or strictly constrain and validate the executed content.",
	},
	"security.typescript.vm-dynamic-code": {
		ID:             "security.typescript.vm-dynamic-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript Node vm execution",
		Description:    "Warns when TypeScript or JavaScript code uses Node vm APIs to compile or execute dynamic code.",
		HowToFix:       "Avoid dynamic vm execution, or strictly constrain and validate the executed content and context.",
	},
	"security.typescript.unsafe-html-sink": {
		ID:             "security.typescript.unsafe-html-sink",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript unsafe HTML sink",
		Description:    "Warns when TypeScript or JavaScript code writes untrusted content into unsafe HTML injection sinks.",
		HowToFix:       "Prefer safe DOM APIs or sanitize content before writing to HTML sinks.",
	},
	"security.typescript.string-timer-code": {
		ID:             "security.typescript.string-timer-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript string timer execution",
		Description:    "Warns when TypeScript code uses string-based setTimeout or setInterval execution.",
		HowToFix:       "Pass a function instead of source text to timer APIs.",
	},
	"security.typescript.postmessage-wildcard": {
		ID:             "security.typescript.postmessage-wildcard",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript postMessage wildcard origin",
		Description:    "Warns when TypeScript code sends postMessage calls to the wildcard origin.",
		HowToFix:       "Use a specific trusted origin instead of * when sending cross-origin messages.",
	},
	"security.typescript.untrusted-input-flow": {
		ID:             "security.typescript.untrusted-input-flow",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript untrusted input flow",
		Description:    "Warns when TypeScript semantic analysis finds untrusted input flowing into a risky sink.",
		HowToFix:       "Validate or sanitize the input before the sink, or replace the sink with a safer API.",
	},
	"security.javascript.insecure-tls": {
		ID:             "security.javascript.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "JavaScript insecure TLS",
		Description:    "Fails when JavaScript code disables TLS verification.",
		HowToFix:       "Enable certificate verification and use trusted certificates in non-local environments.",
	},
	"security.javascript.shell-execution": {
		ID:             "security.javascript.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "JavaScript shell execution review",
		Description:    "Warns when JavaScript code invokes shell execution primitives.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain command execution.",
	},
	"security.javascript.dynamic-code": {
		ID:             "security.javascript.dynamic-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "JavaScript dynamic code execution",
		Description:    "Warns when JavaScript code evaluates dynamic source text.",
		HowToFix:       "Remove eval-style execution or strictly constrain and validate the executed content.",
	},
	"security.javascript.vm-dynamic-code": {
		ID:             "security.javascript.vm-dynamic-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "JavaScript Node vm execution",
		Description:    "Warns when JavaScript code uses Node vm APIs to compile or execute dynamic code.",
		HowToFix:       "Avoid dynamic vm execution, or strictly constrain and validate the executed content and context.",
	},
	"security.javascript.unsafe-html-sink": {
		ID:             "security.javascript.unsafe-html-sink",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "JavaScript unsafe HTML sink",
		Description:    "Warns when JavaScript code writes untrusted content into unsafe HTML injection sinks.",
		HowToFix:       "Prefer safe DOM APIs or sanitize content before writing to HTML sinks.",
	},
	"security.javascript.string-timer-code": {
		ID:             "security.javascript.string-timer-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "JavaScript string timer execution",
		Description:    "Warns when JavaScript code uses string-based setTimeout or setInterval execution.",
		HowToFix:       "Pass a function instead of source text to timer APIs.",
	},
	"security.javascript.postmessage-wildcard": {
		ID:             "security.javascript.postmessage-wildcard",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "JavaScript postMessage wildcard origin",
		Description:    "Warns when JavaScript code sends postMessage calls to the wildcard origin.",
		HowToFix:       "Use a specific trusted origin instead of * when sending cross-origin messages.",
	},
	"security.javascript.untrusted-input-flow": {
		ID:             "security.javascript.untrusted-input-flow",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "JavaScript untrusted input flow",
		Description:    "Warns when JavaScript semantic analysis finds untrusted input flowing into a risky sink.",
		HowToFix:       "Validate or sanitize the input before the sink, or replace the sink with a safer API.",
	},
	"security.python.insecure-tls": {
		ID:             "security.python.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python insecure TLS",
		Description:    "Fails when Python code disables TLS verification.",
		HowToFix:       "Enable certificate verification and use trusted certificates in non-local environments.",
	},
	"security.python.shell-execution": {
		ID:             "security.python.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python shell execution review",
		Description:    "Warns when Python code invokes shell execution primitives.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain command execution.",
	},
	"security.python.dynamic-code": {
		ID:             "security.python.dynamic-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python dynamic code execution",
		Description:    "Warns when Python code evaluates or executes dynamic source text.",
		HowToFix:       "Remove eval or exec usage, or strictly constrain and validate the executed content.",
	},
	"security.rust.insecure-tls": {
		ID:             "security.rust.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Rust insecure TLS",
		Description:    "Fails when Rust code disables TLS certificate or hostname verification.",
		HowToFix:       "Enable certificate and hostname verification and use trusted certificates in non-local environments.",
	},
	"security.rust.shell-execution": {
		ID:             "security.rust.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Rust shell execution review",
		Description:    "Warns when Rust code launches shell interpreters through process execution APIs.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain spawned commands.",
	},
	"security.java.insecure-tls": {
		ID:             "security.java.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Java insecure TLS",
		Description:    "Fails when Java code disables hostname or certificate verification.",
		HowToFix:       "Use the default TLS verification flow or a properly validated trust configuration.",
	},
	"security.java.shell-execution": {
		ID:             "security.java.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Java shell execution review",
		Description:    "Warns when Java code invokes OS process execution primitives.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain spawned commands.",
	},
	"security.csharp.insecure-tls": {
		ID:             "security.csharp.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "C# insecure TLS",
		Description:    "Fails when C# code disables TLS certificate validation.",
		HowToFix:       "Use the default TLS validation flow or a properly validated custom certificate policy.",
	},
	"security.csharp.shell-execution": {
		ID:             "security.csharp.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "C# shell execution review",
		Description:    "Warns when C# code invokes OS process execution primitives.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain spawned commands.",
	},
	"security.ruby.insecure-tls": {
		ID:             "security.ruby.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Ruby insecure TLS",
		Description:    "Fails when Ruby code disables TLS verification.",
		HowToFix:       "Enable certificate verification and use trusted certificates in non-local environments.",
	},
	"security.ruby.shell-execution": {
		ID:             "security.ruby.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Ruby shell execution review",
		Description:    "Warns when Ruby code invokes shell or process execution primitives.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain spawned commands.",
	},
	"security.ruby.dynamic-code": {
		ID:             "security.ruby.dynamic-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Ruby dynamic code execution",
		Description:    "Warns when Ruby code evaluates dynamic source text.",
		HowToFix:       "Remove eval-style execution or strictly constrain and validate the executed content.",
	},
}
