package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

// securityFixTemplates covers the language-agnostic security rules: secrets,
// transport security, misconfiguration, crypto, and the Go/Python taint and
// SSRF analyses. Language-mirror rules live in
// catalog_fix_templates_security_lang.go.
var securityFixTemplates = map[string]core.FixTemplate{
	"security.hardcoded-credential":     {Kind: guided, Text: "Remove the credential, rotate it, and load it from the environment or a secret manager at runtime.\n\nBefore:\nconst stripeKey = \"sk_live_51H8x...\";\n\nAfter:\nconst stripeKey = process.env.STRIPE_API_KEY;\n// rotate the exposed key and purge it from git history"},
	"security.high-entropy-string":      {Kind: guided, Text: "If the literal is a secret, move it out of source and rotate it; if it is a non-secret constant, allowlist it.\n\nBefore:\ntoken = \"qJ8kP2vX9mN4wL7cR5tY3hB6dF1gS0aZ\"\n\nAfter:\ntoken = os.environ[\"SERVICE_TOKEN\"]\n# or, for a non-secret constant, add it to security_rules.secrets.allow_patterns"},
	"security.hardcoded-secret":         {Kind: guided, Text: "Remove the secret from the repository and load it from the environment or a secret manager at runtime.\n\nBefore:\ndb_password = \"hunter2\"\n\nAfter:\ndb_password = os.environ[\"DB_PASSWORD\"]\n# rotate the exposed value if it was ever a real credential"},
	"security.private-key":              {Kind: guided, Text: "Delete the committed key, rotate it, and load key material from secure storage at runtime.\n\nBefore:\n-----BEGIN RSA PRIVATE KEY-----\nMIIEow...\n\nAfter:\n// key removed from the repository; provisioned by the deploy environment\nkey, err := os.ReadFile(os.Getenv(\"TLS_KEY_PATH\"))\n// rotate the exposed key and purge it from git history"},
	"security.insecure-tls":             {Kind: deterministic, Text: "Remove InsecureSkipVerify so certificate verification stays on.\n\nBefore:\nclient := &http.Client{Transport: &http.Transport{\n\tTLSClientConfig: &tls.Config{InsecureSkipVerify: true},\n}}\n\nAfter:\nclient := &http.Client{} // the default transport verifies certificates"},
	"security.shell-execution":          {Kind: guided, Text: "Run a fixed binary with an argv list instead of handing a composed string to a shell.\n\nBefore:\nexec.Command(\"sh\", \"-c\", \"convert \"+userFile)\n\nAfter:\nexec.Command(\"convert\", userFile) // fixed binary, arguments passed without a shell"},
	"security.secrets-config":           {Kind: deterministic, Text: "Fix the unusable pattern in security_rules.secrets so it participates in the scan.\n\nBefore:\nsecrets:\n  custom_patterns:\n    - id: acme-token\n      regex: \"acme_live_[0-9a-f]{16\"   # unbalanced brace, pattern skipped\n\nAfter:\nsecrets:\n  custom_patterns:\n    - id: acme-token\n      regex: \"acme_live_[0-9a-f]{16}\""},
	"security.govulncheck":              {Kind: guided, Text: "Upgrade the affected dependency past the fixed version and re-run govulncheck.\n\nBefore:\n$ govulncheck ./...\nGO-2023-2102: golang.org/x/net before v0.17.0 ...\n\nAfter:\n$ go get golang.org/x/net@v0.17.0 && go mod tidy\n$ govulncheck ./... # reports no findings"},
	"security.command-check":            {Kind: guided, Text: "Run the configured security command locally and fix each reported finding at its source.\n\nBefore:\n$ bandit -r app/\nB602 subprocess call with shell=True identified\n\nAfter:\nsubprocess.run([\"convert\", user_file], check=True)  # fix at the source\n# re-run until the command exits 0; adjust the command only if it does not fit the target"},
	"security.cors-wildcard":            {Kind: guided, Text: "Reflect a validated allowlist of trusted origins instead of returning '*'.\n\nBefore:\nw.Header().Set(\"Access-Control-Allow-Origin\", \"*\")\n\nAfter:\nif allowedOrigins[origin] {\n\tw.Header().Set(\"Access-Control-Allow-Origin\", origin)\n\tw.Header().Set(\"Vary\", \"Origin\")\n}"},
	"security.debug-enabled":            {Kind: guided, Text: "Drive debug mode from environment configuration and default it to off.\n\nBefore:\napp.run(debug=True)\n\nAfter:\napp.run(debug=os.environ.get(\"FLASK_DEBUG\") == \"1\")  # off unless explicitly enabled"},
	"security.bind-all-interfaces":      {Kind: guided, Text: "Bind to a specific interface unless the service is deliberately public.\n\nBefore:\napp.run(host=\"0.0.0.0\", port=8080)\n\nAfter:\napp.run(host=\"127.0.0.1\", port=8080)\n# expose deliberately through a reverse proxy or firewall rule when needed"},
	"security.dockerfile-root":          {Kind: deterministic, Text: "Add a dedicated non-root user and switch to it before the entrypoint.\n\nBefore:\nUSER root\nCMD [\"./server\"]\n\nAfter:\nRUN adduser --system --no-create-home app\nUSER app\nCMD [\"./server\"]"},
	"security.weak-hash":                {Kind: deterministic, Text: "Replace MD5 or SHA-1 with SHA-256 for integrity; use a dedicated password hash for credentials.\n\nBefore:\nsum := md5.Sum(data)\n\nAfter:\nsum := sha256.Sum256(data)\n// for passwords, use bcrypt.GenerateFromPassword instead of any plain hash"},
	"security.weak-cipher":              {Kind: guided, Text: "Replace the legacy cipher or ECB mode with an authenticated mode such as AES-GCM.\n\nBefore:\nblock, _ := des.NewCipher(key)\n\nAfter:\nblock, err := aes.NewCipher(key)\ngcm, err := cipher.NewGCM(block)\nciphertext := gcm.Seal(nil, nonce, plaintext, nil) // unique nonce per message"},
	"security.insecure-deserialization": {Kind: guided, Text: "Deserialize untrusted data with a data-only format or a safe loader.\n\nBefore:\nconfig = pickle.loads(request.data)\n\nAfter:\nconfig = json.loads(request.data)\n# or yaml.safe_load(...) for YAML input; reserve pickle for trusted, internal data"},
	"security.taint.go":                 {Kind: guided, Text: "Break the source-to-sink chain: parameterize the query or constrain the value before the sink.\n\nBefore:\nname := r.URL.Query().Get(\"name\")\ndb.Query(\"SELECT * FROM users WHERE name = '\" + name + \"'\")\n\nAfter:\nname := r.URL.Query().Get(\"name\")\ndb.Query(\"SELECT * FROM users WHERE name = ?\", name)"},
	"security.taint.python":             {Kind: guided, Text: "Break the source-to-sink chain: pass an argv list, parameterized query, or parsed value instead of interpolated input.\n\nBefore:\nos.system(\"ping \" + hostname)\n\nAfter:\nsubprocess.run([\"ping\", \"-c\", \"1\", hostname], check=True)  # argv list, no shell\n# for SQL: cursor.execute(\"SELECT * FROM users WHERE name = %s\", (name,))"},
	"security.ssrf.go":                  {Kind: guided, Text: "Validate the destination against an allowlist of trusted hosts before issuing the request.\n\nBefore:\nresp, err := http.Get(r.URL.Query().Get(\"url\"))\n\nAfter:\ntarget, err := url.Parse(r.URL.Query().Get(\"url\"))\nif err != nil || !allowedHosts[target.Hostname()] {\n\thttp.Error(w, \"untrusted destination\", http.StatusBadRequest)\n\treturn\n}\nresp, err := http.Get(target.String()) // also block private and link-local addresses"},
	"security.ssrf.python":              {Kind: guided, Text: "Validate the destination against an allowlist of trusted hosts before issuing the request.\n\nBefore:\nresp = requests.get(request.args[\"url\"])\n\nAfter:\ntarget = urllib.parse.urlparse(request.args[\"url\"])\nif target.hostname not in ALLOWED_HOSTS:\n    abort(400, \"untrusted destination\")\nresp = requests.get(target.geturl())  # also block private and link-local addresses"},
}
