package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

// performanceFixTemplates covers the performance section heuristics.
var performanceFixTemplates = map[string]core.FixTemplate{
	"performance.sync-io-in-request-path":          {Kind: guided, Text: "Load the data once at startup or cache it instead of reading the filesystem per request.\n\nBefore:\nfunc handler(w http.ResponseWriter, r *http.Request) {\n\tdata, _ := os.ReadFile(\"config.json\")\n\tw.Write(data)\n}\n\nAfter:\nvar config = mustLoadConfig(\"config.json\") // loaded once at startup\n\nfunc handler(w http.ResponseWriter, r *http.Request) {\n\tw.Write(config)\n}"},
	"performance.unbounded-goroutines-in-loop":     {Kind: guided, Text: "Bound loop-driven concurrency with a worker pool, semaphore, or errgroup limit.\n\nBefore:\nfor _, job := range jobs {\n\tgo process(job)\n}\n\nAfter:\ngroup, ctx := errgroup.WithContext(ctx)\ngroup.SetLimit(8)\nfor _, job := range jobs {\n\tgroup.Go(func() error { return process(ctx, job) })\n}\nif err := group.Wait(); err != nil {\n\treturn err\n}"},
	"performance.n-plus-one-query":                 {Kind: guided, Text: "Batch the per-item lookups into one query issued before the loop.\n\nBefore:\nfor _, id := range ids {\n\tuser, _ := db.GetUser(ctx, id)\n\tusers = append(users, user)\n}\n\nAfter:\nusers, err := db.GetUsersByIDs(ctx, ids) // single batched query"},
	"performance.go.alloc-in-loop":                 {Kind: guided, Text: "Use strings.Builder for string accumulation and preallocate slice capacity before the loop.\n\nBefore:\nvar out string\nfor _, line := range lines {\n\tout += line + \"\\n\"\n}\n\nAfter:\nvar b strings.Builder\nfor _, line := range lines {\n\tb.WriteString(line)\n\tb.WriteByte('\\n')\n}\nout := b.String()"},
	"performance.typescript.sync-io-in-handler":    {Kind: guided, Text: "Switch to the promise-based API inside request handlers so the event loop is not blocked.\n\nBefore:\napp.get(\"/report\", (req, res) => {\n  const data = fs.readFileSync(\"report.json\", \"utf8\");\n  res.send(data);\n});\n\nAfter:\napp.get(\"/report\", async (req, res) => {\n  const data = await fs.promises.readFile(\"report.json\", \"utf8\");\n  res.send(data);\n});"},
	"performance.javascript.sync-io-in-handler":    {Kind: guided, Text: "Switch to the promise-based API inside request handlers so the event loop is not blocked.\n\nBefore:\napp.get(\"/report\", (req, res) => {\n  res.send(fs.readFileSync(\"report.json\"));\n});\n\nAfter:\nconst fsp = require(\"fs/promises\");\napp.get(\"/report\", async (req, res) => {\n  res.send(await fsp.readFile(\"report.json\"));\n});"},
	"performance.typescript.unbounded-concurrency": {Kind: guided, Text: "Process the work in bounded chunks or wrap calls with a concurrency limiter.\n\nBefore:\nfor (const url of urls) {\n  promises.push(fetch(url));\n}\nawait Promise.all(promises);\n\nAfter:\nimport pLimit from \"p-limit\";\nconst limit = pLimit(8);\nawait Promise.all(urls.map((url) => limit(() => fetch(url))));"},
	"performance.javascript.unbounded-concurrency": {Kind: guided, Text: "Process the work in bounded chunks or wrap calls with a concurrency limiter.\n\nBefore:\nfor (const url of urls) {\n  promises.push(fetch(url));\n}\nawait Promise.all(promises);\n\nAfter:\nfor (let i = 0; i < urls.length; i += 8) {\n  await Promise.all(urls.slice(i, i + 8).map((url) => fetch(url)));\n}"},
	"performance.python.sync-io-in-async":          {Kind: guided, Text: "Use async clients and asyncio.sleep inside async functions so the event loop is not blocked.\n\nBefore:\nasync def refresh():\n    data = requests.get(url).json()\n    time.sleep(1)\n\nAfter:\nasync def refresh():\n    async with httpx.AsyncClient() as client:\n        data = (await client.get(url)).json()\n    await asyncio.sleep(1)"},
}
