package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

// contextFixTemplates covers the agent-context legibility rule family.
var contextFixTemplates = map[string]core.FixTemplate{
	"context.agent-docs-missing":     {Kind: guided, Text: "Create a CLAUDE.md (or AGENTS.md) at the repository root that tells an agent how to work in this repo.\n\nBefore:\n(no CLAUDE.md, AGENTS.md, .cursorrules, or .github/copilot-instructions.md)\n\nAfter:\n# CLAUDE.md\n\n## Build & test\n- make build\n- make test\n\n## Layout\n- cmd/: CLI entrypoints\n- internal/: implementation packages\n\n## Conventions\n- run make fmt before committing"},
	"context.agent-docs-drift":       {Kind: guided, Text: "Point the agent doc at things that exist: fix the path, target, or script it references, or delete the stale instruction.\n\nBefore:\n# CLAUDE.md\nRun `make deploy-all` and edit `internal/server/router.go`.\n\nAfter:\n# CLAUDE.md\nRun `make deploy` and edit `internal/api/router.go`."},
	"context.readme-drift":           {Kind: guided, Text: "Update the README's command examples to match the current scripts and make targets.\n\nBefore:\n```bash\n./scripts/setup.sh\nmake bootstrap\n```\n\nAfter:\n```bash\n./scripts/dev-setup.sh\nmake build\n```"},
	"context.oversized-context-unit": {Kind: guided, Text: "Split the file into cohesive units that each fit an agent's working context.\n\nBefore:\n// handlers.go: 2400 lines mixing auth, billing, and admin endpoints\n\nAfter:\n// handlers_auth.go, handlers_billing.go, handlers_admin.go\n// each under the configured line budget, grouped by responsibility"},
	"context.ambiguous-symbol":       {Kind: guided, Text: "Rename duplicated basenames so search results identify a file unambiguously.\n\nBefore:\napi/utils.ts, billing/utils.ts, auth/utils.ts, admin/utils.ts\n\nAfter:\napi/http_helpers.ts, billing/invoice_math.ts, auth/token_helpers.ts, admin/audit_format.ts"},
	"context.legibility-threshold":   {Kind: guided, Text: "Raise the components the finding names as weakest until the score clears the configured floor.\n\nBefore:\nrepository legibility score 58 below warn threshold 80\n(agent_docs 5/25, readme 10/10, doc_accuracy 8/20, context_economy 15/25, navigability 20/20)\n\nAfter:\n1. agent_docs: flesh out CLAUDE.md with real build/test/layout guidance and fix its stale references\n2. doc_accuracy: update or delete doc references that no longer resolve\n3. context_economy: split files that exceed context_rules.max_file_lines\nRe-run the scan; the score and trend are visible via codeguard report -legibility-history"},
}
