package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var qualityCatalog = map[string]core.RuleMetadata{
	"quality.gofmt": {
		ID:             "quality.gofmt",
		Section:        "Code Quality",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Go formatting",
		Description:    "Fails when a Go source file is not gofmt-clean.",
		HowToFix:       "Run gofmt on the file and commit the formatted result.",
	},
	"quality.parse-error": {
		ID:             "quality.parse-error",
		Section:        "Code Quality",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Go parseability",
		Description:    "Fails when a Go source file cannot be parsed.",
		HowToFix:       "Fix the syntax error so the file parses cleanly.",
	},
	"quality.max-file-lines": {
		ID:             "quality.max-file-lines",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "File length",
		Description:    "Warns when a file exceeds the configured maximum line count.",
		HowToFix:       "Split the file into smaller units or raise the configured threshold intentionally.",
	},
	"quality.max-function-lines": {
		ID:             "quality.max-function-lines",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Function length",
		Description:    "Warns when a function exceeds the configured maximum line count.",
		HowToFix:       "Break the function into smaller helpers or raise the threshold intentionally.",
	},
	"quality.max-parameters": {
		ID:             "quality.max-parameters",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Function parameters",
		Description:    "Warns when a function exceeds the configured parameter count.",
		HowToFix:       "Group related inputs into a struct or simplify the function signature.",
	},
	"quality.cyclomatic-complexity": {
		ID:             "quality.cyclomatic-complexity",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Cyclomatic complexity",
		Description:    "Warns when a function exceeds the configured cyclomatic complexity threshold.",
		HowToFix:       "Reduce branching in the function or refactor logic into smaller units.",
	},
	"quality.dependency-direction": {
		ID:             "quality.dependency-direction",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Dependency direction",
		Description:    "Warns when non-CLI packages import CLI-only implementation details.",
		HowToFix:       "Move shared logic into reusable packages and keep internal or CLI details out of library code.",
	},
	"quality.command-check": {
		ID:             "quality.command-check",
		Section:        "Code Quality",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		Title:          "Language quality command",
		Description:    "Fails when a configured language-specific quality command exits non-zero.",
		HowToFix:       "Fix the reported issue from the command output or adjust the configured command if it does not fit the target.",
	},
	"quality.typescript.ts-ignore": {
		ID:             "quality.typescript.ts-ignore",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript suppression comment",
		Description:    "Warns when TypeScript code uses @ts-ignore to suppress type checking.",
		HowToFix:       "Remove the suppression by correcting the underlying type issue or replacing it with a narrower escape hatch.",
	},
	"quality.typescript.explicit-any": {
		ID:             "quality.typescript.explicit-any",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript explicit any",
		Description:    "Warns when TypeScript code opts out of type safety with explicit any.",
		HowToFix:       "Use a narrower type, a generic constraint, or a targeted unknown-based refinement instead of any.",
	},
	"quality.typescript.ts-nocheck": {
		ID:             "quality.typescript.ts-nocheck",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript file-level suppression",
		Description:    "Warns when a TypeScript file disables type checking with @ts-nocheck.",
		HowToFix:       "Remove the file-level suppression and address the underlying type errors directly.",
	},
	"quality.typescript.double-assertion": {
		ID:             "quality.typescript.double-assertion",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript double assertion",
		Description:    "Warns when TypeScript code uses chained assertions such as as unknown as T to bypass type safety.",
		HowToFix:       "Replace the double assertion with a narrower source type, runtime validation, or a safer refinement step.",
	},
	"quality.typescript.non-null-assertion": {
		ID:             "quality.typescript.non-null-assertion",
		Section:        "Code Quality",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript non-null assertion",
		Description:    "Warns when TypeScript code forces nullability away with the non-null assertion operator.",
		HowToFix:       "Prove nullability through control flow, validation, or safer API design instead of using ! assertions.",
	},
}
