package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var securityCatalog = map[string]core.RuleMetadata{
	"security.hardcoded-secret": {
		ID:             "security.hardcoded-secret",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Hardcoded secret",
		Description:    "Fails when a likely hardcoded secret is detected in source text.",
		HowToFix:       "Remove the secret from the repository and load it from a secret manager or environment at runtime.",
	},
	"security.private-key": {
		ID:             "security.private-key",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Private key material",
		Description:    "Fails when PEM private key material is detected.",
		HowToFix:       "Delete the committed key, rotate the credential, and load key material from secure storage.",
	},
	"security.insecure-tls": {
		ID:             "security.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Insecure TLS",
		Description:    "Fails when insecure TLS verification is explicitly disabled.",
		HowToFix:       "Enable certificate verification and use trusted certificates in non-local environments.",
	},
	"security.shell-execution": {
		ID:             "security.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Shell execution review",
		Description:    "Warns when shell execution primitives are used and should receive manual review.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain command execution.",
	},
	"security.govulncheck": {
		ID:             "security.govulncheck",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		Title:          "Govulncheck finding",
		Description:    "Surfaces vulnerabilities or integration failures from govulncheck.",
		HowToFix:       "Install govulncheck, then upgrade or replace the affected dependency and re-run the scan.",
	},
	"security.command-check": {
		ID:             "security.command-check",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelCommandDriven,
		Title:          "Language security command",
		Description:    "Fails when a configured language-specific security command exits non-zero.",
		HowToFix:       "Fix the reported issue from the command output or adjust the configured command if it does not fit the target.",
	},
	"security.typescript.insecure-tls": {
		ID:             "security.typescript.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript insecure TLS",
		Description:    "Fails when TypeScript or JavaScript code disables TLS verification.",
		HowToFix:       "Enable certificate verification and use trusted certificates in non-local environments.",
	},
	"security.typescript.shell-execution": {
		ID:             "security.typescript.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript shell execution review",
		Description:    "Warns when TypeScript or JavaScript code invokes shell execution primitives.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain command execution.",
	},
	"security.typescript.dynamic-code": {
		ID:             "security.typescript.dynamic-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript dynamic code execution",
		Description:    "Warns when TypeScript or JavaScript code evaluates dynamic source text.",
		HowToFix:       "Remove eval-style execution or strictly constrain and validate the executed content.",
	},
	"security.typescript.vm-dynamic-code": {
		ID:             "security.typescript.vm-dynamic-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript Node vm execution",
		Description:    "Warns when TypeScript or JavaScript code uses Node vm APIs to compile or execute dynamic code.",
		HowToFix:       "Avoid dynamic vm execution, or strictly constrain and validate the executed content and context.",
	},
	"security.typescript.unsafe-html-sink": {
		ID:             "security.typescript.unsafe-html-sink",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript unsafe HTML sink",
		Description:    "Warns when TypeScript or JavaScript code writes untrusted content into unsafe HTML injection sinks.",
		HowToFix:       "Prefer safe DOM APIs or sanitize content before writing to HTML sinks.",
	},
	"security.python.insecure-tls": {
		ID:             "security.python.insecure-tls",
		Section:        "Security",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python insecure TLS",
		Description:    "Fails when Python code disables TLS verification.",
		HowToFix:       "Enable certificate verification and use trusted certificates in non-local environments.",
	},
	"security.python.shell-execution": {
		ID:             "security.python.shell-execution",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python shell execution review",
		Description:    "Warns when Python code invokes shell execution primitives.",
		HowToFix:       "Prefer direct library calls, or tightly validate and constrain command execution.",
	},
	"security.python.dynamic-code": {
		ID:             "security.python.dynamic-code",
		Section:        "Security",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python dynamic code execution",
		Description:    "Warns when Python code evaluates or executes dynamic source text.",
		HowToFix:       "Remove eval or exec usage, or strictly constrain and validate the executed content.",
	},
}
