package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

// designFixTemplates covers the design rules: boundary violations, import
// cycles, size limits, and dependency-graph concentration. All are guided —
// each template shows the import restructure or extraction shape.
var designFixTemplates = map[string]core.FixTemplate{
	"design.command-check":                    {Kind: guided, Text: "Run the configured design command locally and fix each reported boundary violation at its source.\n\nBefore:\n$ npx depcruise src\nerror no-cli-imports: src/lib/render.ts -> src/cli/flags.ts\n\nAfter:\n// move the shared flag types from src/cli into src/lib\n// re-run until the command exits 0; adjust the command only if it does not fit the target"},
	"design.diff-command-check":               {Kind: guided, Text: "Restore the contract the diff command reports as broken, or update the target contract deliberately.\n\nBefore:\n$ oasdiff breaking base.yaml head.yaml\nDELETE /v1/orders removed\n\nAfter:\n// restore the removed operation and ship the replacement additively\n// or version the API and update the configured contract target in the same change"},
	"design.cmd-through-internal-cli":         {Kind: guided, Text: "Route the entrypoint through internal/cli instead of importing service packages directly.\n\nBefore:\n// cmd/app/main.go\nimport \"example.com/app/internal/codeguard/runner\"\n\nAfter:\n// cmd/app/main.go\nimport \"example.com/app/internal/cli\"\n\nfunc main() {\n\tos.Exit(cli.Run(os.Args[1:], os.Stdin, os.Stdout, os.Stderr))\n}"},
	"design.service-import-internal":          {Kind: guided, Text: "Move the needed code behind a public boundary instead of importing internal packages from reusable code.\n\nBefore:\n// pkg/render/render.go\nimport \"example.com/app/internal/layout\"\n\nAfter:\n// relocate the shared types from internal/layout into a public package\nimport \"example.com/app/pkg/layout\""},
	"design.service-import-cmd":               {Kind: guided, Text: "Move the shared behavior out of cmd into a reusable package and import it from there.\n\nBefore:\n// pkg/render/render.go\nimport \"example.com/app/cmd/app\"\n\nAfter:\n// move the helper from cmd/app into a reusable package\nimport \"example.com/app/pkg/appflags\""},
	"design.generic-package-name":             {Kind: guided, Text: "Rename the package after the responsibility it owns.\n\nBefore:\npackage util\n\nAfter:\npackage retry // named for the one thing it provides"},
	"design.max-methods-per-type":             {Kind: guided, Text: "Split the type's responsibilities across smaller collaborators.\n\nBefore:\ntype Server struct{ /* ... */ } // 30 methods: routing, auth, billing, metrics\n\nAfter:\ntype Server struct {\n\tauth    Auth\n\tbilling Billing\n\tmetrics Metrics\n}\n// each collaborator owns its own focused method set"},
	"design.max-interface-methods":            {Kind: guided, Text: "Break the interface into smaller focused contracts and accept only what each consumer needs.\n\nBefore:\ntype Store interface {\n\tGetUser(id string) (User, error)\n\tSaveUser(u User) error\n\tGetOrder(id string) (Order, error)\n\tSaveOrder(o Order) error\n\t// ...more\n}\n\nAfter:\ntype UserStore interface {\n\tGetUser(id string) (User, error)\n\tSaveUser(u User) error\n}\n\ntype OrderStore interface {\n\tGetOrder(id string) (Order, error)\n\tSaveOrder(o Order) error\n}"},
	"design.max-decls-per-file":               {Kind: guided, Text: "Move related declarations into smaller files with clearer ownership.\n\nBefore:\n// types.go: 40 top-level types, helpers, and constants\n\nAfter:\n// user_types.go, order_types.go, report_types.go: one concern per file"},
	"design.typescript.generic-module-name":   {Kind: guided, Text: "Rename the module after the responsibility it owns.\n\nBefore:\n// src/utils.ts\n\nAfter:\n// src/date-format.ts — named for the one thing it provides"},
	"design.typescript.max-methods-per-type":  {Kind: guided, Text: "Split the class's responsibilities across extracted collaborators.\n\nBefore:\nclass ApiClient {\n  // 30 methods: auth, users, orders, billing, retries\n}\n\nAfter:\nclass ApiClient {\n  readonly users: UsersApi;\n  readonly orders: OrdersApi;\n  readonly billing: BillingApi;\n}\n// each collaborator owns its own focused method set"},
	"design.typescript.max-interface-members": {Kind: guided, Text: "Break the interface or object type into smaller focused contracts.\n\nBefore:\ninterface Store {\n  getUser(id: string): User;\n  saveUser(user: User): void;\n  getOrder(id: string): Order;\n  saveOrder(order: Order): void;\n  // ...more\n}\n\nAfter:\ninterface UserStore {\n  getUser(id: string): User;\n  saveUser(user: User): void;\n}\n\ninterface OrderStore {\n  getOrder(id: string): Order;\n  saveOrder(order: Order): void;\n}"},
	"design.python.public-imports-private":    {Kind: guided, Text: "Expose the needed symbol through a public module instead of importing a private one.\n\nBefore:\n# api.py\nfrom app._internal import build_report\n\nAfter:\n# move build_report behind a public boundary\nfrom app.report import build_report"},
	"design.python.public-imports-cli":        {Kind: guided, Text: "Move the shared logic out of the entrypoint module and import it from a reusable module.\n\nBefore:\n# report.py\nfrom app.cli import parse_flags\n\nAfter:\n# move parse_flags from app/cli.py into a reusable module\nfrom app.options import parse_options"},
	"design.python.public-depends-on-cli":     {Kind: guided, Text: "Cut the import path that reaches the entrypoint layer by relocating the shared helper.\n\nBefore:\n# import graph: report.py -> formats.py -> cli.py\n\nAfter:\n# move the shared helper from cli.py into its own module\n# import graph: report.py -> formats.py -> tables.py"},
	"design.python.import-cycle":              {Kind: guided, Text: "Break the cycle by extracting the shared symbol into a lower-level module.\n\nBefore:\n# orders.py imports users.py; users.py imports orders.py\n\nAfter:\n# both import the shared type from models.py\n# orders.py -> models.py <- users.py"},
	"design.python.generic-module-name":       {Kind: guided, Text: "Rename the module after the responsibility it owns.\n\nBefore:\n# app/helpers.py\n\nAfter:\n# app/currency.py — named for the one thing it provides"},
	"design.typescript.import-cycle":          {Kind: guided, Text: "Break the cycle by extracting the shared symbol into a lower-level module.\n\nBefore:\n// order.ts imports user.ts; user.ts imports order.ts\n\nAfter:\n// both import the shared types from ids.ts\n// order.ts -> ids.ts <- user.ts"},
	"design.javascript.import-cycle":          {Kind: guided, Text: "Break the cycle by extracting the shared symbol into a lower-level module.\n\nBefore:\n// order.js requires user.js; user.js requires order.js\n\nAfter:\n// both require the shared helpers from ids.js\n// order.js -> ids.js <- user.js"},
	"design.rust.import-cycle":                {Kind: guided, Text: "Break the cycle by moving the shared items into a lower-level module.\n\nBefore:\n// orders.rs uses crate::users; users.rs uses crate::orders\n\nAfter:\n// move the shared struct into models.rs\n// orders.rs -> models.rs <- users.rs"},
	"design.java.import-cycle":                {Kind: guided, Text: "Break the cycle with an interface owned by the lower-level package.\n\nBefore:\n// billing.Invoice imports shipping.RateTable; shipping.RateTable imports billing.Invoice\n\nAfter:\n// billing defines interface RateSource; shipping implements it\n// billing no longer imports shipping, and shipping depends only on the interface"},
	"design.god-module":                       {Kind: guided, Text: "Split the module into focused pieces and route consumers through narrower interfaces.\n\nBefore:\n// core.ts: imported by 40 modules and importing 25 others\n\nAfter:\n// split into config.ts, events.ts, and store.ts\n// consumers import only the piece they actually use"},
	"design.high-impact-change":               {Kind: guided, Text: "Reduce the blast radius before merging a change to a widely depended-on module.\n\nBefore:\n// one commit rewrites shared/http.ts, which 60 modules transitively depend on\n\nAfter:\n// land a backwards-compatible refactor first, then migrate dependents in batches\n// add tests for the highest-traffic dependents before the breaking step"},
}
