package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var designCatalog = map[string]core.RuleMetadata{
	"design.cmd-through-internal-cli": {
		ID:             "design.cmd-through-internal-cli",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Command layer routing",
		Description:    "Fails when cmd entrypoints import reusable service packages directly instead of going through internal/cli.",
		HowToFix:       "Route command execution through internal/cli and keep cmd thin.",
	},
	"design.service-import-internal": {
		ID:             "design.service-import-internal",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Service to internal import",
		Description:    "Fails when reusable public packages, other than the SDK facade, import internal packages.",
		HowToFix:       "Move the dependency behind a public boundary or relocate the service code.",
	},
	"design.service-import-cmd": {
		ID:             "design.service-import-cmd",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Service to cmd import",
		Description:    "Fails when reusable service code imports cmd packages.",
		HowToFix:       "Move shared behavior into a reusable package and keep cmd packages as entrypoints only.",
	},
	"design.generic-package-name": {
		ID:             "design.generic-package-name",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Generic package name",
		Description:    "Warns when a package name is too generic to communicate ownership or responsibility.",
		HowToFix:       "Rename the package to something specific to its responsibility.",
	},
	"design.max-methods-per-type": {
		ID:             "design.max-methods-per-type",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Methods per type",
		Description:    "Warns when a type accumulates too many methods.",
		HowToFix:       "Split responsibilities across smaller types or interfaces.",
	},
	"design.max-interface-methods": {
		ID:             "design.max-interface-methods",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Interface size",
		Description:    "Warns when an interface is too large.",
		HowToFix:       "Break the interface into smaller focused contracts.",
	},
	"design.max-decls-per-file": {
		ID:             "design.max-decls-per-file",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelGoNative,
		Title:          "Declarations per file",
		Description:    "Warns when a file accumulates too many top-level declarations.",
		HowToFix:       "Move related declarations into smaller files with clearer ownership.",
	},
	"design.typescript.generic-module-name": {
		ID:             "design.typescript.generic-module-name",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript generic module name",
		Description:    "Warns when a TypeScript or JavaScript module name is too generic to communicate ownership or responsibility.",
		HowToFix:       "Rename the module to something specific to its responsibility.",
	},
	"design.typescript.max-methods-per-type": {
		ID:             "design.typescript.max-methods-per-type",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript methods per type",
		Description:    "Warns when a TypeScript class accumulates too many methods.",
		HowToFix:       "Split responsibilities across smaller classes or extracted collaborators.",
	},
	"design.typescript.max-interface-members": {
		ID:             "design.typescript.max-interface-members",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "TypeScript interface size",
		Description:    "Warns when a TypeScript interface or object type accumulates too many members.",
		HowToFix:       "Break the interface or type into smaller focused contracts.",
	},
	"design.python.public-imports-private": {
		ID:             "design.python.public-imports-private",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python public-to-private import",
		Description:    "Fails when a public Python module imports a private module or private symbol.",
		HowToFix:       "Keep private helpers behind the public module boundary or move shared logic into a public module.",
	},
	"design.python.public-imports-cli": {
		ID:             "design.python.public-imports-cli",
		Section:        "Design Patterns",
		DefaultLevel:   "fail",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python public-to-entrypoint import",
		Description:    "Fails when a public Python module imports a CLI or entrypoint module.",
		HowToFix:       "Move shared behavior into a reusable module and keep entrypoints thin.",
	},
	"design.python.generic-module-name": {
		ID:             "design.python.generic-module-name",
		Section:        "Design Patterns",
		DefaultLevel:   "warn",
		ExecutionModel: core.RuleExecutionModelLanguageAgnostic,
		Title:          "Python generic module name",
		Description:    "Warns when a Python module name is too generic to communicate ownership or responsibility.",
		HowToFix:       "Rename the module to something specific to its responsibility.",
	},
}
