package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

// securityLanguageFixTemplates covers the per-language security mirror rules
// (TypeScript, JavaScript, Python, C++, Rust, Java, C#, Ruby) with snippets in the
// idiom of each language.
var securityLanguageFixTemplates = map[string]core.FixTemplate{
	"security.typescript.insecure-tls":         {Kind: deterministic, Text: "Remove the verification opt-out so TLS certificates are checked.\n\nBefore:\nconst agent = new https.Agent({ rejectUnauthorized: false });\n\nAfter:\nconst agent = new https.Agent(); // the default agent verifies certificates"},
	"security.typescript.shell-execution":      {Kind: guided, Text: "Run a fixed binary with an argument array instead of interpolating into a shell string.\n\nBefore:\nexec(`convert ${userFile}`);\n\nAfter:\nexecFile(\"convert\", [userFile]); // fixed binary, arguments passed without a shell"},
	"security.typescript.dynamic-code":         {Kind: guided, Text: "Replace eval with a dispatch table or a data-only format.\n\nBefore:\nconst result = eval(userExpression);\n\nAfter:\nconst handlers: Record<string, (values: number[]) => number> = { sum, avg };\nconst result = handlers[name]?.(values); // dispatch instead of evaluating source text"},
	"security.typescript.vm-dynamic-code":      {Kind: guided, Text: "Evaluate declarative data instead of executing user source text through the vm module.\n\nBefore:\nvm.runInNewContext(userScript);\n\nAfter:\nconst config = JSON.parse(userInput); // data, not code\napplyConfig(config);"},
	"security.typescript.unsafe-html-sink":     {Kind: guided, Text: "Write untrusted content with a safe DOM API or sanitize it first.\n\nBefore:\nelement.innerHTML = userComment;\n\nAfter:\nelement.textContent = userComment;\n// or, when markup is required: element.innerHTML = DOMPurify.sanitize(userComment);"},
	"security.typescript.string-timer-code":    {Kind: deterministic, Text: "Pass a function to timer APIs instead of source text.\n\nBefore:\nsetTimeout(\"refresh()\", 1000);\n\nAfter:\nsetTimeout(() => refresh(), 1000);"},
	"security.typescript.taint-flow":           {Kind: guided, Text: "Parameterize the sink or validate the untrusted value before it arrives.\n\nBefore:\napp.get(\"/search\", (req, res) => {\n  db.query(`SELECT * FROM items WHERE name = '${req.query.q}'`);\n});\n\nAfter:\napp.get(\"/search\", (req, res) => {\n  db.query(\"SELECT * FROM items WHERE name = ?\", [req.query.q]);\n});"},
	"security.typescript.postmessage-wildcard": {Kind: guided, Text: "Send cross-origin messages to a specific trusted origin instead of '*'.\n\nBefore:\nframe.contentWindow.postMessage(payload, \"*\");\n\nAfter:\nframe.contentWindow.postMessage(payload, \"https://app.example.com\");"},
	"security.typescript.untrusted-input-flow": {Kind: guided, Text: "Constrain the untrusted value before the sink, or switch to an API that bounds it for you.\n\nBefore:\nconst file = req.query.file as string;\nres.sendFile(file);\n\nAfter:\nconst name = path.basename(String(req.query.file));\nres.sendFile(name, { root: DOWNLOADS_DIR }); // confined to a fixed directory"},
	"security.javascript.insecure-tls":         {Kind: deterministic, Text: "Remove the verification opt-out so TLS certificates are checked.\n\nBefore:\nprocess.env.NODE_TLS_REJECT_UNAUTHORIZED = \"0\";\n\nAfter:\n// delete the override; Node verifies certificates by default\n// for a private CA, pass ca: fs.readFileSync(\"ca.pem\") to https.Agent instead"},
	"security.javascript.shell-execution":      {Kind: guided, Text: "Run a fixed binary with an argument array instead of interpolating into a shell string.\n\nBefore:\nconst { exec } = require(\"child_process\");\nexec(\"convert \" + userFile);\n\nAfter:\nconst { execFile } = require(\"child_process\");\nexecFile(\"convert\", [userFile]); // fixed binary, arguments passed without a shell"},
	"security.javascript.dynamic-code":         {Kind: guided, Text: "Replace eval with a dispatch table or a data-only format.\n\nBefore:\nconst result = eval(userExpression);\n\nAfter:\nconst handlers = { sum, avg };\nconst result = handlers[name] ? handlers[name](values) : undefined; // dispatch instead of eval"},
	"security.javascript.vm-dynamic-code":      {Kind: guided, Text: "Evaluate declarative data instead of executing user source text through the vm module.\n\nBefore:\nconst vm = require(\"vm\");\nvm.runInNewContext(userScript);\n\nAfter:\nconst config = JSON.parse(userInput); // data, not code\napplyConfig(config);"},
	"security.javascript.unsafe-html-sink":     {Kind: guided, Text: "Write untrusted content with a safe DOM API or sanitize it first.\n\nBefore:\ndocument.getElementById(\"comment\").innerHTML = userComment;\n\nAfter:\ndocument.getElementById(\"comment\").textContent = userComment;\n// or, when markup is required: element.innerHTML = DOMPurify.sanitize(userComment);"},
	"security.javascript.string-timer-code":    {Kind: deterministic, Text: "Pass a function to timer APIs instead of source text.\n\nBefore:\nsetInterval(\"poll()\", 5000);\n\nAfter:\nsetInterval(() => poll(), 5000);"},
	"security.javascript.taint-flow":           {Kind: guided, Text: "Parameterize the sink or validate the untrusted value before it arrives.\n\nBefore:\napp.get(\"/search\", (req, res) => {\n  db.query(\"SELECT * FROM items WHERE name = '\" + req.query.q + \"'\");\n});\n\nAfter:\napp.get(\"/search\", (req, res) => {\n  db.query(\"SELECT * FROM items WHERE name = ?\", [req.query.q]);\n});"},
	"security.javascript.postmessage-wildcard": {Kind: guided, Text: "Send cross-origin messages to a specific trusted origin instead of '*'.\n\nBefore:\nwindow.parent.postMessage(payload, \"*\");\n\nAfter:\nwindow.parent.postMessage(payload, \"https://app.example.com\");"},
	"security.javascript.untrusted-input-flow": {Kind: guided, Text: "Constrain the untrusted value before the sink, or switch to an API that bounds it for you.\n\nBefore:\nres.sendFile(req.query.file);\n\nAfter:\nconst name = path.basename(String(req.query.file));\nres.sendFile(name, { root: DOWNLOADS_DIR }); // confined to a fixed directory"},
	"security.python.insecure-tls":             {Kind: deterministic, Text: "Remove verify=False so TLS certificates are checked.\n\nBefore:\nresp = requests.get(url, verify=False)\n\nAfter:\nresp = requests.get(url)  # requests verifies certificates by default\n# for a private CA: requests.get(url, verify=\"/etc/ssl/private-ca.pem\")"},
	"security.python.shell-execution":          {Kind: guided, Text: "Pass an argv list instead of a shell string.\n\nBefore:\nsubprocess.run(\"convert \" + user_file, shell=True)\n\nAfter:\nsubprocess.run([\"convert\", user_file], check=True)  # fixed binary, no shell"},
	"security.python.dynamic-code":             {Kind: guided, Text: "Replace eval or exec with a safe parser or a dispatch dict.\n\nBefore:\nresult = eval(user_expression)\n\nAfter:\nresult = ast.literal_eval(user_expression)  # literals only\n# or dispatch by name: handlers = {\"sum\": sum_values}; handlers[name](values)"},
	"security.cpp.insecure-tls":                {Kind: deterministic, Text: "Keep certificate and hostname verification enabled.\n\nBefore:\ncurl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);\n\nAfter:\ncurl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 1L);\ncurl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 2L);"},
	"security.cpp.shell-execution":             {Kind: guided, Text: "Replace shell parsing with a process API that accepts a fixed executable and argument vector.\n\nBefore:\nstd::system(command.c_str());\n\nAfter:\n// use the platform process API or a reviewed process library\nprocess::run(\"convert\", {user_file});"},
	"security.cpp.unsafe-c-api":                {Kind: guided, Text: "Use a bounds-aware string operation.\n\nBefore:\nstrcpy(destination, source);\n\nAfter:\nstd::string destination{source};\n// for a fixed buffer, use a checked copy that always preserves termination"},
	"security.rust.insecure-tls":               {Kind: deterministic, Text: "Remove the certificate acceptance opt-out so TLS verification stays on.\n\nBefore:\nlet client = reqwest::Client::builder()\n    .danger_accept_invalid_certs(true)\n    .build()?;\n\nAfter:\nlet client = reqwest::Client::new(); // the default client verifies certificates"},
	"security.rust.shell-execution":            {Kind: guided, Text: "Spawn the target binary directly with typed arguments instead of a shell command line.\n\nBefore:\nCommand::new(\"sh\").arg(\"-c\").arg(format!(\"convert {user_file}\")).status()?;\n\nAfter:\nCommand::new(\"convert\").arg(&user_file).status()?; // fixed binary, no shell parsing"},
	"security.java.insecure-tls":               {Kind: deterministic, Text: "Delete the permissive verifier override so hostname and certificate checks stay on.\n\nBefore:\nHttpsURLConnection.setDefaultHostnameVerifier((hostname, session) -> true);\n\nAfter:\n// no override: the default verifier validates hostnames and certificates\nHttpsURLConnection conn = (HttpsURLConnection) url.openConnection();"},
	"security.java.shell-execution":            {Kind: guided, Text: "Build the process from a fixed argv instead of a shell-parsed command string.\n\nBefore:\nRuntime.getRuntime().exec(\"convert \" + userFile);\n\nAfter:\nnew ProcessBuilder(\"convert\", userFile).start(); // fixed binary, arguments not shell-parsed"},
	"security.csharp.insecure-tls":             {Kind: deterministic, Text: "Delete the always-true certificate callback so validation stays on.\n\nBefore:\nhandler.ServerCertificateCustomValidationCallback = (msg, cert, chain, errors) => true;\n\nAfter:\nvar client = new HttpClient(); // the default handler validates certificates"},
	"security.csharp.shell-execution":          {Kind: guided, Text: "Start the target binary with an argument list instead of a shell command string.\n\nBefore:\nProcess.Start(\"cmd.exe\", \"/C convert \" + userFile);\n\nAfter:\nvar psi = new ProcessStartInfo(\"convert\") { UseShellExecute = false };\npsi.ArgumentList.Add(userFile);\nProcess.Start(psi); // fixed binary, arguments not shell-parsed"},
	"security.ruby.insecure-tls":               {Kind: deterministic, Text: "Restore peer verification instead of disabling it.\n\nBefore:\nhttp.verify_mode = OpenSSL::SSL::VERIFY_NONE\n\nAfter:\nhttp.verify_mode = OpenSSL::SSL::VERIFY_PEER # default certificate verification"},
	"security.ruby.shell-execution":            {Kind: guided, Text: "Use the argv form so arguments are never shell-interpolated.\n\nBefore:\nsystem(\"convert #{user_file}\")\n\nAfter:\nsystem(\"convert\", user_file) # argv form, no shell interpolation"},
	"security.ruby.dynamic-code":               {Kind: guided, Text: "Replace eval with a dispatch table or a data-only format.\n\nBefore:\nresult = eval(user_expression)\n\nAfter:\nhandlers = { \"sum\" => method(:sum_values), \"avg\" => method(:avg_values) }\nresult = handlers[name]&.call(values) # dispatch instead of evaluating source text"},
}
