package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var qualityErrorDefensiveCatalog = map[string]core.RuleMetadata{
	"error.logged-and-returned":             localQualityRule("error.logged-and-returned", "warn", "Logged and returned error", "Warns when the same error is logged and returned, risking duplicate logs at multiple layers.", "Log at one ownership boundary or return the wrapped error for the caller to log."),
	"error.generic-message":                 localQualityRule("error.generic-message", "warn", "Generic error message", "Warns when an error message lacks operation, resource, or decision context.", "Add operation-specific context while preserving the original error where possible."),
	"error.wrong-abstraction-level":         localQualityRule("error.wrong-abstraction-level", "warn", "Wrong abstraction level in error", "Warns when higher-level error contracts expose lower-level infrastructure details.", "Translate infrastructure failures into domain/API-level errors and retain the cause internally."),
	"error.inconsistent-wrapping":           localQualityRule("error.inconsistent-wrapping", "warn", "Inconsistent error wrapping", "Warns when a function mixes wrapped errors with bare error returns.", "Use one wrapping convention in the function so callers receive consistent context and causes."),
	"error.retryable-not-distinguished":     localQualityRule("error.retryable-not-distinguished", "warn", "Retryable failure not distinguished", "Warns when retry paths cannot distinguish transient from permanent failures.", "Return or tag retryable failures explicitly so callers can apply bounded retry policy safely."),
	"error.user-message-leaks-internals":    localQualityRule("error.user-message-leaks-internals", "warn", "User message leaks internals", "Warns when user-facing errors expose database, transport, stack, or infrastructure internals.", "Show a safe user message and keep technical diagnostics in logs or wrapped internal errors."),
	"error.partial-failure-hidden":          localQualityRule("error.partial-failure-hidden", "warn", "Partial failure hidden", "Warns when a partial failure path continues or reports success without surfacing failed work.", "Return structured partial-failure information or fail the operation explicitly."),
	"error.cleanup-error-ignored":           localQualityRule("error.cleanup-error-ignored", "warn", "Cleanup error ignored", "Warns when close, rollback, delete, or cleanup failures are discarded.", "Handle, join, or deliberately document cleanup errors instead of silently discarding them."),
	"error.panic-on-recoverable-path":       localQualityRule("error.panic-on-recoverable-path", "warn", "Panic on recoverable path", "Warns when recoverable request, validation, or I/O failures are handled with panic/throw.", "Return an explicit error/result for recoverable failures and reserve panic for programmer errors."),
	"error.exception-used-for-control-flow": localQualityRule("error.exception-used-for-control-flow", "warn", "Exception used for control flow", "Warns when exception/panic/throw is used for ordinary branch control.", "Use explicit branches or result values for expected control flow."),
	"error.fallback-hides-corruption":       localQualityRule("error.fallback-hides-corruption", "warn", "Fallback hides corruption", "Warns when fallback success after parse, corruption, or validation failure can hide bad data.", "Fail closed or return a partial/error contract that makes the corrupted input visible."),

	"defensive.unvalidated-boundary-input":  localQualityRule("defensive.unvalidated-boundary-input", "warn", "Unvalidated boundary input", "Warns when handler, API, event, or filesystem input is consumed without validation evidence.", "Validate boundary input before using it in domain logic or side effects."),
	"defensive.invalid-state-representable": localQualityRule("defensive.invalid-state-representable", "warn", "Invalid state representable", "Warns when booleans or raw status strings can represent impossible state combinations.", "Model state with an enum, sum type, or value object that makes invalid combinations unrepresentable."),
	"defensive.null-assumption":             localQualityRule("defensive.null-assumption", "warn", "Null assumption", "Warns when nullable boundary values are dereferenced without a nil/null guard.", "Check for nil/null or validate the value before dereferencing."),
	"defensive.integer-overflow":            localQualityRule("defensive.integer-overflow", "warn", "Integer overflow assumption", "Warns when arithmetic on count, size, or length input lacks an overflow bound check.", "Validate bounds or use a type wide enough for the source range before arithmetic."),
	"defensive.bounds-assumption":           localQualityRule("defensive.bounds-assumption", "warn", "Bounds assumption", "Warns when indexed access assumes collection bounds without a nearby length check.", "Check length or key existence before indexing."),
	"defensive.unsafe-default":              localQualityRule("defensive.unsafe-default", "warn", "Unsafe default", "Warns when a config/env fallback can fail open or disable a safety control.", "Choose fail-closed defaults and require explicit opt-out for safety-sensitive settings."),
	"defensive.non-exhaustive-branch":       localQualityRule("defensive.non-exhaustive-branch", "warn", "Non-exhaustive branch", "Warns when enum-like state/kind/type branching lacks default or exhaustive handling.", "Handle every known case and add a safe default or exhaustive assertion."),
	"defensive.unchecked-external-response": localQualityRule("defensive.unchecked-external-response", "warn", "Unchecked external response", "Warns when external responses are consumed without checking status, ok, or transport errors.", "Check status/error/schema before consuming response data."),
	"defensive.missing-schema-validation":   localQualityRule("defensive.missing-schema-validation", "warn", "Missing schema validation", "Warns when decoded JSON, events, or request payloads are used without schema or invariant validation.", "Validate decoded payloads with schema or domain invariant checks before use."),
	"defensive.missing-resource-limit":      localQualityRule("defensive.missing-resource-limit", "warn", "Missing resource limit", "Warns when boundary reads or uploads lack explicit size, count, or time limits.", "Apply size/count/time bounds before reading or queueing boundary input."),
	"defensive.invalid-state-transition":    localQualityRule("defensive.invalid-state-transition", "warn", "Invalid state transition", "Warns when state transitions write terminal states without checking allowed prior state.", "Validate the current state before applying transitions."),
	"defensive.fail-open-authorization":     localQualityRule("defensive.fail-open-authorization", "warn", "Fail-open authorization", "Warns when authorization failure paths default to allow or success.", "Fail closed on authorization errors and require explicit allow decisions."),
}
