package rules

import "github.com/devr-tools/codeguard/internal/codeguard/core"

var reliabilityFixTemplates = map[string]core.FixTemplate{
	"reliability.missing-timeout":           {Kind: deterministic, Text: "Bind outbound work to a deadline or timeout.\n\nBefore:\nresp, err := http.Get(url)\n\nAfter:\nctx, cancel := context.WithTimeout(ctx, 5*time.Second)\ndefer cancel()\nreq, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)\nresp, err := client.Do(req)\n// or configure http.Client{Timeout: 5 * time.Second}"},
	"reliability.unbounded-retry":           {Kind: guided, Text: "Add a bounded retry policy that stops on context cancellation.\n\nBefore:\nfor {\n\tif err := call(); err == nil { break }\n}\n\nAfter:\nfor attempt := 0; attempt < maxAttempts; attempt++ {\n\tif err := ctx.Err(); err != nil { return err }\n\tif err := call(); err == nil { return nil }\n}"},
	"reliability.retry-without-backoff":     {Kind: guided, Text: "Sleep with capped exponential backoff and jitter between attempts.\n\nBefore:\nfor attempt := 0; attempt < maxAttempts; attempt++ { _ = call() }\n\nAfter:\nfor attempt := 0; attempt < maxAttempts; attempt++ {\n\tif err := call(); err == nil { return nil }\n\ttime.Sleep(backoff.WithJitter(attempt))\n}"},
	"reliability.non-idempotent-retry":      {Kind: guided, Text: "Do not retry side effects unless the operation is idempotent.\n\nBefore:\nretry(func() error { return chargeCard(ctx, payment) })\n\nAfter:\npayment.IdempotencyKey = stableKey\nretry(func() error { return chargeCard(ctx, payment) })\n// or avoid retrying the non-idempotent side effect"},
	"reliability.missing-cancellation":      {Kind: deterministic, Text: "Propagate the caller context instead of creating a detached background context.\n\nBefore:\nreq, _ := http.NewRequestWithContext(context.Background(), method, url, body)\n\nAfter:\nreq, _ := http.NewRequestWithContext(ctx, method, url, body)"},
	"reliability.unbounded-work":            {Kind: guided, Text: "Bound fan-out with a worker pool, queue, or semaphore.\n\nBefore:\nfor _, item := range items { go process(item) }\n\nAfter:\nsem := make(chan struct{}, maxConcurrency)\nfor _, item := range items {\n\tsem <- struct{}{}\n\tgo func() { defer func(){ <-sem }(); process(item) }()\n}"},
	"reliability.missing-concurrency-limit": {Kind: guided, Text: "Put an explicit limit around concurrent work.\n\nBefore:\ng.Go(func() error { return process(item) })\n\nAfter:\ng.SetLimit(maxConcurrency)\ng.Go(func() error { return process(item) })"},
	"reliability.resource-leak":             {Kind: deterministic, Text: "Close or stop resources on every successful acquisition path.\n\nBefore:\nresp, err := client.Do(req)\nif err != nil { return err }\nreturn decode(resp.Body)\n\nAfter:\nresp, err := client.Do(req)\nif err != nil { return err }\ndefer resp.Body.Close()\nreturn decode(resp.Body)"},
	"reliability.partial-failure-hidden":    {Kind: guided, Text: "Return partial-failure evidence instead of reporting overall success.\n\nBefore:\nfor _, item := range items { _ = process(item) }\nreturn nil\n\nAfter:\nvar errs []error\nfor _, item := range items { if err := process(item); err != nil { errs = append(errs, err) } }\nreturn errors.Join(errs...)"},
	"reliability.missing-graceful-shutdown": {Kind: guided, Text: "Handle termination, stop accepting work, and drain in-flight work with a timeout.\n\nBefore:\nlog.Fatal(http.ListenAndServe(addr, mux))\n\nAfter:\nsrv := &http.Server{Addr: addr, Handler: mux}\n// start srv, listen for SIGTERM, then call srv.Shutdown(ctx) with a deadline"},
	"reliability.swallowed-error":           {Kind: deterministic, Text: "Do not discard production errors silently.\n\nBefore:\n_, _ = io.Copy(dst, src)\n\nAfter:\nif _, err := io.Copy(dst, src); err != nil {\n\treturn fmt.Errorf(\"copy payload: %w\", err)\n}"},
	"reliability.lost-error-context":        {Kind: guided, Text: "Preserve the original error and add operation context.\n\nBefore:\nif err != nil { return errors.New(\"failed\") }\n\nAfter:\nif err != nil { return fmt.Errorf(\"load account %s: %w\", accountID, err) }"},
	"reliability.recoverable-panic":         {Kind: guided, Text: "Return an error for recoverable failures instead of panicking.\n\nBefore:\nif err != nil { panic(err) }\n\nAfter:\nif err != nil { return fmt.Errorf(\"initialize worker: %w\", err) }"},
}
