package agentcontext

import (
	"bytes"
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/devr-tools/codeguard/internal/codeguard/checks/support"
	"github.com/devr-tools/codeguard/internal/codeguard/core"
)

// sourceExtensions are the file types counted toward the agent context
// budget and basename-ambiguity measurements.
var sourceExtensions = map[string]struct{}{
	".go": {}, ".py": {}, ".ts": {}, ".tsx": {}, ".js": {}, ".jsx": {},
	".mjs": {}, ".cjs": {}, ".rs": {}, ".java": {}, ".cs": {}, ".rb": {},
	".php": {}, ".kt": {}, ".kts": {}, ".swift": {}, ".scala": {},
	".c": {}, ".h": {}, ".cc": {}, ".cpp": {}, ".hpp": {}, ".m": {}, ".mm": {},
}

// vendoredSegments are path segments that mark third-party or build-output
// trees, which are not context an agent is expected to read.
var vendoredSegments = map[string]struct{}{
	"vendor": {}, "node_modules": {}, "third_party": {}, "thirdparty": {},
	".venv": {}, "venv": {}, "site-packages": {}, "bower_components": {},
	"dist": {}, "build": {}, ".next": {}, ".nuxt": {}, "__pycache__": {},
}

// generatedSuffixes are filename patterns for machine-written source.
var generatedSuffixes = []string{
	".pb.go", ".pb.gw.go", "_pb2.py", "_pb2_grpc.py",
	".gen.go", "_gen.go", "_generated.go", ".min.js", ".min.css", ".d.ts",
}

type oversizedFile struct {
	rel   string
	lines int
}

// sourceInventory is the per-target measurement pass shared by the oversized
// and ambiguous-basename rules and the legibility artifact: one walk that
// counts eligible source files, collects budget breakers, and groups files by
// basename.
type sourceInventory struct {
	files     int
	oversized []oversizedFile
	basenames map[string][]string
}

func collectSourceInventory(env support.Context, target core.TargetConfig, maxLines int) sourceInventory {
	inv := sourceInventory{basenames: map[string][]string{}}
	env.VisitTargetFiles(target, isEligibleSourcePath, func(rel string, data []byte) {
		if looksGenerated(data) {
			return
		}
		inv.files++
		if lines := env.CountLines(data); lines > maxLines {
			inv.oversized = append(inv.oversized, oversizedFile{rel: rel, lines: lines})
		}
		base := path.Base(rel)
		inv.basenames[base] = append(inv.basenames[base], rel)
	})
	return inv
}

func isEligibleSourcePath(rel string) bool {
	if _, ok := sourceExtensions[strings.ToLower(path.Ext(rel))]; !ok {
		return false
	}
	for _, suffix := range generatedSuffixes {
		if strings.HasSuffix(rel, suffix) {
			return false
		}
	}
	for _, segment := range strings.Split(path.Dir(rel), "/") {
		if _, ok := vendoredSegments[segment]; ok {
			return false
		}
	}
	return true
}

// looksGenerated sniffs the leading bytes for the conventional generated-code
// markers ("Code generated ... DO NOT EDIT", "@generated", "<auto-generated").
func looksGenerated(data []byte) bool {
	head := data
	if len(head) > 4096 {
		head = head[:4096]
	}
	return bytes.Contains(head, []byte("DO NOT EDIT")) ||
		bytes.Contains(head, []byte("@generated")) ||
		bytes.Contains(head, []byte("<auto-generated"))
}

// oversizedFindings reports source files whose size exceeds the agent
// context budget, framed as a context cost rather than a style limit.
func oversizedFindings(env support.Context, inv sourceInventory, maxLines int) []core.Finding {
	findings := make([]core.Finding, 0, len(inv.oversized))
	for _, file := range inv.oversized {
		findings = append(findings, env.NewFinding(support.FindingInput{
			RuleID: "context.oversized-context-unit",
			Level:  "warn",
			Path:   file.rel,
			Line:   1,
			Column: 1,
			Message: fmt.Sprintf("file has %d lines, exceeding the %d-line agent context budget; "+
				"a file this large crowds out the rest of an AI agent's working context — split it into smaller, focused units", file.lines, maxLines),
		}))
	}
	return findings
}

// ambiguousBasenameGroups returns basenames shared by at least threshold
// source files, with sorted locations, in deterministic basename order.
func ambiguousBasenameGroups(inv sourceInventory, threshold int) [][]string {
	names := make([]string, 0, len(inv.basenames))
	for name, locations := range inv.basenames {
		if len(locations) >= threshold {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	groups := make([][]string, 0, len(names))
	for _, name := range names {
		locations := append([]string(nil), inv.basenames[name]...)
		sort.Strings(locations)
		groups = append(groups, locations)
	}
	return groups
}

// ambiguousBasenameFindings emits one finding per over-shared basename,
// listing up to five locations.
func ambiguousBasenameFindings(env support.Context, inv sourceInventory, threshold int) []core.Finding {
	groups := ambiguousBasenameGroups(inv, threshold)
	findings := make([]core.Finding, 0, len(groups))
	for _, locations := range groups {
		shown := locations
		suffix := ""
		if len(shown) > 5 {
			suffix = fmt.Sprintf(" and %d more", len(shown)-5)
			shown = shown[:5]
		}
		findings = append(findings, env.NewFinding(support.FindingInput{
			RuleID: "context.ambiguous-symbol",
			Level:  "warn",
			Path:   locations[0],
			Message: fmt.Sprintf("%d files share the basename %q (%s%s); duplicated basenames defeat filename search and grep-based navigation for AI agents — prefer distinct, descriptive file names",
				len(locations), path.Base(locations[0]), strings.Join(shown, ", "), suffix),
		}))
	}
	return findings
}
