package checks_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/devr-tools/codeguard/pkg/codeguard"
)

func TestRustToolchainDeadCodeIsOptIn(t *testing.T) {
	dir := t.TempDir()
	writeRustToolchainCrate(t, dir)
	installFakeCargo(t, `{"reason":"compiler-message","message":{"level":"error","message":"function `+"`unused_private`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"src/lib.rs","line_start":3,"column_start":4,"is_primary":true}]}}`)

	report := runScan(t, rustToolchainDeadCodeConfig(dir, false))

	assertFindingRuleAbsent(t, report, "Code Quality", goToolchainDeadCodeRuleID)
}

func TestRustToolchainDeadCodeReportsCargoDeadCodeDiagnostics(t *testing.T) {
	dir := t.TempDir()
	writeRustToolchainCrate(t, dir)
	installFakeCargo(t, `{"reason":"compiler-message","message":{"level":"error","message":"function `+"`unused_private`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"src/lib.rs","line_start":3,"column_start":4,"is_primary":true}]}}
{"reason":"compiler-message","message":{"level":"error","message":"function `+"`exported_api`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"src/lib.rs","line_start":5,"column_start":1,"is_primary":true}]}}
{"reason":"compiler-message","message":{"level":"warning","message":"unused variable","code":{"code":"unused_variables"},"spans":[{"file_name":"src/lib.rs","line_start":7,"column_start":9,"is_primary":true}]}}`)

	report := runScan(t, rustToolchainDeadCodeConfig(dir, true))
	findings := findingsForRule(report, goToolchainDeadCodeRuleID)

	if len(findings) != 1 {
		t.Fatalf("toolchain dead-code findings = %d, want 1: %+v", len(findings), findings)
	}
	if findings[0].Path != "src/lib.rs" || findings[0].Line != 3 {
		t.Fatalf("finding = %+v, want private src/lib.rs:3 diagnostic", findings[0])
	}
}

func TestRustToolchainDeadCodeReportsArtifactReachability(t *testing.T) {
	dir := t.TempDir()
	writeRustToolchainCrate(t, dir)
	writeFile(t, filepath.Join(dir, ".codeguard", "rust-symbols.txt"), `00000000 T rust_dead_code_test::used
`)
	installFakeCargoSuccess(t)

	cfg := rustToolchainDeadCodeConfig(dir, true)
	cfg.Checks.QualityRules.DeadCode.Rust.Reports = []string{".codeguard/rust-symbols.txt"}
	report := runScan(t, cfg)
	findings := findingsForRule(report, goToolchainDeadCodeRuleID)

	if len(findings) != 1 {
		t.Fatalf("toolchain dead-code findings = %d, want 1: %+v", len(findings), findings)
	}
	if findings[0].Path != "src/lib.rs" || findings[0].Line != 3 {
		t.Fatalf("finding = %+v, want artifact finding for src/lib.rs:3", findings[0])
	}
	if findings[0].Metadata["evidence"] != "artifact-symbol-report" {
		t.Fatalf("metadata = %+v, want artifact evidence", findings[0].Metadata)
	}
}

func TestRustToolchainDeadCodeAvoidsRealWorldFalsePositiveSurfaces(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "Cargo.toml"), `[package]
name = "rust-dead-code-test"
version = "0.1.0"
edition = "2021"
`)
	writeFile(t, filepath.Join(dir, "src", "lib.rs"), `pub fn exported_api() {}

#[no_mangle]
pub extern "C" fn ffi_entrypoint() {}

#[cfg(test)]
fn test_helper() {}

trait Handler { fn handle(&self); }
struct Job;
impl Handler for Job {
    fn handle(&self) {}
}














fn truly_unused() {}
`)
	writeFile(t, filepath.Join(dir, "src", "registry.rs"), `inventory::submit! {
    Plugin::new()
}

fn registered_plugin() {}
`)
	writeFile(t, filepath.Join(dir, "generated", "bindings.rs"), `// Code generated by bindgen. DO NOT EDIT.
fn generated_helper() {}
`)
	writeFile(t, filepath.Join(dir, "vendor", "ffi.rs"), `fn vendor_helper() {}
`)
	writeFile(t, filepath.Join(dir, "tests", "integration.rs"), `fn integration_helper() {}
`)
	writeFile(t, filepath.Join(dir, "examples", "demo.rs"), `fn example_helper() {}
`)
	writeFile(t, filepath.Join(dir, "benches", "bench.rs"), `fn bench_helper() {}
`)
	installFakeCargo(t, `{"reason":"compiler-message","message":{"level":"error","message":"function `+"`exported_api`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"src/lib.rs","line_start":1,"column_start":1,"is_primary":true}]}}
{"reason":"compiler-message","message":{"level":"error","message":"function `+"`ffi_entrypoint`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"src/lib.rs","line_start":4,"column_start":1,"is_primary":true}]}}
{"reason":"compiler-message","message":{"level":"error","message":"function `+"`test_helper`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"src/lib.rs","line_start":7,"column_start":1,"is_primary":true}]}}
{"reason":"compiler-message","message":{"level":"error","message":"method `+"`handle`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"src/lib.rs","line_start":12,"column_start":5,"is_primary":true}]}}
{"reason":"compiler-message","message":{"level":"error","message":"function `+"`truly_unused`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"src/lib.rs","line_start":28,"column_start":1,"is_primary":true}]}}
{"reason":"compiler-message","message":{"level":"error","message":"function `+"`registered_plugin`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"src/registry.rs","line_start":5,"column_start":1,"is_primary":true}]}}
{"reason":"compiler-message","message":{"level":"error","message":"function `+"`generated_helper`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"generated/bindings.rs","line_start":2,"column_start":1,"is_primary":true}]}}
{"reason":"compiler-message","message":{"level":"error","message":"function `+"`vendor_helper`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"vendor/ffi.rs","line_start":1,"column_start":1,"is_primary":true}]}}
{"reason":"compiler-message","message":{"level":"error","message":"function `+"`integration_helper`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"tests/integration.rs","line_start":1,"column_start":1,"is_primary":true}]}}
{"reason":"compiler-message","message":{"level":"error","message":"function `+"`example_helper`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"examples/demo.rs","line_start":1,"column_start":1,"is_primary":true}]}}
{"reason":"compiler-message","message":{"level":"error","message":"function `+"`bench_helper`"+` is never used","code":{"code":"dead_code"},"spans":[{"file_name":"benches/bench.rs","line_start":1,"column_start":1,"is_primary":true}]}}`)

	report := runScan(t, rustToolchainDeadCodeConfig(dir, true))
	findings := findingsForRule(report, goToolchainDeadCodeRuleID)

	if len(findings) != 1 {
		t.Fatalf("toolchain dead-code findings = %d, want 1: %+v", len(findings), findings)
	}
	if findings[0].Path != "src/lib.rs" || findings[0].Line != 28 {
		t.Fatalf("finding = %+v, want only private src/lib.rs:28 diagnostic", findings[0])
	}
}

func writeRustToolchainCrate(t *testing.T, dir string) {
	t.Helper()
	writeFile(t, filepath.Join(dir, "Cargo.toml"), `[package]
name = "rust-dead-code-test"
version = "0.1.0"
edition = "2021"
`)
	writeFile(t, filepath.Join(dir, "src", "lib.rs"), `pub fn used() {}

fn unused_private() {}

pub fn exported_api() {}
`)
}

func rustToolchainDeadCodeConfig(dir string, enabled bool) codeguard.Config {
	cfg := codeguard.ExampleConfig()
	cfg.Name = "rust-toolchain-dead-code-test"
	cfg.Targets = []codeguard.TargetConfig{{Name: "repo", Path: dir, Language: "rust"}}
	cfg.Checks.Quality = true
	cfg.Checks.Design = false
	cfg.Checks.Security = false
	cfg.Checks.Prompts = false
	cfg.Checks.CI = false
	cfg.Checks.Performance = boolValue(false)
	cfg.Checks.SupplyChain = false
	cfg.Checks.Delivery = boolValue(false)
	cfg.Checks.Reliability = boolValue(false)
	cfg.Checks.Data = boolValue(false)
	cfg.Checks.Observability = boolValue(false)
	cfg.Checks.Operations = boolValue(false)
	cfg.Checks.Change = boolValue(false)
	cfg.Checks.Contracts = boolValue(false)
	cfg.Checks.Context = boolValue(false)
	cfg.Checks.QualityRules.AIChecks.DeadCode = boolValue(false)
	cfg.Cache.Enabled = boolValue(false)
	if enabled {
		cfg.Checks.QualityRules.DeadCode.Enabled = boolValue(true)
		cfg.Checks.QualityRules.DeadCode.Mode = "toolchain"
		cfg.Checks.QualityRules.DeadCode.Level = "warn"
	}
	return cfg
}

func installFakeCargo(t *testing.T, output string) {
	t.Helper()
	binDir := t.TempDir()
	writeExecutableFile(t, filepath.Join(binDir, "cargo"), "#!/bin/sh\ncat <<'JSON'\n"+output+"\nJSON\nexit 1\n")
	t.Setenv("PATH", binDir+string(os.PathListSeparator)+os.Getenv("PATH"))
}

func installFakeCargoSuccess(t *testing.T) {
	t.Helper()
	binDir := t.TempDir()
	writeExecutableFile(t, filepath.Join(binDir, "cargo"), "#!/bin/sh\nexit 0\n")
	t.Setenv("PATH", binDir+string(os.PathListSeparator)+os.Getenv("PATH"))
}
