package checks_test

import (
	"path/filepath"
	"strings"
	"testing"
)

var workstreamERules = []string{
	"error.logged-and-returned",
	"error.logged-and-ignored",
	"error.context-lost",
	"error.generic-message",
	"error.wrong-abstraction-level",
	"error.inconsistent-wrapping",
	"error.retryable-not-distinguished",
	"error.user-message-leaks-internals",
	"error.partial-failure-hidden",
	"error.cleanup-error-ignored",
	"error.panic-on-recoverable-path",
	"error.exception-used-for-control-flow",
	"error.fallback-hides-corruption",
	"defensive.unvalidated-boundary-input",
	"defensive.invalid-state-representable",
	"defensive.null-assumption",
	"defensive.unchecked-type-assertion",
	"defensive.unsafe-numeric-conversion",
	"defensive.integer-overflow",
	"defensive.bounds-assumption",
	"defensive.unsafe-default",
	"defensive.non-exhaustive-branch",
	"defensive.unchecked-external-response",
	"defensive.missing-schema-validation",
	"defensive.missing-resource-limit",
	"defensive.invalid-state-transition",
	"defensive.fail-open-authorization",
}

// codeguard:ignore quality.max-function-lines until 2026-12-31 -- multi-language fixture matrix kept inline for focused detector coverage.
func TestQualityErrorContractsDetectMultiLanguageSignals(t *testing.T) {
	tests := []struct {
		name     string
		language string
		file     string
		source   string
		rules    []string
	}{
		{
			name:     "go",
			language: "go",
			file:     "errors.go",
			source: strings.Join([]string{
				"package sample",
				"",
				"import (",
				"\t\"encoding/json\"",
				"\t\"errors\"",
				"\t\"fmt\"",
				"\t\"log\"",
				")",
				"",
				"type rowsHandle struct{}",
				"func (rowsHandle) Close() error { return nil }",
				"",
				"func SaveProfile(id string) error {",
				"\tif err := writeProfile(id); err != nil {",
				"\t\tlog.Printf(\"save profile: %v\", err)",
				"\t\treturn err",
				"\t}",
				"\treturn nil",
				"}",
				"",
				"func LoadProfile(id string) error {",
				"\tif err := readProfile(id); err != nil {",
				"\t\treturn err",
				"\t}",
				"\tif err := writeProfile(id); err != nil {",
				"\t\treturn fmt.Errorf(\"write profile: %w\", err)",
				"\t}",
				"\treturn errors.New(\"failed\")",
				"}",
				"",
				"func CheckoutHandler() error {",
				"\treturn errors.New(\"postgres sql constraint failed\")",
				"}",
				"",
				"func CloseRows(rows rowsHandle) error {",
				"\tdefer rows.Close()",
				"\treturn nil",
				"}",
				"",
				"func ProcessAll(items []string) ([]string, error) {",
				"\tprocessed := make([]string, 0, len(items))",
				"\tfor _, item := range items {",
				"\t\tif err := sendItem(item); err != nil {",
				"\t\t\tcontinue",
				"\t\t}",
				"\t\tprocessed = append(processed, item)",
				"\t}",
				"\treturn processed, nil",
				"}",
				"",
				"func DecodeConfig(raw []byte) map[string]string {",
				"\tvar out map[string]string",
				"\tif err := json.Unmarshal(raw, &out); err != nil {",
				"\t\treturn map[string]string{}",
				"\t}",
				"\treturn out",
				"}",
				"",
				"func RetryCall() error {",
				"\tfor attempt := 0; attempt < 3; attempt++ {",
				"\t\tif err := callRemote(); err != nil {",
				"\t\t\tretryLater()",
				"\t\t}",
				"\t}",
				"\treturn errors.New(\"failed\")",
				"}",
				"",
				"func HandleRequest(input string) {",
				"\tif input == \"\" {",
				"\t\tpanic(\"invalid request\")",
				"\t}",
				"}",
				"",
				"func writeProfile(string) error { return nil }",
				"func readProfile(string) error { return nil }",
				"func sendItem(string) error { return nil }",
				"func callRemote() error { return nil }",
				"func retryLater() {}",
				"",
			}, "\n"),
			rules: []string{
				"error.logged-and-returned",
				"error.context-lost",
				"error.generic-message",
				"error.wrong-abstraction-level",
				"error.inconsistent-wrapping",
				"error.retryable-not-distinguished",
				"error.user-message-leaks-internals",
				"error.partial-failure-hidden",
				"error.cleanup-error-ignored",
				"error.panic-on-recoverable-path",
				"error.fallback-hides-corruption",
			},
		},
		{
			name:     "python",
			language: "python",
			file:     "errors.py",
			source: strings.Join([]string{
				"import json",
				"import logging",
				"",
				"def load_profile(profile_id):",
				"    try:",
				"        return read_profile(profile_id)",
				"    except Exception as err:",
				"        logging.error('load failed %s', err)",
				"        return None",
				"",
				"def retry_call(client):",
				"    for attempt in range(3):",
				"        try:",
				"            return client.call()",
				"        except Exception as err:",
				"            retry_again()",
				"    raise Exception('failed')",
				"",
				"def find_user(user_id):",
				"    if not user_id:",
				"        raise Exception('not found')",
				"    return user_id",
				"",
				"def decode_config(raw):",
				"    try:",
				"        return json.loads(raw)",
				"    except Exception:",
				"        return {}",
				"",
				"def process_all(items):",
				"    for item in items:",
				"        try:",
				"            send_item(item)",
				"        except Exception:",
				"            continue",
				"    return []",
				"",
			}, "\n"),
			rules: []string{
				"error.logged-and-ignored",
				"error.generic-message",
				"error.retryable-not-distinguished",
				"error.partial-failure-hidden",
				"error.exception-used-for-control-flow",
				"error.fallback-hides-corruption",
			},
		},
		{
			name:     "typescript",
			language: "typescript",
			file:     "errors.ts",
			source: strings.Join([]string{
				"export function checkoutHandler(): Error {",
				"  return new Error('sql database failed');",
				"}",
				"",
				"export function parseControl(value: string): string {",
				"  if (value === 'stop') {",
				"    throw new Error('stop');",
				"  }",
				"  return value;",
				"}",
				"",
				"export function batch(tasks: Promise<unknown>[]) {",
				"  const result = Promise.allSettled(tasks);",
				"  return result;",
				"}",
				"",
			}, "\n"),
			rules: []string{
				"error.wrong-abstraction-level",
				"error.user-message-leaks-internals",
				"error.exception-used-for-control-flow",
				"error.partial-failure-hidden",
			},
		},
		{
			name:     "cpp",
			language: "cpp",
			file:     "errors.cpp",
			source: strings.Join([]string{
				"#include <stdexcept>",
				"#include <string>",
				"",
				"std::string HandleApi() {",
				"  return std::runtime_error(\"redis connection refused\").what();",
				"}",
				"",
				"std::string parseControl(std::string value) {",
				"  if (value == \"missing\") {",
				"    throw std::runtime_error(\"missing\");",
				"  }",
				"  return value;",
				"}",
				"",
			}, "\n"),
			rules: []string{
				"error.wrong-abstraction-level",
				"error.user-message-leaks-internals",
				"error.exception-used-for-control-flow",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			writeFile(t, filepath.Join(dir, tt.file), tt.source)

			report := runQualityPrecisionScan(t, qualityPrecisionConfigForLanguage(dir, tt.language))

			for _, ruleID := range tt.rules {
				assertFindingRulePresent(t, report, "Code Quality", ruleID)
			}
		})
	}
}

// codeguard:ignore quality.max-function-lines until 2026-12-31 -- multi-language fixture matrix kept inline for focused detector coverage.
func TestQualityDefensiveBoundariesDetectMultiLanguageSignals(t *testing.T) {
	tests := []struct {
		name     string
		language string
		file     string
		source   string
		rules    []string
	}{
		{
			name:     "go",
			language: "go",
			file:     "defensive.go",
			source: strings.Join([]string{
				"package sample",
				"",
				"import (",
				"\t\"encoding/json\"",
				"\t\"io\"",
				"\t\"net/http\"",
				"\t\"os\"",
				")",
				"",
				"type DeploymentState struct {",
				"\tIsActive bool",
				"\tIsDeleted bool",
				"}",
				"",
				"type Request struct { Body Body }",
				"type Body struct { ID string }",
				"type User struct { Name string }",
				"type OrderStatus string",
				"type Order struct { Status OrderStatus }",
				"",
				"func HandleUser(req Request) string {",
				"\treturn req.Body.ID",
				"}",
				"",
				"func RenderUser(user *User) string {",
				"\treturn user.Name",
				"}",
				"",
				"func First(items []string) string {",
				"\treturn items[0]",
				"}",
				"",
				"func Allocate(count int) []byte {",
				"\ttotalBytes := count * 4096",
				"\treturn make([]byte, totalBytes)",
				"}",
				"",
				"func AllowByDefault() bool {",
				"\treturn os.Getenv(\"AUTHZ_DISABLED\") != \"false\"",
				"}",
				"",
				"func Label(status string) string {",
				"\tswitch status {",
				"\tcase \"new\":",
				"\t\treturn \"new\"",
				"\t}",
				"\treturn \"\"",
				"}",
				"",
				"func Fetch(url string) string {",
				"\tresp, _ := http.Get(url)",
				"\tbody, _ := io.ReadAll(resp.Body)",
				"\treturn string(body)",
				"}",
				"",
				"func Decode(raw []byte) map[string]string {",
				"\tvar payload map[string]string",
				"\tjson.Unmarshal(raw, &payload)",
				"\treturn payload",
				"}",
				"",
				"func Promote(order *Order) {",
				"\torder.Status = \"paid\"",
				"}",
				"",
				"func CanAccess(user string) bool {",
				"\tif err := authorize(user); err != nil {",
				"\t\treturn true",
				"\t}",
				"\treturn true",
				"}",
				"",
				"func DecodeValue(value any) string {",
				"\treturn value.(string)",
				"}",
				"",
				"func Narrow(count int64) int32 {",
				"\treturn int32(count)",
				"}",
				"",
				"func authorize(string) error { return nil }",
				"",
			}, "\n"),
			rules: []string{
				"defensive.unvalidated-boundary-input",
				"defensive.invalid-state-representable",
				"defensive.null-assumption",
				"defensive.unchecked-type-assertion",
				"defensive.unsafe-numeric-conversion",
				"defensive.integer-overflow",
				"defensive.bounds-assumption",
				"defensive.unsafe-default",
				"defensive.non-exhaustive-branch",
				"defensive.unchecked-external-response",
				"defensive.missing-schema-validation",
				"defensive.missing-resource-limit",
				"defensive.invalid-state-transition",
				"defensive.fail-open-authorization",
			},
		},
		{
			name:     "python",
			language: "python",
			file:     "defensive.py",
			source: strings.Join([]string{
				"import json",
				"import os",
				"import requests",
				"from typing import Optional",
				"",
				"class SessionState:",
				"    is_active: bool",
				"    is_deleted: bool",
				"",
				"def handle_event(event):",
				"    return event['user']['id']",
				"",
				"def render_user(user: Optional[User]):",
				"    return user.name",
				"",
				"def first(items):",
				"    return items[0]",
				"",
				"def allocate(count):",
				"    total_bytes = count * 4096",
				"    return bytearray(total_bytes)",
				"",
				"def allow_by_default():",
				"    return os.environ.get('AUTHZ_DISABLED', 'true')",
				"",
				"def fetch(url):",
				"    response = requests.get(url)",
				"    return response.json()",
				"",
				"def decode(raw):",
				"    return json.loads(raw)",
				"",
			}, "\n"),
			rules: []string{
				"defensive.unvalidated-boundary-input",
				"defensive.invalid-state-representable",
				"defensive.null-assumption",
				"defensive.integer-overflow",
				"defensive.bounds-assumption",
				"defensive.unsafe-default",
				"defensive.unchecked-external-response",
				"defensive.missing-schema-validation",
			},
		},
		{
			name:     "typescript",
			language: "typescript",
			file:     "defensive.ts",
			source: strings.Join([]string{
				"interface SessionState { isActive: boolean; isDeleted: boolean }",
				"interface User { name: string }",
				"",
				"export function handleUser(req: any) {",
				"  const payload = JSON.parse(req.body);",
				"  return payload.user.id;",
				"}",
				"",
				"export function loadUserName(user: User | null): string {",
				"  return user.name;",
				"}",
				"",
				"export function first(items: string[]): string {",
				"  return items[0];",
				"}",
				"",
				"export function allocate(count: number): Uint8Array {",
				"  const totalBytes = count * 4096;",
				"  return new Uint8Array(totalBytes);",
				"}",
				"",
				"export function allowByDefault(): string {",
				"  return process.env.AUTHZ_DISABLED || 'true';",
				"}",
				"",
				"export function label(status: string): string {",
				"  switch (status) {",
				"    case 'new': return 'new';",
				"  }",
				"  return '';",
				"}",
				"",
				"export function fetchUser(url: string) {",
				"  const response = fetch(url);",
				"  return response.json();",
				"}",
				"",
				"export function canAccess(user: User): boolean {",
				"  try { return policy(user); } catch (error) { return true; }",
				"}",
				"",
			}, "\n"),
			rules: []string{
				"defensive.unvalidated-boundary-input",
				"defensive.invalid-state-representable",
				"defensive.null-assumption",
				"defensive.integer-overflow",
				"defensive.bounds-assumption",
				"defensive.unsafe-default",
				"defensive.non-exhaustive-branch",
				"defensive.unchecked-external-response",
				"defensive.missing-schema-validation",
				"defensive.fail-open-authorization",
			},
		},
		{
			name:     "javascript",
			language: "javascript",
			file:     "defensive.js",
			source: strings.Join([]string{
				"export function handleUser(req) {",
				"  const payload = JSON.parse(req.body);",
				"  return payload.user.id;",
				"}",
				"",
				"export function first(items) { return items[0]; }",
				"export function allocate(count) { const totalBytes = count * 4096; return new Uint8Array(totalBytes); }",
				"export function allowByDefault() { return process.env.AUTHZ_DISABLED || 'true'; }",
				"",
				"export function fetchUser(url) {",
				"  const response = fetch(url);",
				"  return response.json();",
				"}",
				"",
			}, "\n"),
			rules: []string{
				"defensive.unvalidated-boundary-input",
				"defensive.integer-overflow",
				"defensive.bounds-assumption",
				"defensive.unsafe-default",
				"defensive.unchecked-external-response",
				"defensive.missing-schema-validation",
			},
		},
		{
			name:     "cpp",
			language: "cpp",
			file:     "defensive.cpp",
			source: strings.Join([]string{
				"#include <string>",
				"#include <vector>",
				"",
				"struct SessionState { bool active; bool deleted; };",
				"struct User { std::string name; };",
				"struct Order { std::string state; };",
				"",
				"std::string renderUser(User* user) {",
				"  return user->name;",
				"}",
				"",
				"std::string first(std::vector<std::string> items) {",
				"  return items[0];",
				"}",
				"",
				"std::vector<char> allocate(int count) {",
				"  int totalBytes = count * 4096;",
				"  return std::vector<char>(totalBytes);",
				"}",
				"",
				"std::string fetchUser(std::string url) {",
				"  auto response = http_client.get(url);",
				"  return response.body;",
				"}",
				"",
				"void promote(Order* order) {",
				"  order->state = \"paid\";",
				"}",
				"",
			}, "\n"),
			rules: []string{
				"defensive.invalid-state-representable",
				"defensive.null-assumption",
				"defensive.integer-overflow",
				"defensive.bounds-assumption",
				"defensive.unchecked-external-response",
				"defensive.invalid-state-transition",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			writeFile(t, filepath.Join(dir, tt.file), tt.source)

			report := runQualityPrecisionScan(t, qualityPrecisionConfigForLanguage(dir, tt.language))

			for _, ruleID := range tt.rules {
				assertFindingRulePresent(t, report, "Code Quality", ruleID)
			}
		})
	}
}

// codeguard:ignore quality.max-function-lines until 2026-12-31 -- multi-language fixture matrix kept inline for focused detector coverage.
func TestQualityErrorAndDefensiveRulesAllowGuardedPatterns(t *testing.T) {
	tests := []struct {
		name     string
		language string
		file     string
		source   string
	}{
		{
			name:     "go",
			language: "go",
			file:     "safe.go",
			source: strings.Join([]string{
				"package sample",
				"",
				"import (",
				"\t\"encoding/json\"",
				"\t\"fmt\"",
				"\t\"io\"",
				"\t\"net/http\"",
				")",
				"",
				"type User struct { Name string }",
				"type OrderStatus string",
				"type Order struct { Status OrderStatus }",
				"type Request struct { Body Body }",
				"type Body struct { ID string }",
				"",
				"func HandleUser(req Request) (string, error) {",
				"\tif err := validate(req); err != nil { return \"\", fmt.Errorf(\"validate request: %w\", err) }",
				"\treturn req.Body.ID, nil",
				"}",
				"",
				"func RenderUser(user *User) (string, error) {",
				"\tif user == nil { return \"\", fmt.Errorf(\"user required\") }",
				"\treturn user.Name, nil",
				"}",
				"",
				"func First(items []string) (string, error) {",
				"\tif len(items) == 0 { return \"\", fmt.Errorf(\"items required\") }",
				"\treturn items[0], nil",
				"}",
				"",
				"func Fetch(url string) ([]byte, error) {",
				"\tresp, err := http.Get(url)",
				"\tif err != nil { return nil, fmt.Errorf(\"fetch profile: %w\", err) }",
				"\tif resp.StatusCode >= 400 { return nil, fmt.Errorf(\"fetch profile status %d\", resp.StatusCode) }",
				"\treturn io.ReadAll(io.LimitReader(resp.Body, 1024))",
				"}",
				"",
				"func Decode(raw []byte) (map[string]string, error) {",
				"\tvar payload map[string]string",
				"\tif err := json.Unmarshal(raw, &payload); err != nil { return nil, fmt.Errorf(\"decode payload: %w\", err) }",
				"\tif err := validate(payload); err != nil { return nil, err }",
				"\treturn payload, nil",
				"}",
				"",
				"func Promote(order *Order) error {",
				"\tif order == nil { return fmt.Errorf(\"order required\") }",
				"\tif !canTransition(order.Status, \"paid\") { return fmt.Errorf(\"invalid transition from %s\", order.Status) }",
				"\torder.Status = \"paid\"",
				"\treturn nil",
				"}",
				"",
				"func CanAccess(user string) bool {",
				"\tif err := authorize(user); err != nil { return false }",
				"\treturn true",
				"}",
				"",
				"func validate(any) error { return nil }",
				"func canTransition(OrderStatus, string) bool { return true }",
				"func authorize(string) error { return nil }",
				"",
			}, "\n"),
		},
		{
			name:     "python",
			language: "python",
			file:     "safe.py",
			source: strings.Join([]string{
				"import json",
				"import requests",
				"from typing import Optional",
				"",
				"class SessionState:",
				"    status: SessionStatus",
				"",
				"def handle_event(event):",
				"    validate(event)",
				"    return event['user']['id']",
				"",
				"def render_user(user: Optional[User]):",
				"    if user is None:",
				"        raise ValueError('user required')",
				"    return user.name",
				"",
				"def first(items):",
				"    if len(items) == 0:",
				"        raise ValueError('items required')",
				"    return items[0]",
				"",
				"def fetch(url):",
				"    response = requests.get(url)",
				"    response.raise_for_status()",
				"    return response.json()",
				"",
				"def decode(raw):",
				"    payload = json.loads(raw)",
				"    validate_schema(payload)",
				"    return payload",
				"",
			}, "\n"),
		},
		{
			name:     "typescript",
			language: "typescript",
			file:     "safe.ts",
			source: strings.Join([]string{
				"interface User { name: string }",
				"export function handleUser(req: Request) { validate(req); return req; }",
				"export function renderUser(user: User | null): string { if (user === null) { throw new Error('user required'); } return user.name; }",
				"export function first(items: string[]): string { if (items.length === 0) { throw new Error('items required'); } return items[0]; }",
				"export async function fetchUser(url: string) { const response = await fetch(url); if (!response.ok) { throw new Error('fetch user failed'); } return response.json(); }",
				"export function decode(raw: string) { const payload = JSON.parse(raw); validateSchema(payload); return payload; }",
				"export function canAccess(user: User): boolean { try { return policy(user); } catch (error) { return false; } }",
				"",
			}, "\n"),
		},
		{
			name:     "javascript",
			language: "javascript",
			file:     "safe.js",
			source: strings.Join([]string{
				"export function handleUser(req) { validate(req); return req.body.id; }",
				"export function first(items) { if (items.length === 0) { throw new Error('items required'); } return items[0]; }",
				"export async function fetchUser(url) { const response = await fetch(url); if (!response.ok) { throw new Error('fetch user failed'); } return response.json(); }",
				"export function decode(raw) { const payload = JSON.parse(raw); validateSchema(payload); return payload; }",
				"",
			}, "\n"),
		},
		{
			name:     "cpp",
			language: "cpp",
			file:     "safe.cpp",
			source: strings.Join([]string{
				"#include <stdexcept>",
				"#include <string>",
				"#include <vector>",
				"struct User { std::string name; };",
				"std::string renderUser(User* user) { if (user == nullptr) { throw std::runtime_error(\"user required\"); } return user->name; }",
				"std::string first(std::vector<std::string> items) { if (items.empty()) { throw std::runtime_error(\"items required\"); } return items[0]; }",
				"int allocate(int count) { if (count > safeint_limit()) { throw std::runtime_error(\"count too large\"); } return count * 4096; }",
				"",
			}, "\n"),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			dir := t.TempDir()
			writeFile(t, filepath.Join(dir, tt.file), tt.source)

			report := runQualityPrecisionScan(t, qualityPrecisionConfigForLanguage(dir, tt.language))

			for _, ruleID := range workstreamERules {
				assertFindingRuleAbsent(t, report, "Code Quality", ruleID)
			}
		})
	}
}
