package checks_test

import (
	"context"
	"path/filepath"
	"testing"

	"github.com/devr-tools/codeguard/pkg/codeguard"
)

func TestPythonToolchainDeadCodeReportsUnreachableModules(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "app", "__init__.py"), "")
	writeFile(t, filepath.Join(dir, "app", "__main__.py"), `from app.live import run

run()
`)
	writeFile(t, filepath.Join(dir, "app", "live.py"), `def run():
    return "ok"
`)
	writeFile(t, filepath.Join(dir, "app", "orphan.py"), `def cleanup():
    return "legacy"
`)

	report := runPythonToolchainDeadCodeScan(t, dir, true)

	assertToolchainDeadCodePath(t, report, "app/orphan.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/live.py")
}

func TestPythonToolchainDeadCodeAvoidsKnownFalsePositives(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "app", "__init__.py"), "")
	writeFile(t, filepath.Join(dir, "app", "__main__.py"), `from app.live import run

run()
`)
	writeFile(t, filepath.Join(dir, "app", "live.py"), `def run():
    return "ok"
`)
	writeFile(t, filepath.Join(dir, "app", "dynamic.py"), `import importlib

handler = importlib.import_module("app.handlers")
`)
	writeFile(t, filepath.Join(dir, "app", "routes.py"), `@app.route("/health")
def health():
    return "ok"
`)
	writeFile(t, filepath.Join(dir, "tests", "test_helpers.py"), `def test_only_helper():
    return "test"
`)
	writeFile(t, filepath.Join(dir, "app", "generated.py"), `# Code generated by test fixture. DO NOT EDIT.
def generated_helper():
    return "generated"
`)
	writeFile(t, filepath.Join(dir, "app", "ignored", "legacy.py"), `def ignored():
    return "ignored"
`)

	report := runPythonToolchainDeadCodeScanWithConfig(t, dir, true, func(cfg *codeguard.Config) {
		cfg.Checks.QualityRules.DeadCode.Python.IgnorePaths = []string{"app/ignored/**"}
	})

	assertFindingRuleAbsent(t, report, "Code Quality", "quality.dead-code.toolchain")
}

func TestPythonToolchainDeadCodeDiscoversPyprojectScripts(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "pyproject.toml"), `[project.scripts]
serve = "app.cli:main"
`)
	writeFile(t, filepath.Join(dir, "app", "__init__.py"), "")
	writeFile(t, filepath.Join(dir, "app", "cli.py"), `from app.live import run

def main():
    return run()
`)
	writeFile(t, filepath.Join(dir, "app", "live.py"), `from app.loader import load

def run():
    return load("plugins").activate()
`)
	writeFile(t, filepath.Join(dir, "app", "orphan.py"), `def cleanup():
    return "legacy"
`)

	report := runPythonToolchainDeadCodeScanWithConfig(t, dir, true, func(cfg *codeguard.Config) {
		cfg.Targets[0].Entrypoints = nil
	})

	assertToolchainDeadCodePath(t, report, "app/orphan.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/cli.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/live.py")
}

func TestPythonToolchainDeadCodeTreatsDynamicImportsExportsAndFrameworkFilesAsLive(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "setup.cfg"), `[options.entry_points]
console_scripts =
    worker = app.loader:main
`)
	writeFile(t, filepath.Join(dir, "app", "__init__.py"), `from . import public

__all__ = ["public"]
`)
	writeFile(t, filepath.Join(dir, "app", "loader.py"), `import importlib

def main():
    return importlib.import_module("app.plugin")
`)
	writeFile(t, filepath.Join(dir, "app", "plugin.py"), `def activate():
    return "plugin"
`)
	writeFile(t, filepath.Join(dir, "app", "public.py"), `def facade():
    return "public"
`)
	writeFile(t, filepath.Join(dir, "app", "views.py"), `from django.urls import path

urlpatterns = [path("health", lambda request: "ok")]
`)
	writeFile(t, filepath.Join(dir, "app", "orphan.py"), `def cleanup():
    return "legacy"
`)

	report := runPythonToolchainDeadCodeScanWithConfig(t, dir, true, func(cfg *codeguard.Config) {
		cfg.Targets[0].Entrypoints = nil
	})

	assertToolchainDeadCodePath(t, report, "app/orphan.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/loader.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/plugin.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/public.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/views.py")
}

func TestPythonToolchainDeadCodeTreatsUnknownDynamicImportsAsPackageLive(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "app", "__init__.py"), "")
	writeFile(t, filepath.Join(dir, "app", "__main__.py"), `from app.loader import run

run("plugin")
`)
	writeFile(t, filepath.Join(dir, "app", "loader.py"), `import importlib

def run(name):
    return importlib.import_module (name)
`)
	writeFile(t, filepath.Join(dir, "app", "plugin.py"), `def activate():
    return "loaded dynamically"
`)
	writeFile(t, filepath.Join(dir, "app", "legacy.py"), `def cleanup():
    return "maybe plugin"
`)

	report := runPythonToolchainDeadCodeScan(t, dir, true)

	assertFindingRuleAbsent(t, report, "Code Quality", "quality.dead-code.toolchain")
}

func TestPythonToolchainDeadCodeDiscoversSetupCfgGuiScriptsAndMultilinePackageExports(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "setup.cfg"), `[options.entry_points]
gui_scripts =
    viewer = app.gui:main
`)
	writeFile(t, filepath.Join(dir, "app", "__init__.py"), `__all__: list[str] = [
    "public",
]
`)
	writeFile(t, filepath.Join(dir, "app", "gui.py"), `from app.live import run

def main():
    return run()
`)
	writeFile(t, filepath.Join(dir, "app", "live.py"), `from app.loader import load

def run():
    return load("plugins").activate()
`)
	writeFile(t, filepath.Join(dir, "app", "public.py"), `def facade():
    return "exported"
`)
	writeFile(t, filepath.Join(dir, "app", "orphan.py"), `def cleanup():
    return "legacy"
`)

	report := runPythonToolchainDeadCodeScanWithConfig(t, dir, true, func(cfg *codeguard.Config) {
		cfg.Targets[0].Entrypoints = nil
	})

	assertToolchainDeadCodePath(t, report, "app/orphan.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/gui.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/live.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/public.py")
}

func TestPythonToolchainDeadCodeCoversFrameworkRuntimeAndVendorFalsePositives(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "pyproject.toml"), `[project.gui-scripts]
viewer = "app.gui:main"
`)
	writeFile(t, filepath.Join(dir, "app", "__init__.py"), `from . import exported

__all__ = [
    "exported",
]
`)
	writeFile(t, filepath.Join(dir, "app", "gui.py"), `from app.live import run

def main():
    return run()
`)
	writeFile(t, filepath.Join(dir, "app", "live.py"), `from app.loader import load

def run():
    return load("plugins").activate()
`)
	writeFile(t, filepath.Join(dir, "app", "loader.py"), `import importlib

def load(name):
    return importlib.import_module("app.plugins")
`)
	writeFile(t, filepath.Join(dir, "app", "runtime.py"), `def load(name):
    return __import__("app.plugins")
`)
	writeFile(t, filepath.Join(dir, "app", "plugins.py"), `def activate():
    return "plugin"
`)
	writeFile(t, filepath.Join(dir, "app", "routes.py"), `from fastapi import FastAPI

app = FastAPI()

@app.get("/health")
def health():
    return "ok"
`)
	writeFile(t, filepath.Join(dir, "app", "tasks.py"), `from celery import shared_task

@shared_task
def rebuild():
    return "queued"
`)
	writeFile(t, filepath.Join(dir, "app", "signals.py"), `from django.dispatch import receiver

@receiver(object())
def on_event(sender, **kwargs):
    return None
`)
	writeFile(t, filepath.Join(dir, "app", "exported.py"), `def facade():
    return "exported"
`)
	writeFile(t, filepath.Join(dir, "vendor", "legacy.py"), `def vendor_helper():
    return "vendor"
`)
	writeFile(t, filepath.Join(dir, "app", "orphan.py"), `def cleanup():
    return "legacy"
`)

	report := runPythonToolchainDeadCodeScanWithConfig(t, dir, true, func(cfg *codeguard.Config) {
		cfg.Targets[0].Entrypoints = nil
	})

	assertToolchainDeadCodePath(t, report, "app/orphan.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/gui.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/live.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/loader.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/runtime.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/plugins.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/routes.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/tasks.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/signals.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/exported.py")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "vendor/legacy.py")
}

func TestPythonToolchainDeadCodeReportsTrustedVultureText(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "app", "__init__.py"), "")
	writeFile(t, filepath.Join(dir, "app", "__main__.py"), `def main():
    return "ok"
`)
	writeFile(t, filepath.Join(dir, "app", "legacy.py"), `def cleanup():
    return "legacy"
`)
	writeFile(t, filepath.Join(dir, ".codeguard", "vulture.txt"), `app/legacy.py:1: unused function 'cleanup' (90% confidence)
`)

	report := runPythonToolchainDeadCodeScanWithConfig(t, dir, true, func(cfg *codeguard.Config) {
		cfg.Checks.QualityRules.DeadCode.Python.Reports = []string{".codeguard/vulture.txt"}
	})

	assertToolchainDeadCodePathMessageContains(t, report, "app/legacy.py", "trusted dead-code report")
}

func TestPythonToolchainDeadCodeReportsTrustedJSONAndSkipsLowConfidence(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "app", "__init__.py"), "")
	writeFile(t, filepath.Join(dir, "app", "__main__.py"), `def main():
    return "ok"
`)
	writeFile(t, filepath.Join(dir, "app", "dead.py"), `def unused():
    return "dead"
`)
	writeFile(t, filepath.Join(dir, "app", "maybe.py"), `def maybe():
    return "dynamic"

__all__ = ["maybe"]
`)
	writeFile(t, filepath.Join(dir, ".codeguard", "dead-code.json"), `{
  "findings": [
    {"path": "app/dead.py", "line": 1, "kind": "unused function", "name": "unused", "confidence": 95},
    {"path": "app/maybe.py", "line": 1, "kind": "unused function", "name": "maybe", "confidence": 60}
  ]
}`)

	report := runPythonToolchainDeadCodeScanWithConfig(t, dir, true, func(cfg *codeguard.Config) {
		cfg.Checks.QualityRules.DeadCode.Python.Reports = []string{".codeguard/dead-code.json"}
	})

	assertToolchainDeadCodePathMessageContains(t, report, "app/dead.py", "trusted dead-code report")
	assertToolchainDeadCodeFindingPathAbsent(t, report, "app/maybe.py")
}

func runPythonToolchainDeadCodeScan(t *testing.T, dir string, enabled bool) codeguard.Report {
	t.Helper()
	return runPythonToolchainDeadCodeScanWithConfig(t, dir, enabled, nil)
}

func runPythonToolchainDeadCodeScanWithConfig(t *testing.T, dir string, enabled bool, mutate func(*codeguard.Config)) codeguard.Report {
	t.Helper()
	cfg := codeguard.ExampleConfig()
	cfg.Name = "python-toolchain-dead-code-test"
	cfg.Targets = []codeguard.TargetConfig{{
		Name:        "py",
		Path:        dir,
		Language:    "python",
		Entrypoints: []string{"app/__main__.py"},
	}}
	cfg.Checks.Quality = true
	cfg.Checks.Design = false
	cfg.Checks.Security = false
	cfg.Checks.Prompts = false
	cfg.Checks.CI = false
	disabled := false
	cfg.Checks.Performance = &disabled
	cfg.Checks.SupplyChain = false
	cfg.Checks.Delivery = &disabled
	cfg.Checks.Reliability = &disabled
	cfg.Checks.Data = &disabled
	cfg.Checks.Observability = &disabled
	cfg.Checks.Operations = &disabled
	cfg.Checks.Change = &disabled
	cfg.Checks.Contracts = &disabled
	cfg.Checks.Context = &disabled
	cfg.Checks.QualityRules.AIChecks.DeadCode = &disabled
	if enabled {
		enabled := true
		cfg.Checks.QualityRules.DeadCode = codeguard.QualityDeadCodeConfig{
			Enabled: &enabled,
			Mode:    "toolchain",
			Level:   "warn",
		}
	}
	if mutate != nil {
		mutate(&cfg)
	}
	report, err := codeguard.Run(context.Background(), cfg)
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	return report
}
